### ISSUE TITLE
establish SLOs for MozMEAO sites

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1000]
Let's start thinking about setting [SLOs](https://en.wikipedia.org/wiki/Service-level_objective) for our sites.

- how will we measure?
    - availability, throughput, response time etc 
    - `1 - availability = error budget`
    - what is the interval?
- how we are alerted of SLO violations?
- what happens if we miss an SLO?
  - prioritize resources to fix availability
- what sites do we establish an SLO for?
    - bedrock
    - snippets
    - basket
    - basket-admin
    - nucleus
    - irlpodcast
    - viewsourceconf
- New Relic can export CSV data

- read about SRE and error budget [here](https://landing.google.com/sre/interview/ben-treynor/)

**Comment by duallain** [comment]
@bensternthal do you want to take this work out of this jira ticket and put it on your docket to discuss with IT? It probably isn't work that I'd normally do (a consumer of the choice about SLA/SLO more than creator of it).  Happy to talk more, but it seems like a different type of work than most of the other tickets.  Less implement something, more decide something.

**Comment by bensternthal** [comment]
Agreed it is on me and already something Travis and I have chatted about. @duallain You mentioned a Jira ticket, can you send a link over and I'll take a peek

**Comment by duallain** [comment]
Sorry, not jira ticket.  This github ticket.  I'll close it on down. Jira/github tickets are interchangeable in my head.  Sorry bout that.
