### ISSUE TITLE
Evaluate Static Site Admin Tools

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#1002]
Several are available and have very different properties. These are also referred to as "Headless CMS".

## OSS

* [Netlify CMS](https://www.netlifycms.org/)
  * No hosting
  * OSS
  * Just HTML + JS to deploy, then uses the Github API to store and retrieve data
* [Cockpit](https://getcockpit.com/)
  * Self hosted
  * OSS
  * Similar to Contentful, but less featureful
* Custom Django App (maybe Nucleus)
  * Self hosted
  * OSS
  * Infinitely customizable

## 3rd party hosted

All of these:

* 3rd party hosted
* Costs $$ (Not OSS)
* Good API and tools for editors and developers 
* Good image processing tools

These are therefore very good options and would significantly lessen the load on our team. We could well run into situations where we want a feature our provider doesn't offer however. And I always prefer creating data models in code rather than an admin. Below are some of the best of these ranked in order of popularity on Twitter.

* [Contentful](https://www.contentful.com/)
* [Prismic](https://prismic.io/)
* [Cosmic JS](https://cosmicjs.com/)
* [GraphCMS](https://graphcms.com/)
* [DatoCMS](https://www.datocms.com/)

A good list of "Headless CMS" offerings: https://headlesscms.org/

**Comment by pmac** [comment]
@hoosteeno is this issue worth keeping around, or have we definitely landed on a 3rd party solution and one in particular?

**Comment by hoosteeno** [comment]
Let's close for now, we can always reopen.
