### ISSUE TITLE
setup monitoring accts for OI

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1005]
- [x] New Relic
- [x] Sentry (we don't admin, requires a bug)
- [x] DeadMansSnitch
- [x] DockerHub

for Tasos, Nemo, Henrik

**Comment by hmitsch** [comment]
CC'ing @akatsoulas (Tasos) and @johngian (Nemo) on this. 😄

**Comment by metadave** [comment]
@hmitsch @akatsoulas @johngian if you don't have an account on https://keybase.io/, can you please set one up? Once you have an account, can you forward me your account name so I can send you some things securely?

**Comment by metadave** [comment]
Sentry request [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1521890)

**Comment by hmitsch** [comment]
@metadave my keybase account is: https://keybase.io/hmitsch

**Comment by metadave** [comment]
Sentry accounts setup via https://bugzilla.mozilla.org/show_bug.cgi?id=1521890#c1

**Comment by johngian** [comment]
@metadave Yes that's my keybase account

**Comment by metadave** [comment]
Please install the Keybase desktop app. Once installed, you should now have access to a team folder under Files -> Team -> (1 or more team names).

**Comment by metadave** [comment]
@akatsoulas @johngian @hmitsch You'll need to create dockerhub accounts, then I'll invite you to the org.

**Comment by akatsoulas** [comment]
@metadave that would be `akatsoulas` for DockerHub.

https://hub.docker.com/u/akatsoulas

**Comment by johngian** [comment]
@metadave here is my Dockerhub account:
https://hub.docker.com/u/johngian

**Comment by metadave** [comment]
@akatsoulas @johngian Papertrail invites have been sent
