### ISSUE TITLE
reduce MozMEAO dependency on DataDog

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1006]

**Comment by glogiotatidis** [comment]
Snippets uses datadog for statsd stats and for monitoring Snippets GA bridge ("soon" to be decommed)

Also Kitsune monitors the celery queue size

**Comment by pmac** [comment]
Basket also uses datadog for statsd and creating dashboards with said data. e.g.:

https://p.datadoghq.com/sb/279ea5216-630e79664d

**Comment by jgmize** [comment]
Stackdriver has a [statsd plugin](https://cloud.google.com/monitoring/agent/plugins/statsd) currently in beta that we could try as part of #1040.

**Comment by glogiotatidis** [comment]
> monitoring Snippets GA bridge ("soon" to be decommed)

this has been decommissioned
