### ISSUE TITLE
HTTP_X_FORWARDED_PROTO not set for for snippets-*.virginia.moz.works

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#101]
The current ELB setup (see also #74) does not set `HTTP_X_FORWADED_PROTO` and thus Django cannot be aware whether a connection is secure or not.

On snippets this breaks `http` to `https` redirection, which is minor since the clients have hardcoded HTTPS by default and the CDN we're behind uses HTTPS to reach to this origin.

Nevertheless this is something we need to figure out at some point for other apps as well.

**Comment by metadave** [comment]
I believe this change has to be outside of the context of the [Kubernetes annotations](https://github.com/mozmar/infra/blob/master/k8s/install/stage2_functions.sh#L210-L242), so we'll need to script something with the awscli.

**Comment by glogiotatidis** [comment]
Can be fixed using k8s annotations! See https://github.com/kubernetes/kubernetes/issues/36845#issuecomment-268706455

**Comment by glogiotatidis** [comment]
I'm going to work on careers today and fix this one tomorrow.

**Comment by glogiotatidis** [comment]
See also #159

**Comment by jgmize** [comment]
Implemented http->https redirects in https://github.com/mozmar/infra/pull/163 instead.

**Comment by glogiotatidis** [comment]
While redirects solve the `http->https` redirect, Django still needs a way to know that a request came over a secure channel. Any ideas on how to fix that?

**Comment by jgmize** [comment]
> While redirects solves the http->https redirect, Django still needs a way to know that a request came over a secure channel. Any ideas on how to fix that?

Why does django need to know? If we set `SECURE_SSL_REDIRECT=False` then the app shouldn't try to do the redirect itself.  My understanding is that we should still be able to set `CSRF_COOKIE_SECURE` and `SESSION_COOKIE_SECURE` to True independently of that method. Is there something else that's not working due to the `http.request.is_secure` method returning false?

**Comment by glogiotatidis** [comment]
The thing is that redirects rely on `request.is_secure()` and [`request.is_secure()` relies on `SECURE_PROXY_SSL_HEADER`](https://github.com/django/django/blob/3eb679a86956d9eedf24492f0002de002f7180f5/django/http/request.py#L188-L198) which is what HTTP_X_FORWARDED_PROTO is needed for.

`is_secure()` is used [all over](https://github.com/django/django/search?p=1&q=is_secure&type=&utf8=%E2%9C%93) [the place](https://github.com/mozilla/django-session-csrf/search?utf8=%E2%9C%93&q=is_secure&type=)

I guess we can hardcode things in wsgi.py but I don't like this approach,  thus I'm asking for alternatives.

**Comment by glogiotatidis** [comment]
Re-opening b/c I don't want to lose track of the discussion. We still need to figure out HTTP_X_FORWADED_PROTO

**Comment by jgmize** [comment]
We ran into an issue on this in bedrock too, and after some discussion @pmac implemented an alternative to x-forwarded-proto using [an HTTPS env var and an WSGIRequest subclass](https://github.com/mozilla/bedrock/commit/8124b66cb3f4f6faa337dde999df104145ebb29c).
