### ISSUE TITLE
setup MozMEAO office hours with Marketing

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1016]

**Comment by jpetto** [comment]
Based on the experience of the websites team holding office hours and my own gut feeling (remember those?), I propose the following as a starting point:

- I'll proactively reach out via Slack to a designated member of each team [0] to get an update on what they've got a-cookin'. This would be very casual, of minor interruption (less so than a video call, anyway), and very flexible on day/time (if needed).
- I'll make sure each designated member knows they can reach me on Slack or via email with questions whenever they need to. [1]
- I'll answer questions as-needed in the most appropriate form - Vidyo, Slack, email. If I can't answer something, I'll know who to pass the question on to - at which point I'll give details to that person and have _them_ contact the person asking the question (i.e. I'll be the liaison mitigated the "cold call" factor).

Ultimately I think this is a relationship/comfort building exercise/role/change that could _really_ improve efficiency, camaraderie, and overall job enjoyment. Or, maybe it won't work. Worth a try though.

@metadave What do you think about the above? See any details that won't work, or that are missing?

[0] Maybe every single team doesn't need this - we can iron out this detail.
[1] This might blow up into a big time commitment, which I think would actually be a good problem.
