### ISSUE TITLE
Decide how best to have Gitlab do PR testing and deployment

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#1028]
Depending on the outcome of #1027 we'll need to ensure that GitLab CI won't run pull-request jobs on the runner box(es) that contain deployment secrets. You can setup the runners to only be used for "protected branches", so that's a good place to start. But we'll also have to link GitLab with Github for CI.

related to #329 
/cc @jpetto

**Comment by jgmize** [comment]
We use a [tags](https://docs.gitlab.com/ee/ci/yaml/#tags) when configuring jobs to select runners, and we define jobs that require our runners with [rules](https://docs.gitlab.com/ee/ci/yaml/#rules] or [only](https://docs.gitlab.com/ee/ci/yaml/#onlyexcept-basic) to limit them to only run on branches from our fork to ensure that only those with commit access to the repo can trigger code execution on our runners.
