### ISSUE TITLE
Snippets GCP migration

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#1041]
[Draft proposal](https://docs.google.com/document/d/1-iPTIQoHRA9BYuTTgPw0SUkEE2jZZlRgz0e9-9KxjIQ)

**Comment by glogiotatidis** [comment]
For the database migration and after we're done with https://github.com/mozmeao/snippets-service/pull/950 these are good discussions to migrate the data from one DB engine to another

https://gist.github.com/sirodoht/f598d14e9644e2d3909629a41e3522ad
