### ISSUE TITLE
transfer snippets CDN to MozMEAO AWS account

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1042]
@mozmeao/theconn let's talk about moving the snippets Cloudfront distribution from IT to the MozMEAO AWS account. MDN worked with AWS support to reuse the domain name, I think we'd need to do the same.

We would need:

- [ ] Terraform automation
- [ ] test plan
- [ ] stage CDN
- [ ] prod CDN

anything else?

https://github.com/mdn/infra/issues/112
https://github.com/mdn/infra/issues/43

cc @bensternthal

**Comment by metadave** [comment]
This may impact snippets migration to GKE: https://github.com/mozmeao/infra/issues/1041

**Comment by jgmize** [comment]
I think we should also discuss the cost, benefits, and estimated level of effort of migrating snippets to a new cloudfront distribution vs another CDN provider, such as Cloudflare.

**Comment by metadave** [comment]
> I think we should also discuss the cost, benefits, and estimated level of effort of migrating snippets to a new cloudfront distribution vs another CDN provider, such as Cloudflare.

+1

**Comment by glogiotatidis** [comment]
+1 I wanted to do this for a while!

Somewhat related is that I'm working on things like https://github.com/mozmeao/snippets-service/issues/841 which I expect to significantly reduce the CDN transfer costs.

**Comment by jgmize** [comment]
This issue is also being tracked in https://jira.mozilla.com/browse/SRE-313 which is a medium priority issue in the [current IT SRE sprint](https://jira.mozilla.com/secure/RapidBoard.jspa?rapidView=95&view=planning) and @limed and I hope to find some time to work together on it this week.

**Comment by glogiotatidis** [comment]
@jgmize could you please update on status?

**Comment by jgmize** [comment]
@limed & I have some time on the calendar to work on this tomorrow morning. Next actions:
- [ ] set up a cert via ACM valid for `snippets.cdn.mozilla.net` and `snippets-prod-cdn.moz.works`
  - [ ] add DNS entry required for validation of domain cert for ACM
- [ ] update https://github.com/mozmeao/infra/pull/1158/files with the ARN of the new cert
- [ ] `terraform apply`
- [ ] add `snippets-prod-cdn.moz.works` DNS entry
- [ ] test distribution
- [ ] schedule move with AWS support

**Comment by jgmize** [comment]
@glogiotatidis see above and https://github.com/mozmeao/infra/pull/1158#issuecomment-526343628 

@limed will be doing some further validation and filing a support ticket with AWS for the transfer of `snippets.cdn.mozilla.net` to the new distribution in our account. We are hoping to complete the move next Wednesday, 2019-09-04.

**Comment by glogiotatidis** [comment]
What's great news! Thank you both :beers:

**Comment by jgmize** [comment]
`snippets.cdn.mozilla.net` is now pointed to distribution E2V5HQXONSYXSD in our account. Looking through the logs and verifying with curl things appear to be working for all of the requests that are coming through, but the traffic volume appears to be lower than expected based on the numbers reported by cloudfront so far relative to the throughput previously reported by the distribution in the other account. This issue has been raised with AWS support, and we are continuing to monitor.

**Comment by metadave** [comment]
awesome, thanks @jgmize and @limed!

**Comment by jgmize** [comment]
@limed figured out that the reason we weren't getting all of the traffic we expected was because the browser has [pinned the cert for *.cdn.mozilla.net](https://dxr.mozilla.org/mozilla-central/source/security/manager/tools/PreloadedHPKPins.json#192) to only recognize certs signed from a limited list of CAs, which Amazon is not on, which caused errors like the screenshot below:

![image](https://user-images.githubusercontent.com/161718/64304808-e8b5b080-cf52-11e9-9691-d60d6d4115a9.png)

@limed and I worked with @cshields to get a duplicate of the existing digicert signed cert for the new distribution, which resolved the issue. However, this cert will expire in 149 days and we will need to solve the HPKP issue with a newly issued cert before then.

**Comment by cshields** [comment]
AIUI, key pinning should only pin to the fingerprint if specified by using the Public-Key-Pins header, which snippets does not.  However, as @jgmize pointed out it is a subdomain of a pin to a list of CAs (in this case, digicert and LE).

So - I'm pretty sure the cert renewal resolution in this case will be to issue a new cert from one of those CAs and move on.  I feel more confident in that being the case as the re-issue of the cert we did tonight came as a new serial number and fingerprint and worked fine (whereas actual cert pinning would block a different fingerprint).

hth!

**Comment by glogiotatidis** [comment]
Thanks for completing this folks! @jgmize I'll add an item to our next 1:1 agenda to discuss how to move fwd with the cert resolution. What cshields suggests sounds like the easiest way to go fwd.
:beers: 

I guess this is OK to close now?
