### ISSUE TITLE
Update MozMEAO repos to use ci.vpn1.moz.works

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1043]
- [x] bedrock
- [x] kitsune
- [x] nucleus
- [x] basket
- [x] snippets
- [x] irlpodcast
- [x] viewsource

**Comment by pmac** [comment]
What does this mean exactly? I know that the slack notification scripts output links to the old domain, so we'll need to update those. Is that it? Are there README links as well or something like that?

**Comment by metadave** [comment]
any links that refer to ci.us-west.moz.works should change to ci.vpn1.moz.works. I'd like to disable the ci.us-west.moz.works ELB at some point in the near future.
