### ISSUE TITLE
Verify ownership for search console via DNS Record

### ISSUE THREAD

**Issue by rraue** [mozmeao/infra#1044]
The Google search console has a new feature for complete domain views and I cant verify this with GA like we do usually.
string: google-site-verification=E1vBHtOW-D9IlAj-pbRM-8PrOSiPDT48lrwRlW82ysw
<img width="587" alt="screenshot 2019-02-28 at 16 19 03" src="https://user-images.githubusercontent.com/36700618/53579524-ff311880-3b79-11e9-83fc-35fa5a75636d.png">

**Comment by metadave** [comment]
done
