### ISSUE TITLE
careers static hosting stuff

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1053]
- [x] add scheduled builds
- [x] update prod Greenhouse webhook
- [x] DNS changes
https://github.com/mozmeao/infra/pull/1052

**Comment by glogiotatidis** [comment]
- Updated `production` branch with `master`
- Re-enabled scheduled build
- Added #meao-alerts slack channel for Greenhouse webhook errors
- Updated and tested GH webhooks for both `master` and `production`
