### ISSUE TITLE
decom careers K8s infra

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1058]
- [ ] ACM certs
- [x] New Relic synthetics monitors

**Comment by glogiotatidis** [comment]
See 
 - https://github.com/mozmeao/lumbergh/issues/370
 - https://github.com/mozmeao/lumbergh/issues/367

**Comment by metadave** [comment]
let's wait until these issues have been resolved first:
- https://github.com/mozmeao/infra/issues/1076
- https://github.com/mozmeao/infra/issues/1064

**Comment by glogiotatidis** [comment]
I finished with   mozmeao/lumbergh#370 and mozmeao/lumbergh#367

https://github.com/mozmeao/infra/pull/1087

We still need to remove 

 - ELBs
 - ACM certs
 - Route53 entries
   - [ ] careers-prod.frankfurt.moz.works
   - [ ] careers-prod.oregon-b.moz.works
   - [ ] careers-stage.oregon-b.moz.works

Do **not** remove `careers-stage.moz.works` and `careers-prod.moz.works`

**Comment by metadave** [comment]
New Relic APM alerts for careers-prod-oregon-b and careers-prod-frankfurt disabled

**Comment by metadave** [comment]
done!

**Comment by metadave** [comment]
careers-prod, careers-stage ELB's unbound from frankfurt + oregon nodes ASGs

**Comment by metadave** [comment]
it done!
