### ISSUE TITLE
investigate careers performance

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1064]

**Comment by glogiotatidis** [comment]
For comparison the k8s served version without CDN scores slightly better (78 vs 76)

![image](https://user-images.githubusercontent.com/584352/56267111-8caed480-60f6-11e9-8b5e-9b47cfdd1c79.png)

**Comment by glogiotatidis** [comment]
https://github.com/mozmeao/lumbergh/pull/410

**Comment by glogiotatidis** [comment]
I think the score from PageSpeed has something to say but it can differ significantly from run to run, probably due to CF cache warmup.

I based my work on the suggested optimization opportunities

**Comment by glogiotatidis** [comment]
After the work in mozmeao/lumbergh#410 I get today

88 for mobile and 98 for desktop.Site feels really snappy too.

@metadave you think we can close this one and start work on https://github.com/mozmeao/infra/issues/1058?


![image](https://user-images.githubusercontent.com/584352/56494936-a720ed80-64fc-11e9-8e5e-3d5209e479c1.png)
![image](https://user-images.githubusercontent.com/584352/56494946-b0aa5580-64fc-11e9-8425-9c03525c7c0c.png)

**Comment by metadave** [comment]
@glogiotatidis yes!

**Comment by glogiotatidis** [comment]
w00t! closing this one
