### ISSUE TITLE
Make Sharp Sans available for use on mozilla.org

### ISSUE THREAD

**Issue by stephaniehobson** [mozmeao/infra#1071]
We have acquired a license to use Sharp Sans on all of mozilla.org and with that license comes new files that need to replace the current ones on the server with the same cache and content types.

I'll email the files to @metadave

**Comment by stephaniehobson** [comment]
Just the WOFF and WOFF2 are needed.

**Comment by metadave** [comment]
https://gist.github.com/metadave/92734e8c766f34f643b22c8dd16ed1a7
