### ISSUE TITLE
improve cdn caching for careers

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1076]
wip: https://github.com/mozmeao/lumbergh/pull/402

**Comment by glogiotatidis** [comment]
https://github.com/mozmeao/lumbergh/pull/410

**Comment by glogiotatidis** [comment]
Before https://www.webpagetest.org/result/190417_SR_bb13a144cd1f2ac0f9bb8eafdf7959bb/
![image](https://user-images.githubusercontent.com/584352/56287169-5425ef80-6124-11e9-9fc0-01090775434c.png)


After https://www.webpagetest.org/result/190417_P1_00adc04626ea0b98fba0ce20467ab7ed/
![image](https://user-images.githubusercontent.com/584352/56287154-4a03f100-6124-11e9-9e8f-46e8aa72cad3.png)

**Comment by glogiotatidis** [comment]
I guess we can mark this fixed ;)
