### ISSUE TITLE
Careers RSS feed not setting correct content-type

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#1086]
Although stage returns 
`content-type: application/rss+xml`

prod returns
`content-type: text/html`

Tested with 
`curl https://careers.mozilla.org/feed/ -I`

@metadave I remembered we talked about this and you created a fix. Probably not applied to production?

**Comment by metadave** [comment]
@glogiotatidis correct, I see that the fix isn't in prod, only stage. I will fix.

**Comment by bensternthal** [comment]
Verified fixed in prod.
