### ISSUE TITLE
resize Ireland bastion

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1103]
Let's bump the `t2.nano` Ireland bastion up to an `m5.large` to see if it helps connectivity issues for @akatsoulas.

for the `m5.large`, it's 24.64/month at 10% utilization, and up to 243.61/month for 100% utilization. I doubt the utilization will be very high for extended periods.

**Comment by metadave** [comment]
if the gitlab-runner automation needs to be updated, lets run [this](https://github.com/mozmeao/infra-private/pull/200/files) along with any new changes

**Comment by glogiotatidis** [comment]
Steps:
 - [ ] Create new `m5.large` instance in Ireland
 - [ ] Limit SSH access to new bastion to my IP in Security Group.
 - [ ] Copy ansible host_vars of current bastion to new runner
 - [ ] Apply playbook
 - [ ] Accept new host in zt network
 - [ ] Add new bastion public IP to security groups
    - [ ] Oregon-A master
    - [ ] Oregon-B Master
    - [ ] Frankfurt Master
    - [ ] CI SSH
    - [ ] GitLab Runner SSH
 - [ ] Remove zt IPs from old bastion and add to new bastion
 - [ ] Reboot new bastion
 - [ ] Shutdown old bastion
 - [ ] Validate that all fwds work
 - [ ] Terminate old bastion
 - [ ] Rename `new bastion` to `bastion` in AWS Console
 - [ ] Update infra-private repo

**Comment by glogiotatidis** [comment]
While at it I removed `0.0.0.0/24` @ Port 443 inbound rule for `ci.us-west.moz.works` and other personal entries.

**Comment by glogiotatidis** [comment]
Verified with @akatsoulas that things work but inconclusive if we got any speed improvements.
