### ISSUE TITLE
Basket CI/CD

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#1104]
Move from Jenkins to Gitlab

**Comment by jpetto** [comment]
I believe the below is the complete list, but should be verified:

- oregon-b
  - dev
    - [ ] namespace
      - `oregon-b/basket-dev/ns.yaml` in basket-config
    - [ ] service
      - `oregon-b/basket-dev/web-svc.yaml` in basket-config
    - [ ] web deployment
      - `oregon-b/basket-dev/web-deploy.yaml` in basket-config
    - [ ] worker deployment
      - `oregon-b/basket-dev/worker-deploy.yaml` in basket-config
    - [ ] donateworker deployment
      - `oregon-b/basket-dev/donateworker-deploy.yaml` in basket-config
    - [ ] secrets
      - `oregon-b/basket-dev/secrets.yaml` in basket-private-config
  - stage
    - [ ] namespace
      - `oregon-b/basket-stage/ns.yaml` in basket-config
    - [ ] service
      - `oregon-b/basket-stage/web-svc.yaml` in basket-config
    - [ ] web deployment
      - `oregon-b/basket-stage/web-deploy.yaml` in basket-config
    - [ ] worker deployment
      - `oregon-b/basket-stage/worker-deploy.yaml` in basket-config
    - [ ] donateworker deployment
      - `oregon-b/basket-stage/donateworker-deploy.yaml` in basket-config
    - [ ] fxaeventsworker deployment
      - `oregon-b/basket-stage/fxaeventsworker-deploy.yaml` in basket-config
    - [ ] secrets
      - `oregon-b/basket-stage/secrets.yaml` in basket-private-config
  - prod
    - [ ] namespace
      - `oregon-b/basket-stage/ns.yaml` in basket-config
    - [ ] service
      - `oregon-b/basket-stage/web-svc.yaml` in basket-config
    - [ ] clock deployment
      - `oregon-b/basket-stage/clock-deploy.yaml` in basket-config
    - [ ] web deployment
      - `oregon-b/basket-stage/web-deploy.yaml` in basket-config
    - [ ] worker deployment
      - `oregon-b/basket-stage/worker-deploy.yaml` in basket-config
    - [ ] donateworker deployment
      - `oregon-b/basket-stage/donateworker-deploy.yaml` in basket-config
    - [ ] fxaworker deployment
      - `oregon-b/basket-stage/fxaworker-deploy.yaml` in basket-config
    - [ ] fxaeventsworker deployment
      - `oregon-b/basket-stage/fxaeventsworker-deploy.yaml` in basket-config
    - [ ] secrets
      - `oregon-b/basket-stage/secrets.yaml` in basket-private-config
- frankfurt
  - dev
    - [ ] namespace
      - `frankfurt/basket-dev/ns.yaml` in basket-config
    - [ ] service
      - `frankfurt/basket-dev/web-svc.yaml` in basket-config
    - [ ] web deployment
      - `frankfurt/basket-dev/web-deploy.yaml` in basket-config
    - [ ] secrets
      - `frankfurt/basket-dev/secrets.yaml` in basket-private-config
  - stage
    - [ ] namespace
      - `frankfurt/basket-stage/ns.yaml` in basket-config
    - [ ] service
      - `frankfurt/basket-stage/web-svc.yaml` in basket-config
    - [ ] web deployment
      - `frankfurt/basket-stage/web-deploy.yaml` in basket-config
    - [ ] worker deployment
      - `frankfurt/basket-stage/worker-deploy.yaml` in basket-config
    - [ ] secrets
      - `frankfurt/basket-stage/secrets.yaml` in basket-private-config
  - prod
    - [ ] namespace
      - `frankfurt/basket-prod/ns.yaml` in basket-config
    - [ ] service
      - `frankfurt/basket-prod/web-svc.yaml` in basket-config
    - [ ] clock deployment
      - `frankfurt/basket-prod/clock-deploy.yaml` in basket-config
    - [ ] web deployment
      - `frankfurt/basket-prod/web-deploy.yaml` in basket-config
    - [ ] worker deployment
      - `frankfurt/basket-prod/worker-deploy.yaml` in basket-config
    - [ ] secrets
      - `frankfurt/basket-prod/secrets.yaml` in basket-private-config

**Comment by jgmize** [comment]
We also have basket deployments in oregon-a:
```
$ oregon-a
$ for ns in $(kubectl get ns | awk '/basket/ {print $1}'); do echo $ns; kubectl get deploy -n $ns; done
basket-admin
NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
basket-admin-web   1         1         1            1           1y
basket-admin-stage
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
basket-admin-stage-web   1         1         1            1           1y
basket-dev
NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
basket-dev-web      1         1         1            1           1y
basket-dev-worker   1         1         1            1           1y
basket-prod
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
basket-prod-web      4         4         4            4           1y
basket-prod-worker   4         4         4            4           1y
basket-stage
NAME                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
basket-stage-web      1         1         1            1           1y
basket-stage-worker   2         2         2            2           1y
```

**Comment by jpetto** [comment]
next steps (2019/08/07):

1. add `.gitlab-ci.yaml` in `basket` repo to keep images up to date in `basket-config` deployment files
2. add `CLUSTER_NAME` env var to deployment files in `basket-config`
3. add `.gitlab-ci.yaml` in `basket-config`

**Comment by jgmize** [comment]
The basket CI/CD pipeline has been moved from Jenkins to Gitlab.
