### ISSUE TITLE
Route53 automation

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1108]
/remind me in 1 day to review

**Comment by metadave** [comment]
applied

tokyo tf update: https://github.com/mozmeao/infra-private/pull/204

/remind me in 2 days

**Comment by jgmize** [comment]
also need to remove route53 entries for https://github.com/mozmeao/snippets-service/issues/545#issuecomment-485384942

**Comment by metadave** [comment]
https://github.com/mozmeao/infra-private/pull/209

will follow up with PR's for https://github.com/mozmeao/snippets-service/issues/545#issuecomment-485384942 and sumo decom.
