### ISSUE TITLE
Eval downsizing MariaDB Instances in Oregon and Frankfurt

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#1114]
Since snippets moved to pgsql maybe it's worth evaluating whether we can downsize mariadb clusters in both oregon and frankfurt to save some $$.

From the `monitoring` tab of the oregon instance, the db appears to be pretty bored (~5% cpu utilization, more than 2gb ram free, interestingly more write IOPS than read?)

**Comment by metadave** [comment]
[Oregon/Frankfurt DBs are reserved instances](https://docs.google.com/spreadsheets/d/10f0u-AYJkQo0Ft2IctTgjdkXMvnd6-v0JoNk9Ei10BQ/edit#gid=780883974), so they've already been paid for. We should schedule this later in the year when the RIs have to be renewed.

**Comment by pmac** [comment]
Basket could move to pgsql as well whenever we're ready to evaluate our reserved instances.

**Comment by metadave** [comment]
[RI's expire Sept 20/28](https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#ReservedInstances:sort=formattedState), let's target Q3. 

Milestone created: https://github.com/orgs/mozmeao/projects/3#card-21751077
