### ISSUE TITLE
nucleus-stage frankfurt CI/CD 

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#1115]
Currently nucleus does not have a staging environment, only dev & prod. As a non-blocking task related to #988 we shall add one.
- [x] https://github.com/mozmeao/nucleus-config/issues/7
- [x] https://gitlab.com/mozmeao/nucleus-private-config/issues/3
- [x] https://github.com/mozmeao/nucleus-config/issues/8
- [x] https://github.com/mozilla/nucleus/issues/96

**Comment by jpetto** [comment]
@jgmize I think we're good here? Can we close this out?

**Comment by jgmize** [comment]
Yep, thanks
