### ISSUE TITLE
Remove SUMO datadog Monitor

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#1124]
When we're ready to decom SUMO, remember to remove the Datadog Celery queue monitor

https://app.datadoghq.com/monitors/5579780

**Comment by metadave** [comment]
Deleted, backup json stored [here](https://gist.githubusercontent.com/metadave/9b02918e95a9f6cfe05a98afdd925300/raw/745493b72de87ca6fe2a4267b13cf63545404db8/celerylagqueue.json)
