### ISSUE TITLE
tls version eval for MozMEAO sites

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1125]
https://twitter.com/iPullRank/status/1138504279931707392

**Comment by jgmize** [comment]
- www.mozilla.org
  - TLS terminated at Cloudflare
  - supports TLS 1.3
  - supports a minimum TLS version of 1.0
    - we need to continue maximize compatibility with older clients for this site so that they can download Firefox
  - see https://observatory.mozilla.org/analyze/www.mozilla.org#tls for more details
    - note that this does not yet check for TLS 1.3 compatibility, but the test linked from that tweet does
- All of our other sites' TLS are currently terminated at AWS ELBs or Cloudfront, which do not yet support TLS 1.3
  - We are evaluating moving the TLS termination for the other sites behind Cloudflare which would open up the possibility of enabling TLS 1.3 for these sites without waiting for AWS to support it
  - The minimum version of TLS supported on each of our sites is TLS 1.0 to maximize compatibility with older clients

**Comment by jgmize** [comment]
cc @rraue
