### ISSUE TITLE
decom bedrock demo namespaces in oregon-b

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1127]
current list of namespaces, checked items will be deleted!

- [ ] bedrock-demo                        
- [ ] bedrock-demo-1                      
- [ ] bedrock-demo-2                      
- [ ] bedrock-demo-3                      
- [ ] bedrock-demo-4                      
- [ ] bedrock-demo-5                      
- [ ] bedrock-demo-6                      
- [x] bedrock-demo-about                  
- [ ] bedrock-demo-achurchwell            
- [ ] bedrock-demo-agibson                
- [ ] bedrock-demo-craigcook              
- [x] bedrock-demo-cve-feed               
- [x] bedrock-demo-developer-newsletter   
- [x] bedrock-demo-election               
- [x] bedrock-demo-firefox-sync           
- [x] bedrock-demo-id-whatsnew            
- [x] bedrock-demo-jgmize                 
- [ ] bedrock-demo-jpetto                 
- [x] bedrock-demo-l10n-db                
- [ ] bedrock-demo-legal                  
- [x] bedrock-demo-navigation             
- [x] bedrock-demo-pipelinefree           
- [x] bedrock-demo-pmac                   
- [x] bedrock-demo-pr7196                 
- [x] bedrock-demo-protocol               
- [x] bedrock-demo-seo-new                
- [x] bedrock-demo-seo-vpn                
- [x] bedrock-demo-seo-windows            
- [ ] bedrock-demo-shobson                
- [ ] bedrock-integration-tests           

if your comment below got a :+1: from me, I've integrated your changes into the list above.

**Comment by amychurchwell** [comment]
- demo-id-whatsnew
can also be deleted.

**Comment by pmac** [comment]
Add...

* demo-pipelinefree
* demo-pmac

I can always recreate mine if need be.

**Comment by pmac** [comment]
It actually might be best to poll the team on which are in active use right now. they're easy enough to create that if no one outside of the team is looking for the URL we can delete everything but the `demo-[1-6]` ones.

**Comment by stephaniehobson** [comment]
I'm done with `demo-election` and `demo-protocol`.

I'm not done with `demo-shobson`.

I'm also done with `demo-6` but I used it because I couldn't find a free numbered demo. With Sam joining this is likely to be a more frequent problem so you can delete it but it might come back.

**Comment by pmac** [comment]
Oh. Does any numbered demo work with `demo-N.allizom.org`? That's the point of them right?

**Comment by metadave** [comment]
> Oh. Does any numbered demo work with demo-N.allizom.org? That's the point of them right?

That's how I thought it worked, I'll leave demo* as-is. We can add more later if needed. (Maybe it's a wildcard DNS record?)


Deis apps remaining:

```
bedrock-demo-1
bedrock-demo-2
bedrock-demo-3
bedrock-demo-4
bedrock-demo-5
bedrock-demo-6
bedrock-demo-achurchwell
bedrock-demo-agibson
bedrock-demo-craigcook
bedrock-demo-jgmize
bedrock-demo-jpetto
bedrock-demo-legal
bedrock-demo-pr7196
bedrock-demo-shobson
bedrock-integration-tests
```

**Comment by jgmize** [comment]
> Oh. Does any numbered demo work with demo-N.allizom.org? That's the point of them right?

Only demos 1-5 currently have an explicit mapping to www-demo[1-5].allizom.org. All other demos, numbered or not, are only mapped to the *.oregon-b.moz.works wildcard. The `*.allizom.org` wildcard was historically mapped to a load balancer cluster in the now-decommissioned SCL3 datacenter, and nothing appears to be listening on that IP any more. While this may open the possibility for our use of that wildcard in the future, I believe explicit CNAME mappings are still the best past forward, and would be happy to set up additional www-demo[X].allizom.org aliases if desired. Would 10 be sufficient, or perhaps 20?

**Comment by jgmize** [comment]
deleted bedrock-demo-jgmize

**Comment by metadave** [comment]
> Would 10 be sufficient, or perhaps 20?

10
