### ISSUE TITLE
Remove MIG Agents from infrastructure

### ISSUE THREAD

**Issue by arcrose** [mozmeao/infra#1128]
Hi folks!

Mozilla's Enterprise Information Security (EIS) team will be deprecating MIG in July starting with the removal of MIG Agents from Mozilla's infrastructure.  We would like to ask that this be taken care of at your earliest convenience in the hopes that our bringing down MIG's backend infrastructure will not result in any breakage on your side.

Thank you!
Please feel free to follow up with any questions.

**Comment by metadave** [comment]
MIG Daemonset deleted from:

- Frankfurt
- Oregon-A
- Oregon-B
- Iowa-a

**Comment by metadave** [comment]
thanks @arcrose!
