### ISSUE TITLE
decom SUMO VPN

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1129]
do we want to scale it down or keep it around Just In Case?

cc @glogiotatidis @jgmize

**Comment by jgmize** [comment]
I'm not aware of any reasons to keep the sumo VPN at this point.

**Comment by metadave** [comment]
we have the Ansible to spin a new bastion for RDS access if needed, I'm +1 on tearing it down.

**Comment by glogiotatidis** [comment]
On it!

## Task list
- [ ] Delete EC2
- [ ] Delete zerotier configuration

**Comment by glogiotatidis** [comment]
Done :rocket:
