### ISSUE TITLE
Broken http->https redirects on bedrock demos

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#1135]
- This was first noticed on https://bedrock-integration-tests.oregon-b.moz.works 
  - it was stuck in a redirect loop until @pmac removed the `DISABLE_SSL=false` setting
  - this eliminated the redirect loop, but now http requests are no longer redirected
- this applies to all bedrock demos
  - they all go through the same ELB
  - this ELB was originally created during the Deis workflow installation, but then altered directly via the AWS console
  - the k8s master recently re-applied the previous configuration
    - this also caused cert issues: #1134

**Comment by bensternthal** [comment]
Closing, if this proves problematic again we can re-open.
