### ISSUE TITLE
Decom product-details-json-watch Jenkins job 

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#1143]
https://ci.vpn1.moz.works/job/product-details-json-watch/

**Comment by pmac** [comment]
It's possible we can simply retire it in favor of https://github.com/mozilla/bedrock/issues/6998

**Comment by pmac** [comment]
I have a PR in for said issue, so once that merges and makes it to prod we can change this issue to be about decommissioning the product-details-json-watch jenkins job and [the repo it was updating](https://github.com/mozilla/product-details-json).

**Comment by metadave** [comment]
jenkins tho?

**Comment by pmac** [comment]
> jenkins tho?

I don't understand the question.

**Comment by metadave** [comment]
why not move this to Gitlab?

**Comment by pmac** [comment]
I just said in the comment above yours that we can decommission the jenkins job and repo and replace it with nothing. No need for Gitlab or anything else.

**Comment by jgmize** [comment]
Disabled https://ci.vpn1.moz.works/job/product-details-json-watch/
