### ISSUE TITLE
Verify ownership for search console via DNS Record for firefox.com

### ISSUE THREAD

**Issue by rraue** [mozmeao/infra#1153]
To get a *.firefox.com Search Console domain property, I need to verify via DNS record with the string: google-site-verification=sZbK1VU-6gaKN6c3idPKdVMfrpkypWTZrrQRJJ9xPUo

Its the same process like in #1044 

<img width="580" alt="Screenshot 2019-08-12 at 17 15 50" src="https://user-images.githubusercontent.com/36700618/62876261-dc0fb500-bd24-11e9-8690-c1f1478ef2e7.png">

**Comment by metadave** [comment]
hi @rraue, this team doesn't own firefox.com, but I'll see if someone in IT can help us out.

**Comment by rraue** [comment]
Entry already exists, clsoing this
