### ISSUE TITLE
Remove legacy clients support from Snippets CDNs

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#1167]
Snippet CDNs (prod and stage) are configured to support old clients without SNI support. Firefox supports SNI since version 2 and we're targeting only Firefox clients with these CDNs so we can safely switch to SNI setup and save some money.

**Comment by metadave** [comment]
we'll need to make sure https://github.com/mozmeao/infra/blob/master/apps/snippets/infra/global/cdn/main.tf is updated to reflect any changes.
