### ISSUE TITLE
cert for moz.org

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1168]

**Comment by metadave** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1588518

**Comment by pmac** [comment]
This will fix the nagios alerts we're seeing in the #meao-notices channel correct?

**Comment by jgmize** [comment]
I've uploaded the new cert to Cloudflare; the cert is propagating to their locations now.

**Comment by jgmize** [comment]
The new cert is deployed, and will expire Oct 21 2020.
