### ISSUE TITLE
blockaws | fluent container updates

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1172]

**Comment by bensternthal** [comment]
@pmac Do you know what this is?

**Comment by pmac** [comment]
No idea. Sorry :/ Maybe @duallain does?

**Comment by duallain** [comment]
Ben and I were talking out of band, but I don't know.  blockaws seems to be an mdnish thing that limed wrote.  fluent is the log aggregation.  I'm just not sure what the goal the update would have. (Maybe just the standard, keep it up to date for security patching).

**Comment by bensternthal** [comment]
Closing as none of us know what this is. If it becomes a thing we can revisit.
