### ISSUE TITLE
Gitlab runner disk space cleanup

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#1174]
- The AWS gitlab runner instance in frankfurt ran out of disk space today. 
- [X] `docker system prune` 
  - reclaimed 180GB of space
- [x] `docker system prune -a -f`
  - reclaimed an additional 41.66GB
- [X] `docker volume prune` 
  - reclaimed 263.2MB of space
- [x] automate the above via cron job
  - see #1169 
  - created cron job via ansible 
    - see 9d0da0b in keybase://team/mozmeao.cloud/gitlab

**Comment by pmac** [comment]
This was on `AWS Frankfurt Shell Runner 0 ZSy9chDU` that I saw this FYI.
