### ISSUE TITLE
Implement SSO For CloudFlare

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#1175]
Looks like we can[ get SSO enabled for our account](https://blog.cloudflare.com/introducing-single-sign-on-for-the-cloudflare-dashboard/) (I think we qualify as enterprise).

- [Mozilla Docs On Requesting SSO](https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=SECURITY&title=SSO+Request+Form#SSORequestForm-SSORequestForm)

Can you take a peek and let me know a timeframe.

**Comment by metadave** [comment]
sorry @bensternthal, just saw your note on getting a time frame together. We'll take a look this week.

**Comment by bensternthal** [comment]
Ping on this one!

**Comment by metadave** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1637702

**Comment by metadave** [comment]
Cloudflare is now enforcing SSO.
