### ISSUE TITLE
Implement SSO For DataDog

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#1176]
It looks like we should be able to enable SSO for the mozilla marketing team. 

Can you review if possible and let me know a reasonable timeframe.

- [Mozilla Docs On Requesting SSO](https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=SECURITY&title=SSO+Request+Form#SSORequestForm-SSORequestForm)
- [Data Dog Docs](https://docs.datadoghq.com/account_management/saml/)

**Comment by metadave** [comment]
sorry @bensternthal, just saw your note on getting a time frame together. We'll take a look this week.

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/issues/1238
