### ISSUE TITLE
investigate snippets prod fetch metrics DMS

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1188]

**Comment by glogiotatidis** [comment]
Will take care this week, thanks!

**Comment by glogiotatidis** [comment]
Will go ahead and make the data fetching to be every 30 minutes (now around every 10) so wrong around timeouts. 

A proper solution will come with https://github.com/mozmeao/snippets-service/issues/1275

**Comment by glogiotatidis** [comment]
https://github.com/mozmeao/snippets-service/pull/1276
