### ISSUE TITLE
Kubernetes logs to BigQuery

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#1190]
- Replace our current solution based on Athena implemented in https://github.com/mozmeao/infra/issues/225
  - option 1: set up ETL from existing papertrail-moz-works S3 bucket
  - option 2: switch everything to stackdriver & [configure a BigQuery sink](https://cloud.google.com/logging/docs/export/configure_export_v2#dest-create)
    - this reverses https://github.com/mozmeao/infra/issues/914
    - https://cloud.google.com/monitoring/quickstart-aws
  - option 3: option 1 followed by a GCP-only subset of option 2

**Comment by jgmize** [comment]
Athena to BigQuery converter: https://iodide.telemetry.mozilla.org/notebooks/397/?viewMode=report

**Comment by sunahsuh** [comment]
Just a note that a lot of the rules in that conversion are telemetry-specific, so please proceed with caution :)
