### ISSUE TITLE
Remove ELBs from Terraform, and ensure the k8s deployments are correctly create elbs.

### ISSUE THREAD

**Issue by duallain** [mozmeao/infra#1262]
Our elb deployments are currently partially defined in terraform in the infra repo, partially defined in k8s services.

- At the end of this story, all of our service deployments should have their elbs defined as k8s services.
- Should have the correct ACM cert. Should have reasonable TLS/encryption settings.
- ensure functionality, and zero downtime for this change
- many services have multiple listeners (80 and 443), ensure both work
- we should manually update dns to point at the new elbs
- ensure the old services are cleaned up (kubectl apply doesn't delete old objects)
- services to migrate include basket/bedrock/nucleus
- terraform defining elbs should be deleted

**Comment by metadave** [comment]
- Each ELB must have a health check (use existing health check definitions)
- standardize shared defaults (connection draining, cross az, etc)

> services to migrate include basket/bedrock/nucleus

`+` snippets

> we should manually update dns to point at the new elbs

I'd like to think about this, we could probably sync up TF DNS automation w/ K8s

**Comment by duallain** [comment]
https://jira.mozilla.com/browse/SE-1242 has elb work in scope.
