### ISSUE TITLE
Grafana dashboard for Basket

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1263]
@pmac What data do we want to see on the dashboard?

**Comment by pmac** [comment]
Similar things to what was on the DD dashboards I think:

* view call counts
  * possibly by HTTP response code
* task call counts by task
* SFDC and SFMC API call counts and limits
* task retries and max retries
* messages coming in on the SQS queues from FxA and MoFo

That kind of thing

**Comment by metadave** [comment]
@glogiotatidis is this something you could take a look at? 

cc @duallain @pmac

**Comment by glogiotatidis** [comment]
Yap, will take care!
