### ISSUE TITLE
Artemis: [Spike] Do a spike on EKS

### ISSUE THREAD

**Issue by duallain** [mozmeao/infra#1274]
Deploy eks, and test it.  Answer the following questions:

Can it support all our services?
How does networking work between the cluster and other aws services + outside stuff (github, for example)?
How do Security groups work?
What does eks make easy/hard about Iam Permissions?
What does access to the cluster look like from the POV of real humans, and from the POV of automation accounts.

(note, it-se's have some eks terraform code https://github.com/mozilla-it/it-sre-apps-cluster, that we might be able to reuse)

**Comment by glogiotatidis** [comment]
Looks like you didn't finish your last sentence @duallain

**Comment by metadave** [comment]
https://youtu.be/LJfowXTXOfU?t=65

**Comment by duallain** [comment]
- Can it support all our services?
  - It seems to.  It's 'just' k8s, so no big suprises.  Deployed voyager/external-dns and a few sample services and everything seemed to work great.
- How does networking work between the cluster and other aws services + outside stuff (github, for example)?
  - Seemed to be pretty straight forward ec2 instance stuff.  The managed nodes are just ec2 instances.  Nat Gateway was how I solved the problem for this demo, but I'm sure if we set the internet gateway up correctly we could skip the nat gateway.
- How do Security groups work?
  - You can just attach rules to the security group created.
- What does eks make easy/hard about Iam Permissions?
  - for cluster wide IAM stuff, it seems like we can just add extra roles/policies.  We can also add arbitrary permissions to particular node groups (untested, but accepts an iam role as input)
need to run that command at startup, maybe make separate files), but seems to be doable.
- What does access to the cluster look like from the POV of real humans, and from the POV of automation accounts.
  - You do need to be logged into aws as a real user to access the cluster.  But it happened pretty transparently, ran `aws eks --region us-west-2 update-kubeconfig --name oregon-eks` then switched to using that context, and while logged into aws, was able to run kubectl commands.  This will likely be a little weird for our gitlab-runners (will 
  - There is some 'extra' configuration around roles and permissions that are in the variables of the related PR, but it seems like it works for automation accounts as well.  We'll just need to keep networking, eks perms, and account roles all in sync for everything to work.
