### ISSUE TITLE
Consolidate mozorg and mozmeao dockerhub repos.

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#1284]
- [x] snippets
 ~~careers~~ - not pushing images anymore, it's static
 - [x] bedrock
 - [x] nucleus -  already done
 - [x] basket - already done

**Comment by glogiotatidis** [comment]
Snippets https://github.com/mozmeao/snippets-service/pull/1359

**Comment by glogiotatidis** [comment]
Removed very old repositories from mozorg dockerhub repo. 

Only bedrock repos remain under mozorg account. Filed PR https://github.com/mozilla/bedrock/pull/8936

**Comment by metadave** [comment]
this is great, thanks for the cleanup!

**Comment by glogiotatidis** [comment]
bedrock is complete.
