### ISSUE TITLE
Move Projects to new GitLab runners

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#1286]
- [x] Snippets
- [x] Snippets - config
- [x] Careers
- [x] Nucleus (only did master branch b/c stage / prod are behind)
- [x] Nucleus - config 
- [x] Bedrock - PR https://github.com/mozilla/bedrock/pull/8872
- [x] Bedrock - config - https://github.com/mozmeao/www-config/pull/264
- [x] Basket
- [x] Basket - config
- [x] IRL
- [ ] infra-services
- [x] Bedrock - workers (CloudFlare worker deployment)
- [x] Release notes (should go away soon)
- [x] Protocol (only did master branch b/c prod is behind)
- [x] awebpodcast
- [x] Bedrock - admin (home page content cards) (only did master to avoid publishing something unintentionally)
- [x] https://github.com/mozmeao/slack-notify
- [x] https://github.com/mozmeao/performance-dashboard/blob/master/.gitlab-ci.yml
- [x] https://github.com/mozmeao/combinedIngress/blob/master/.gitlab-ci.yml

Tags matching the new runners `mozmeao` and `aws`

**Comment by glogiotatidis** [comment]
@mozmeao/theconn projects I'm missing?

**Comment by pmac** [comment]
Bedrock - workers (CloudFlare worker deployment)

**Comment by glogiotatidis** [comment]
Moved all known projects. :relieved:

**Comment by glogiotatidis** [comment]
:tada:
