### ISSUE TITLE
Test IPVS kube-proxy

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#129]
https://github.com/kubernetes/kubernetes/pull/38817

**Comment by jgmize** [comment]
See also: https://github.com/kobolog/gorb/issues/32

**Comment by jgmize** [comment]
compare and contrast to service-level approach in https://github.com/kubernetes/contrib/tree/master/keepalived-vip

**Comment by quinton-hoole** [comment]
We have a tested implementation of IPVS kubeproxy in https://github.com/kubernetes/kubernetes/issues/44063
Busy tying the various related issues and PR's together now.

**Comment by jgmize** [comment]
kube-router is an interesting alternative:  
- https://www.kube-router.io
- https://github.com/cloudnativelabs/kube-router
- https://cloudnativelabs.github.io/post/2017-11-01-kube-high-available-ingress/

**Comment by jgmize** [comment]
https://blog.quentin-machu.fr/2018/12/15/kube-proxy-ipvs-simple-efficient-unstable/
