### ISSUE TITLE
setup bedrock error page https://www.mozilla.org/en-US/firefox/all/#product-desktop-release

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1290]

**Comment by pmac** [comment]
We've setup an error page domain on Netlify for use as a hot-spare static page in case of catastrophic downtime for the bedrock clusters.

https://mozmeao-www-error-page.netlify.app/

This will respond with the error page regardless of the URL path. It is deployed on push to https://github.com/mozmeao/www-cloudflare-error-pages master branch.

Remaining to do are:

* Ensure it works when proxied through CloudFlare
* Set up a traffic policy to use this site in case of prolonged emergency
