### ISSUE TITLE
s3 bucket cleanup

### ISSUE THREAD

**Issue by duallain** [mozmeao/infra#1293]
delete buckets we don't need

**Comment by glogiotatidis** [comment]
Created a list of all buckets and sizes https://docs.google.com/spreadsheets/d/15ecJ7qUqtqRdGp4N1qngFCwI-5UI0t_27hLGLS3wkCI/edit?usp=sharing

List features two dropdown columns per entry, one to set `Delete` to `Yes` or `No` and another one to set `Lifecycle Policy` if were keeping it (to fix #1294)

@mozmeao/meaocloud can you please the columns above for all buckets?

**Comment by glogiotatidis** [comment]
OK There's something strange going on:

`snippets-prod-us-west` lists 1200 objects and total size 4.9 MiB when queried via the Web Console or `aws` cli.  But CloudWatch reports almost 1TiB and 4.2M objects. 

Any ideas what's going on @duallain @metadave ?

**Comment by duallain** [comment]
@glogiotatidis I think it may be related to 'expired' or 'previous' versions of the objects.  The lifecycle rules we have in place seem to just move some objects from current to expired, but nothing goes from expired to deleted.  I did a quick look at some random folders in that bucket and there are quite a few objects marked as expired. But, it's a bit of a mystery for me as well.

**Comment by glogiotatidis** [comment]
This explains it. We need to both `expire` and `delete expired`. ok AWS.

thanks @duallain !

I guess we need to work on #1294 all these details.

**Comment by glogiotatidis** [comment]
I completed settings lifecycle policies and deleting some unneeded buckets. I believe this is good enough for now
