### ISSUE TITLE
Add ability for CRO team to easily add images to www.m.o for experiments

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#1304]
The CRO team would like to be able to upload images for experiments outside of a full bedrock prod push, but would like to use our CDN to ensure the images are as fast and reliable as our other site media. In my view we have 2 main options:

1. Give them the ability to upload to our existing bedrock-prod-media bucket
2. Give them a new bucket that would also be proxied through the CDN in the same way `/media` is now

I think 1 is the most quick and easy way to go, and we could setup a repo with automation to upload images added to it to a specific folder within the prod media bucket. This would be very similar to the automation for the https://github.com/mozmeao/www-admin repo that uploads content card images to the bucket.

**Comment by pmac** [comment]
I've created a repo for this https://github.com/mozmeao/www-experiment-media

Alan and I decided on Slack to use the existing prod bucket and automate uploads via the above repo.

**Comment by pmac** [comment]
This is done. I setup the new repo with automation in GitLab and tested it. 

https://www.mozilla.org/media/cro_exp/img/mozilla-hack.jpg

Huge success \o/

**Comment by metadave** [comment]
btw, this is awesome @pmac, thank you!
