### ISSUE TITLE
Setup K8s LoadBalancer/AWS ALB for www.firefox.com

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#1308]
- [x] automate ALB's
- [x] setup ACM certs for each ALB
- [x] configure DNS automatically for `fxc-prod.moz.works` or `fxc-stage.oregon-b.moz.works` (following existing pattern in route53)

**Comment by pmac** [comment]
This is mostly done for the staging instance. Just prod to go as well as DNS for domains.

**Comment by metadave** [comment]
we should be fine pushing everything to prod before the DNS switch, right?

**Comment by pmac** [comment]
definitely. just haven't done it. I can push the prod branch and the k8s resources should be created.

**Comment by pmac** [comment]
Okay. Done. Seems to have worked. https://gitlab.com/mozmeao/www.firefox.com/-/jobs/560855599

**Comment by metadave** [comment]
what else do we need before we request the DNS cutover?

**Comment by pmac** [comment]
We should get some real internal domains for these. e.g. `fxc-prod.moz.works` or `fxc-stage.oregon-b.moz.works`. After that we're going to hook the prod one up to CloudFlare I think (issue #1309). Then we'll be ready for DNS. I'd like to do some load testing before we cut over as well though.

**Comment by duallain** [comment]
I'm going to aim for this pattern for the alb domain name:

<svc>-<env>.<cluster>moz.works.  fxc-stage.oregon-b.moz.works/ fxc-prod.oregon-b.moz.works.

Then, point cloudflare at a fxc-prod.moz.works, which will temporarily just be a cname to fxc-prod.oregon-b.moz.works, but when we add a second region would point to a traffic policy, that can do healthchecks and geo-ip stuff like bedrock.  

@pmac anything wrong with the above?  I think this matches bedrock's pattern today.

**Comment by pmac** [comment]
looks good to me 👍

**Comment by duallain** [comment]
Should be all done! 🎉
