### ISSUE TITLE
Gitlab Security Group

### ISSUE THREAD

**Issue by duallain** [mozmeao/infra#1312]
We should make a security group and attach it to gitlab runners.

**Comment by glogiotatidis** [comment]
https://github.com/mozmeao/infra-services/pull/51/files

**Comment by glogiotatidis** [comment]
Still need to apply this one, re-opening

**Comment by glogiotatidis** [comment]
Fixed here https://github.com/mozmeao/infra-services/pull/54

**Comment by glogiotatidis** [comment]
Applied
