### ISSUE TITLE
Add disk space cleanup cronjob to gitlab runners

### ISSUE THREAD

**Issue by duallain** [mozmeao/infra#1313]
Docker objects filled our disk, let's add a cronjob that does cleanup.
```
docker system prune --volumes --force
```

Should work.  Maybe run it hourly with a filter (since it's incremental, and running more frequently should make it run faster, with smaller resource spikes) of 24hr? `--filter "until=24h"`.

**Comment by glogiotatidis** [comment]
There's already a cron job, but we probably need to run it more often (with the filter command too, nice tip) and also increase the disk space. https://github.com/mozmeao/infra-services/blob/master/gitlab-runners/packer/ansible/playbook.yml#L98

**Comment by glogiotatidis** [comment]
FTR 
```
root@ip-172-31-31-72:/home/admin# docker system prune --volumes --force --filter 'until=12h'
ERROR: The "until" filter is not supported with "--volumes"
```

**Comment by glogiotatidis** [comment]
https://github.com/mozmeao/infra-services/pull/51

**Comment by glogiotatidis** [comment]
Updated here https://github.com/mozmeao/infra-services/pull/54 and applied
