### ISSUE TITLE
AWS CDN Cost Comparison

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#1346]
Pull out cost data from email chain, socialize with enough folks that we have confidence in costs.

- Cost comparison [spreadsheet](https://docs.google.com/spreadsheets/d/1gz1Ppi5YqLm6H9a0vXNAtFkX-QTusDs4GQBzKWiVF_o/edit?usp=sharing).

**Comment by duallain** [comment]
Looks like we missed a flat fee for legacy ssl support, which is $600 a month (with no discounts).  We had decided to do that on prod only, last I knew. We should be able to deploy a single cert.

If I recall we did the pricing check assuming the current traffic in AWS.  So, fairly confident we won't consume unaccounted for capacity. I'll get a second pair of eyes anyway though, as I don't have a ton of experience pricing cloudfront specifically.

**Comment by bensternthal** [comment]
I think this is as good as we can get at this time. Thanks for the help 💸
