### ISSUE TITLE
Develop "Feature" Test Cases

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#1348]
I think this task involves coming up with list of unique features that need to be tested. I pulled the below from [older docs](https://docs.google.com/document/d/1hgc-SmFyL2lPZ6dK-Le_cg6svaFBgGXtuB3WQwch7-U/edit#heading=h.85mmv6okgoh) as a starting point, note I am unsure if these are all still valid so edit at will:

1. Localization: Vary Accept Language Header
2. Multi Origin: Paths under /static
3. IE 8 on Windows XP (Legacy SSL Support)
4. Performance: Likely a non issue. 
5. Workers (if in scope)?
6. Geolocation
7. Page Rules?
8. Anything else?

**Comment by pmac** [comment]
That looks like a good list to me. We can updated it as we find things.
