### ISSUE TITLE
Migrate usage of travis-ci to GitHub Actions or CircleCI

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#1355]
Travis-CI has both changed policy to limit free access for OSS and experienced a massive security breach that potentially exposed encrypted secrets. We should move to GitHub Actions (preferred) or Circle CI. 

- [X] [django-product-details](https://github.com/mozilla/django-product-details) -> https://github.com/mozilla/django-product-details/issues/81
- [x] mozmeao/status (Archived)
- [x] mozmeao/cloudflare-datadog (Archived)
- [x] mozmeao/django-allow-cidr -> https://github.com/mozmeao/django-allow-cidr/pull/17
- [x] mozmeao/performance-dashboard (Archived)
- [x] mozmeao/lumbergh (Retired)

**Comment by glogiotatidis** [comment]
Snippets moved to Github Actions in https://github.com/mozmeao/snippets-service/issues/1489

There're reports that Travis has limited (some say blocked) resources to support OSS projects these days. So probably GitHub actions is a better place to get to. migration was super easy

**Comment by glogiotatidis** [comment]
Same for careers https://github.com/mozmeao/lumbergh/pull/653

**Comment by stevejalim** [comment]
@pmac I've updated the description wiht a list of repos in meao that feature the word "Travis" - are all these still 'on the table' for switching, or can some repos just be archived, please?

**Comment by pmac** [comment]
I see `cloudflare-datadog` and `status` are already archived. I'm talking with Alex about performance-dashboard. We still have `django-allow-cidr` as a dep in some projects though.

**Comment by pmac** [comment]
Updated. I think `django-allow-cidr` is the only one we still need to do.

**Comment by stevejalim** [comment]
Doing `django-allow-cidr` now

**Comment by stevejalim** [comment]
`django-allow-cidr` PR https://github.com/mozmeao/django-allow-cidr/pull/17
