### ISSUE TITLE
Upgrade gitlab runners capacity

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#1359]
We're moving bedrock's integration tests to our runners, so increased CPU would benefit test run times.

We're currently on `m5.large`. I suggest that we move to `c5a.xlarge` with the same memory, double vCPUs, `a` stands for AMD.

Cost comparison
| Instance Type | Frankfurt | Oregon | 
| --- | :-- | --: | 
| m5.large | $0.115 p hour ($82.8 p month) | $0.096 ($69.12) | 
| c5a.xlarge | $0.174 ($125.28) | $0.154 ($110.88) |

Thoughts @pmclanahan @duallain @bensternthal ?

Related issue https://github.com/mozilla/bedrock/issues/9453

**Comment by bensternthal** [comment]
👍 💰

**Comment by duallain** [comment]
Seems good.

One thing to note, I don't think we fully finished the work of having the gitlab runner deployment update a security group when they get new IP addresses. If you wanted to take a swipe at that, that'd be great. Either way, it's worth double/triple checking that the runners can talk to all the k8s clusters after deployment.  I usually just rerun infra-services or dev deployment jobs to double check.

**Comment by glogiotatidis** [comment]
We paired with @pmac and deployed new runners with fresh packer images in both regions. Also produced https://github.com/mozmeao/infra-services/pull/92
