### ISSUE TITLE
Collect complete list of pages to be migrated

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#1364]
## List of pages to migrate
   - *Save to Pocket* - https://getpocket.com/save-to-pocket
   - *Pocket for Firefox* - https://getpocket.com/pocket-and-firefox
   - *About* - Hopefully going live next week (current page is old), and
   will be here:  https://getpocket.com/about
   - *Pocket Hits Signup* - https://getpocket.com/explore/pocket-hits-signup
   - *Pocket Hits Signup Confirmation Page* -
   https://getpocket.com/pocket-hits/confirmation
   - *Privacy* - https://getpocket.com/privacy
   - *TOS* - https://getpocket.com/tos
   - *Contact Info* - https://getpocket.com/contact-info
   - *Jobs* - https://getpocket.com/jobs
   - *New Tab Learn More* - https://getpocket.com/firefox/new_tab_learn_more
   - *Premium* - https://getpocket.com/premium

And also
   - https://getpocket.com/welcome
   - https://getpocket.com/firefox
   - https://getpocket.com/chrome
   - https://getpocket.com/safari
   - https://getpocket.com/android/
   - https://getpocket.com/ios/
   - https://getpocket.com/ipad/
   - https://getpocket.com/iphone/
   - https://getpocket.com/fire/
   - https://getpocket.com/edge
   - https://getpocket.com/opera
   - https://getpocket.com/add
   - https://getpocket.com/slack

## Notes:
 - *Premium* page has a bit of backend logic and maybe it does not get migrated with the first wave
 - The second group of pages listed above (from `welcome` to `slack`) were planned to get replaced by a single page for which a Creative Brief and Figma design exists.

**Comment by hoosteeno** [comment]
The list of prioritized pages in the spreadsheet linked above includes a dozen or so flagged with "Marketing" and assigned to Fabio. I expect that's a good start (and maybe the best list we can get). 

https://docs.google.com/spreadsheets/d/1_qE60UVSwppix85-v9J0WGG7aKhBXF0YeMVhpz31zEg/edit#gid=1228419328

We are blocked on this awaiting confirmation.

**Comment by hoosteeno** [comment]
@glogiotatidis can you link to the more recent list of pages here?

**Comment by glogiotatidis** [comment]
Updated the issue
