### ISSUE TITLE
Research Pocket pages Localization

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#1366]
- Understand current localization process of Pocket marketing pages
 - Decide on whether we will need to update those pages and thus their translations before we move them to Contentful
 - Plan how we're going to do localization if we move to Contentful

Also:

 - How does locale identification work atm? 
 - How do redirects work atm? E.g. `/firefox` redirects to `/pocket-and-firefox`. Which side will be responsible for those redirects?

**Comment by glogiotatidis** [comment]
Netlify supports redirects based on Country or Locale. https://docs.netlify.com/routing/redirects/redirect-options/#redirect-by-country-or-language

**Comment by hoosteeno** [comment]
We are blocked on this waiting for Pocket to get back to us on how l10n happens.

**Comment by glogiotatidis** [comment]
Quoting Mark's very detailed reply:

>  Locale identification works by using Express' req.acceptsLanguages() Method to read the request's Accept-Language header and compare this list against a list of supported languages. The default language is English (en) if there are no matches between supported and accepted languages. Here is where you can find the files that are controlling this:
>  
> [Detecting languages middleware](https://github.com/Pocket/web-discover/blob/b9241bbb34eef3dea0a01f97ee0d723a32d85631/server/middleware/localization.js#L24-L41)
> [Handling the language matching and redirect middleware](https://github.com/Pocket/web-discover/blob/b9241bbb34eef3dea0a01f97ee0d723a32d85631/server/middleware/localization.js#L43-L90)
> [Setting the language after redirect middleware](https://github.com/Pocket/web-discover/blob/b9241bbb34eef3dea0a01f97ee0d723a32d85631/server/middleware/localization.js#L92-L111)
> [List of routes that are localized](https://github.com/Pocket/web-discover/blob/b9241bbb34eef3dea0a01f97ee0d723a32d85631/server/index.js#L106-L122)
> [Supported languages list](https://github.com/Pocket/web-discover/blob/b9241bbb34eef3dea0a01f97ee0d723a32d85631/server/index.js#L89)

> 
> One thing to note here is that the Pocket Hits Signup page was built before the web-discover repo had proper localization setup. So, it uses a custom Middleware that appends a custom header to assist the page in determining the correct language to display. There are only two languages supported for this page (en and de-DE). You can find relevant files to this here:
> 
> [Appending "x-pocket-lang" custom header middleware](https://github.com/Pocket/web-discover/blob/b9241bbb34eef3dea0a01f97ee0d723a32d85631/server/middleware/localization.js#L1-L22)
> [Single route using this method](https://github.com/Pocket/web-discover/blob/b9241bbb34eef3dea0a01f97ee0d723a32d85631/server/index.js#L101-L104)
> [Where the this header is read](https://github.com/Pocket/web-discover/blob/b9241bbb34eef3dea0a01f97ee0d723a32d85631/src/pages/pocket-hits-signup.js#L4)
> [Supported languages list](https://github.com/Pocket/web-discover/blob/b9241bbb34eef3dea0a01f97ee0d723a32d85631/server/index.js#L81)

**Comment by hoosteeno** [comment]
@glogiotatidis what's next here?

**Comment by glogiotatidis** [comment]
* Pages will be moved  to MozMarketing control as they are (visual and content) right now. 
* Same locale identification technique will be used (i.e. Accept-Language) to redirect users to the right content
* Localization will be directory based, e.g. /en/about serves english content
* Contentful has built-in support for localization which 11ty will use to build pages with localized content in the respective directories
* Redirects like /firefox -> /pockets-and-firefox/ are handled on Netlify.
