### ISSUE TITLE
k8s 1.6

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#145]
- [ ] Verify kops works for our purposes with k8s 1.6
  - [ ] Update automation to install latest
  - [ ] deploy ephemeral test cluster
- [ ] decide migration upgrade vs in-place
    - Migration upgrade steps
      - build new cluster
      - deploy apps to new cluster
      - update route53 traffic policy to point to new cluster
      - decom old cluster
    - In-place 
      - [ ] document in-place upgrade steps
- [ ] Upgrade existing clusters
  - [ ] ~Virginia~
  - [ ] Tokyo

**Comment by metadave** [comment]
Our K8s Portland cluster is at v1.7, which seems very stable. @jgmize should this be closed in favor of a newer issue(s)?
