### ISSUE TITLE
Services of type LoadBalancer include master nodes in ELB instances

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#153]
Related issues:
- https://github.com/kubernetes/kubernetes/issues/33884
- https://github.com/kubernetes/kops/issues/853
- https://github.com/kubernetes/kops/issues/639

**Comment by jgmize** [comment]
As a near term workaround, until this is resolved upstream, we'll need to manage ELBs directly.

**Comment by metadave** [comment]
More info on ELB provisioning [here](https://github.com/mozmar/infra/issues/159)

**Comment by metadave** [comment]
Should this move to the backlog for now?

**Comment by jgmize** [comment]
Now that we have the temporary workaround in place this isn't blocking https://github.com/mozmar/infra/milestone/5 but I'd still like to do some work on the upstream issues in Q2 to try to get a resolution in the next release of kops and/or k8s.

**Comment by jgmize** [comment]
See also:
- https://github.com/coreos/alb-ingress-controller/issues/92
- https://github.com/coreos/alb-ingress-controller/pull/94

**Comment by jgmize** [comment]
per https://github.com/kubernetes/kubernetes/issues/33884#issuecomment-296011376 this should be resolved in 1.6 by https://github.com/kubernetes/kubernetes/pull/44745

**Comment by jgmize** [comment]
Does not appear to be fully resolved, follow up issue: https://github.com/kubernetes/kubernetes/issues/45772

**Comment by metadave** [comment]
I'm not seeing masters included in an ELB created via a K8s `LoadBalancer` in our 1.7 Portland cluster.

https://github.com/kubernetes/kubernetes/pull/44745#issuecomment-312668869
