### ISSUE TITLE
💲Analysis and RI Recommendation

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#177]
ping @jgmize @bensternthal let's sync up on this.

**Comment by bensternthal** [comment]
Note, I will drop a link to what we did in 2016 here.

**Comment by bensternthal** [comment]
# Current Reserve Instances

```
us-west-2a	1		t2.micro
us-west-2a	2		m4.xlarge
us-west-2b	2		m4.xlarge
us-west-2c	2		m4.xlarge
eu-west-1a	1		t2.micro
eu-west-1a	2		m4.xlarge
eu-west-1b	2		m4.xlarge
eu-west-1c	2		m4.xlarge
```

**Comment by bensternthal** [comment]
Form -> 

https://docs.google.com/a/mozilla.com/spreadsheets/d/10f0u-AYJkQo0Ft2IctTgjdkXMvnd6-v0JoNk9Ei10BQ/edit?usp=sharing

**Comment by bensternthal** [comment]
Just waiting on final finance approval (PO), once that clears will purchase.. ideally today.

**Comment by bensternthal** [comment]
EC2 & RDS instances are purchased.
