### ISSUE TITLE
Automate deis user management

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#188]
create users and grant permissions based on github group memberships and published ssh keys

**Comment by metadave** [comment]
we should probably close https://github.com/mozmar/infra/issues/94

**Comment by jgmize** [comment]
Alternatively we can centralize all interactions with deis via jenkins and eliminate use of local deis clients entirely.

**Comment by metadave** [comment]
Closing as we'll be moving away from Deis in the near future.
