### ISSUE TITLE
Elasticsearch evaluation for MDN

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#193]
- Hosted vs self-hosted
  - Hosted
    - https://aws.amazon.com/elasticsearch-service/
      - default choice 
        - centralized billing has already been set up
        - low effort to set up through console
        - terraform support: https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html 
      - likely not the best price, performance, reliability, etc
    - https://www.elastic.co/cloud/as-a-service
    - https://qbox.io/hosted-elasticsearch
  - Self-hosted
    - needed for ephemeral dev deploys regardless of production usage
    - likely most affordable solution in terms of monthly bill, but clearly most expensive in terms of engineering time
    - https://supergiant.io/blog/supergiant-packing-algorithm-unique-save-money demonstrates an alternative cluster autoscaler that may be a useful improvement over our current implementation

**Comment by jgmize** [comment]
https://github.com/samsung-cnct/k2-charts/tree/master/elasticsearch looks like a better option than https://github.com/kubernetes/charts/tree/master/incubator/elasticsearch right now.

**Comment by metadave** [comment]
@jgmize in the interest of keeping things simple, I'm leaning towards AWS-hosted Elasticsearch for the initial migration, with a possible post-migration task to self-host if needed.

**Comment by jgmize** [comment]
https://read.acloud.guru/things-you-should-know-before-using-awss-elasticsearch-service-7cd70c9afb4f

**Comment by metadave** [comment]
One thing I think we should consider is that if we use hosted ES, we have support available to us.
If we self-host, we're on our own. Given the size of the team and the amount of tech we juggle, it may be nice to have support to lean on.

**Comment by jgmize** [comment]
Agreed, I'm not excited about self-hosting ES in prod; I'm more interested in evaluating the other hosted options.

**Comment by emmanuel** [comment]
FWIW, we (Nordstrom Kubernetes team) have been using the AWS ES service for >1y, and are currently (very happily) migrating away from it. We've experienced a number of challenges and disappointments:
1. AWS ES doesn't support the entire Elasticsearch API, so some tools in the ecosystem simply don't work (like curator)
2. All interactions with the ES API require AWS request signing, which further complicates usage of existing open source/community tooling
3. Adding cluster capacity (increasing cluster instance count) reliably put our cluster in 'Red' status (ominous!), from which we have only been able to recover by involving AWS support. This has happened to us repeatedly, and we have been told more than once by AWS support that these are known issues and a support ticket is expected in this scenario. I find this completely unacceptable.

Given these experiences, I would personally avoid AWS ES in its current incarnation and seek a different option. 

Please pardon the unsolicited input/advice!

**Comment by metadave** [comment]
@emmanuel your advice is excellent and much appreciated! I think at this point we're leaning away from AWS.

**Comment by jgmize** [comment]
https://github.com/upmc-enterprises/elasticsearch-operator may make self-hosted ES more viable.

**Comment by metadave** [comment]
specs for our current ES clusters [here](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=5112369)

**Comment by metadave** [comment]
Let's try either the (2 GB memory/48 GB disk) or (4 GB memory/96 GB disk) single region clusters from https://www.elastic.co/cloud/as-a-service/pricing. Given the Kuma use case with ES, do we need to purchase [additional support](https://www.elastic.co/cloud/as-a-service/support), or will the [Standard Elastic Support](https://www.elastic.co/cloud/as-a-service/support) work for us?

**Comment by jgmize** [comment]
Given that we're only talking about Kuma right now, starting with a relatively small 2GB or 4GB single region cluster with standard support is probably fine. I think when we add SUMO and/or centralized logging we can evaluate the number, size, and support level of the ES clusters based on the learnings from this initial deployment.

**Comment by metadave** [comment]
closing this as we're continuing on our eval [here](https://github.com/mozmeao/infra/issues/383). Feel free to reopen this card if needed.
