### ISSUE TITLE
Migrate legacy samples and files from SCL3 to AWS

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#197]
See also: https://github.com/mozmar/infra/issues/183

~This is a migration task we can take on well before The Big Migration. Current legacy samples and files are stored on an SCL3 filesystem. We can submit a webops request to change the `Alias` definitions to redirects in S3.~

From the httpd config, I believe these are the relevant aliases:

```
Alias /samples /data/www/samples
Alias /diagrams /data/www/diagrams
Alias /presentations /data/www/presentations
```

@jwhitlock do you know if `/diagrams` and `/presentations` are considered "legacy"?

**Comment by metadave** [comment]
any preference for using a subdir of the existing `mdn-downloads` bucket, or creating a new bucket?

**Comment by jwhitlock** [comment]
I'd rather use a different bucket, because of update, management, and usage patterns, but it's not a strong preference.  Details in [Simple Storage Service](https://docs.google.com/document/d/1-s343yxBMiugPQm5w2ho7EcSAcaLU4uOF6p2MLgbS1I/edit#heading=h.9ghimvtx1wlb) in the AWS migration doc.

**Comment by metadave** [comment]
new buckets created via https://github.com/mozmar/infra/pull/190, although there might be some iteration on them before we go live.

**Comment by metadave** [comment]
regarding `mdn-legacy-samples`, I can't find any good info on setting CSP for an S3 bucket: 
http://stackoverflow.com/questions/19825294/is-it-possible-to-set-content-security-policy-headers-in-amazon-s3

**Comment by metadave** [comment]
@jgmize since I [don't have access to SCL3 yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1357989), would you be able to tar up the following and drop them into a bucket somewhere?

- /data/www/samples
- /data/www/diagrams
- /data/www/presentations

**Comment by metadave** [comment]
@jwhitlock regarding this from the doc you linked above:

    mdn-legacy-samples: Legacy samples with HTML, CSS, and JS can be served from S3, with CSP headers to make them safer

we can't do CSP w/ S3 buckets, any thoughts here?

**Comment by metadave** [comment]
Regarding hosting legacy files in S3 vs EFS, I see 3 scenarios that we should consider:

#### current prod, pre-AWS migration

We could move legacy files from SCL3 to AWS before the main MDN migration. It would be one less detail to account for when the main migration occurs.

- SCL3 Apache redirects to our hosted legacy files
  - if hosted in S3, serve directly from S3
    - we can't do CSP w/ S3 buckets
  - if hosted in EFS, we'll need something to serve the files
	 - prefer not to modify Kuma to do this

#### K8s developer demo instances

- if hosted in S3, serve directly from S3
- if hosted in EFS:
	- Kuma could be modified at some point to serve files directly from EFS
	- if there's a solution from the section above ("current prod"), we could also apply that here.

#### MDN running in AWS

- if hosted in S3, serve directly from S3
- if hosted in EFS
	- see comments for each section above

**Comment by metadave** [comment]
I copied `/data/www/diagrams`, `/data/www/presentations`, and `/data/www/samples` from SCL3 to the virginia EFS share. All files use ~2.4G uncompressed. 

They're currently in the `mdn-dev` dir in EFS:

```
root@ip-172-20-57-187:/mdn/mdn-dev/www# ls -la
total 24
drwxr-xr-x  6 root root 4096 Apr 28 18:36 .
drwxr-xr-x  3 root root 4096 Apr 28 15:52 ..
drwxr-xr-x  3 root root 4096 Apr 28 18:42 diagrams
drwxr-xr-x 13 root root 4096 Apr 28 18:36 presentations
drwxr-xr-x 26 root root 4096 Apr 28 18:37 samples
drwxr-xr-x  2 root root 4096 Apr 28 18:28 uploads
```

---

I'm not sure if we can share these between dev/stage/prod environments, as we would have to symlink out of the pvc mount point to a shared directory.

For example:

EFS has:
```
/mdn-dev
/mdn-stage
/mdn-prod
/shared
```
The PVC for an environment will point to one of the 3 `mdn-` directories above (eg `/mdn-dev` is mounted at `/data` in a pod). If we symlinked to an EFS `/shared` dir, the symlink would point outside of the pvc mount point. Do we care about copying 2.4 Gb of files to each environment?

**Comment by jwhitlock** [comment]
Legacy samples are currently served from developer.mozilla.org via Apache.  We could potentially serve them through Django and add CSP headers that way.  Or, Django could handle the URLs by redirecting to S3 public names for the files, and we could not care about CSP.  I was hoping we could get rid of these legacy samples entirely, but it is hard to get the right people together for that effort.

I consider diagrams, presentations, and samples to be write-only, and could potentially be shared between environments.

``uploads`` is new to me - is that for user-uploaded attachments?  Those will change between now and AWS day, and will need to be re-synced.  Distinct folders are needed for each environment.

**Comment by metadave** [comment]
> I consider diagrams, presentations, and samples to be write-only, and could potentially be shared between environments.

@jwhitlock do you mean read-only here?

---

`uploads` is empty for now, and I believe the intent is for user-uploaded attachments. 

I'm unsure how user-uploaded attachments are stored at the moment, I see this line from the apache config:

```
 <Directory /data/www/developer.mozilla.org/kuma/media/uploads>
  ... 
```

Is Kuma writing to this directory, and if so, is there a config variable that sets the path at runtime?

**Comment by jwhitlock** [comment]
Yes, I meant read-only.  Fridays.

I'm still digging, but I think this is the uploads folder used on kitsune, since it was added in 2010 (https://github.com/mozilla/kuma/commits/8d9a069f8c).  It looks like it was reused for the Demo Studio, which was decommissioned in January 2016 (https://github.com/mozilla/kuma/pull/3698). I think it is safe to drop settings that mention it (my task), and safe to not serve this folder going forward.  There are some Apache redirects for popular demos and the uploads folder, but I think those are covered by #180.

**Comment by metadave** [comment]
In the interest of keeping the migration "clean", we'll keep everything is EFS instead of a split between EFS and S3. We'll be serving legacy samples from EFS. The kuma env var `MEDIA_ROOT` can be configured to point at our EFS.

**Comment by metadave** [comment]
@escattone @jwhitlock I'm thinking of something that can run in or alongside Kuma in SCL3 that will upload any static assets to an S3 bucket, so we can easily sync them to the new stage/prod environments before we go live. 

If I setup credentials with access to a private S3 bucket, I wonder how much effort it would be to use boto3 to periodically push to this bucket. Any thoughts?

**Comment by metadave** [comment]
Contacted webops for permission, we're good to go.

crontask implemented on developer1.webapp.scl3, synchronizing files once an hour. Only new files will be transferred.

https://gist.github.com/metadave/e3e53720fe2fa133a91eb66483eff4ad

**Comment by metadave** [comment]
@escattone can you check and see if everything we need is here?

**Comment by escattone** [comment]
@metadave In addition to the three directories you've already identified above:
```
/data/www/diagrams -> /mnt/netapp/developer.mozilla.org/public/diagrams
/data/www/presentations -> /mnt/netapp/developer.mozilla.org/public/presentations
/data/www/samples -> /mnt/netapp/developer.mozilla.org/public/samples
```
we have to add the following directory:
```
/data/www/developer.mozilla.org/kuma/media/attachments -> /mnt/netapp/developer.mozilla.org/attachments
```
under which all of the user-uploaded attachments are stored. That directory currently holds 6 years of attachments, but a `du -sh /data/www/developer.mozilla.org/kuma/media/attachments/` shows that's only 1.3GB of data. Not too bad.

**Comment by escattone** [comment]
I also just realized that I need to submit a PR to kuma that allows the MEDIA_ROOT setting to be set from the environment. [Currently it is hard-wired to the `media` folder under the root directory.](https://github.com/mozilla/kuma/blob/68e5fddfaaa3ef2488af60599ed3ea44afb13c60/kuma/settings/common.py#L356), and that directory would be ephemeral since it's part of the container. This will allow us to point the MEDIA_ROOT to a location on the shared PVC (EFS).

**Comment by escattone** [comment]
I just submitted https://github.com/mozilla/kuma/pull/4359 to address the MEDIA_ROOT issue.

**Comment by escattone** [comment]
@jwhitlock I assume the following:
```
/data/www/diagrams -> /mnt/netapp/developer.mozilla.org/public/diagrams
/data/www/presentations -> /mnt/netapp/developer.mozilla.org/public/presentations
/data/www/samples -> /mnt/netapp/developer.mozilla.org/public/samples
```
are served in SCL3 via apache, but I don't know how they will be served when we move to AWS?

**Comment by jwhitlock** [comment]
My plan was to 302 redirect them to a public S3 bucket. If that's not feasible, we may need nginx or some additional Django views to serve the files, until we can fully transition to S3 and new domains.

**Comment by metadave** [comment]
@escattone attachments are now being synced once an hour from SCL3 -> S3:

Locations in S3:

- s3://mdn-shared-backup/backups/efs/attachments/
- s3://mdn-shared-backup/backups/efs/diagrams
- s3://mdn-shared-backup/backups/efs/presentations/
- s3://mdn-shared-backup/backups/efs/samples/

**Comment by metadave** [comment]
Regarding S3 hosting of these files, see [this](https://github.com/mozmeao/infra/issues/391) issue for tech issues to consider. I was going to mention using Whitenoise for these, but that's probably [not going to be the right solution](https://github.com/mozmeao/infra/issues/241).

I'll need more info on how attachments work. If they're written to EFS from a Kuma pod, we'll either need an additional crontask to push them to S3, or have Python code directly upload to S3.

**Comment by escattone** [comment]
@metadave Regarding attachments, I can simply point Kuma's `MEDIA_ROOT` setting at `/mdn/www/attachments` (which maps to the `/www/attachments` directory on our EFS mount), and we're good to go I think. I don't think we need to keep the S3 bucket for attachments once MDN is totally in AWS.

**Comment by escattone** [comment]
@metadave @jwhitlock 

Which of these two options (or some other) would you guys prefer for serving the diagrams, presentations, and samples?

1. Add redirects in Django from `/(samples|diagrams|presentations)` to the corresponding S3 bucket for each, and add [@metadave's lambda function](https://github.com/mozmeao/infra/issues/391#issuecomment-320723988) to each of the buckets. If we go down this path, we don't need these three directories on our dev/staging/prod EFS instances.
2. Serve `/(samples|diagrams|presentations)` from Django either via custom views (that add the appropriate headers) or WhiteNoise (I think diagrams and presentations will never change - since they're just legacy files - so they're OK for WhiteNoise, but I don't know about samples).

**Comment by escattone** [comment]
I think for simplicity's sake, I'd prefer serving from Django using WhiteNoise, assuming the samples are also legacy files that won't change.

**Comment by metadave** [comment]
I'd prefer hosting via Django and whatever else can help us there, S3 + Cloudfront/Lambda are slightly inflexible, and the Lambda function for headers is awkward.

**Comment by escattone** [comment]
If we use WhiteNoise and we want to use its hashing functionality, we'd most likely have to do that as a post-container-creation step where we run `make build-static` again since only then do we have access (via the PVC mount) to the files on the EFS instance? But I was looking at Google Analytics for MDN, and it seems that these legacy files (diagrams, presentations, and samples) are so rarely hit, that maybe it's not worth even worrying about caching and compression?

**Comment by metadave** [comment]
@escattone lets see if we can get by for now without extra work for caching and compression.

**Comment by escattone** [comment]
I had to create a temporary `busybox` deployment with the shared PV/PVC/EFS volume mounted:
```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mdn-admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mdn-admin
    spec:
      volumes:
        - name: kuma-fs
          persistentVolumeClaim:
            claimName: {{ SHARED_PVC_NAME }}
      containers:
        - name: mdn-admin
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sleep", "1800"]
          volumeMounts:
            - name: kuma-fs
              mountPath: {{ KUMA_MOUNT_PATH }}
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
```
and then `exec` into that (`kubectl exec -i -t -n mdn-dev <pod-name> -- sh`) to change the owner of the `/mdn/www/attachments` path to `1000` (`kuma`) in order to get the saving of attachments to work.

**Comment by metadave** [comment]
I was able to use the admin container to chown an EFS directory: https://github.com/mozmeao/infra/pull/418#issuecomment-322471942

I started it with a new name (`man-admin-debian`).

**Comment by jgmize** [comment]
see also: https://github.com/mozmeao/infra/pull/418#issuecomment-322494109

**Comment by escattone** [comment]
See also: https://github.com/mozmeao/infra/pull/418#issuecomment-322508919
