### ISSUE TITLE
Additional rewrite migration for MDN

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#217]
We'll need to migrate [these rewrites](https://github.com/mozilla/kuma/blob/master/configs/htaccess) as well.

See also:
https://github.com/mozmar/infra/issues/180#issuecomment-299853423

**Comment by metadave** [comment]
remaining issues are described in [the PR](https://github.com/mozilla/kuma/issues/4231)

**Comment by jwhitlock** [comment]
I've added [bug 1367782](https://bugzilla.mozilla.org/show_bug.cgi?id=1367782) to track converting robots.txt to a Django view.  I'm not sure if that belongs here, or should be a new issue, or doesn't belong on this issue tracker.

**Comment by metadave** [comment]
@jwhitlock which team will be implementing the changes in  [bug 1367782](https://bugzilla.mozilla.org/show_bug.cgi?id=1367782)? I'm fine with a tracking card in this repo either way.

**Comment by metadave** [comment]
https://github.com/mozilla/kuma/pull/4231

**Comment by metadave** [comment]
PR merged, more info here: https://bugzilla.mozilla.org/show_bug.cgi?id=1362438
