### ISSUE TITLE
MDN mime type analysis

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#244]
The unique list of mime types in SCL3 httpd config are as follows:

```
AddType application/json .json
AddType application/octet-stream .dump
AddType application/ogg .ogx
AddType application/x-compress .Z
AddType application/x-data .data
AddType application/x-gzip .gz .tgz
AddType application/x-pkcs7-crl    .crl
AddType application/x-x509-ca-cert .crt
AddType application/x-xpinstall .xpi
AddType audio/ogg .ogg
AddType audio/ogg .ogg .spx
AddType image/png .png
AddType image/svg+xml .svg
AddType image/svg+xml .svg .svgz
AddType image/x-icon .ico
AddType text/cache-manifest .appcache
AddType text/html .shtml
AddType video/ogg .ogv
AddType video/webm .webm
AddType x-java-archive .jar
```

Django allowed_types are listed [here](https://github.com/mozilla/kuma/blob/7359ae715e2102c96a31a6bc4a970a11fc289932/kuma/settings/common.py#L1430-L1432)

**Comment by jwhitlock** [comment]
Two places where this might need to be migrated:

When Whitenoise serves a file (from static), it uses a [built-in list](https://github.com/evansd/whitenoise/blob/v3.3.0/whitenoise/media_types.py) to determine MIME types.  There's also a [WHITENOISE_MIMETYPES](http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_MIMETYPES) setting, but it's unclear to me if this replaces the list or augments it without reading the Whitenoise code, and we're currently not using it.  It is unclear to me if the Apache list affects files served by Whitenoise. I'm 80% sure that it does not. A few headless integration tests would confirm this.

The Apache mime types definitely come into play when serving user uploads and legacy media files.  Those appear to be covered in task #241, where the aliases for file serving are enumerated.  I doubt that this list is well-synced with the files served by MDN.  There are probably file extensions missing from this list (does that then use system mime types?), and there are probably file extensions here not used by MDN (maybe copied from Bugzilla).

**Comment by metadave** [comment]
@jwhitlock @escattone I'm unsure if recent PR's have addressed these mime type issues.

**Comment by jwhitlock** [comment]
I'll do some testing with ``curl`` on https://mdn-mm.moz.works. Some ideas for where to look:

* [ ] attachments
* [ ] contribute.json
* [ ] diagrams
* [ ] presentations
* [ ] samples

**Comment by metadave** [comment]
much appreciated @jwhitlock!

**Comment by jwhitlock** [comment]
After extensively looking at the files we're serving vs how they are served from SCL3, I think we're in good shape.

I think a lot of the Apache rules were left over from the demo studio, or copied from some other project.

Attachments have the MIME type stored in the database, and set it as the ``Content-Type:`` header. I only checked a few before determining that the extension had nothing to do with the MIME type.

I looked for other files:

* ``application/json`` - [/contribute.json](https://mdn-mm.moz.works/contribute.json)
* ``application/octet-stream`` - [/presentations/xtech2005/e4x/ui/.DS_Store](https://mdn-mm.moz.works/presentations/xtech2005/e4x/ui/.DS_Store)
* ``application/pdf`` - [/presentations/AllAboutCommunity.pdf](https://mdn-mm.moz.works/presentations/AllAboutCommunity.pdf)
* ``application/vnd.ms-powerpoint`` - [/presentations/oscon2005/Ben-EuroOSCON2005.ppt](https://mdn-mm.moz.works/presentations/oscon2005/Ben-EuroOSCON2005.ppt)
* ``application/vnd.oasis.opendocument.presentation`` - [/presentations/xtech2006/xulrunner/XTech%20Slides%20New.odp](https://mdn-mm.moz.works/presentations/xtech2006/xulrunner/XTech%20Slides%20New.odp)
* ``application/xhtml+xml`` - [/samples/svg/swarm-of-motes.xhtml](https://mdn-mm.moz.works/samples/svg/swarm-of-motes.xhtml)
* ``application/x-xpinstall`` - [/samples/xultu/examples/findfile/findfile.xpi](https://mdn-mm.moz.works/samples/xultu/examples/findfile/findfile.xpi)
* ``audio/ogg`` - [/samples/domref/cup.ogg](https://mdn-mm.moz.works/samples/domref/cup.ogg) 
* ``image/gif`` - [/presentations/sxsw2007/the_open_web/images/Frederick-Furnivall.gif](https://mdn-mm.moz.works/presentations/sxsw2007/the_open_web/images/Frederick-Furnivall.gif)
* ``image/jpeg`` - [/presentations/javascript2/images/designingfornext10years.jpg](https://mdn-mm.moz.works/presentations/javascript2/images/designingfornext10years.jpg)
* ``image/png`` - [/diagrams/workflow/images/socorro.png](https://mdn-mm.moz.works/diagrams/workflow/images/socorro.png)
* ``image/svg+xml`` - [/presentations/eich-ajax-experience-2007/photos.svg](https://mdn-mm.moz.works/presentations/eich-ajax-experience-2007/photos.svg)
* ``text/css`` - [/presentations/eich-ajax-experience-2007/ui/default/framing.css](https://mdn-mm.moz.works/presentations/eich-ajax-experience-2007/ui/default/framing.css)
* ``text/html`` - [/presentations/javascript2/bigo.html](https://mdn-mm.moz.works/presentations/javascript2/bigo.html)
* ``text/plain`` - [/samples/xultu/examples/ex_5_2_3.xul.txt](https://mdn-mm.moz.works/samples/xultu/examples/ex_5_2_3.xul.txt) (but ``application/xhtml+xml`` content, so done by extension)
* ``text/plain`` - [/diagrams/workflow/mozilla_workflow.gv.txt](https://mdn-mm.moz.works/diagrams/workflow/mozilla_workflow.gv.txt)
* ``video/ogg`` - [/samples/cssref/transitions/sample1/transitiondemo1.ogv](https://mdn-mm.moz.works/samples/cssref/transitions/sample1/transitiondemo1.ogv)

I couldn't find examples files for these rules, so we'll ignore them.

```
AddType application/octet-stream .dump
AddType application/ogg .ogx
AddType application/x-compress .Z
AddType application/x-data .data
AddType application/x-gzip .gz .tgz
AddType application/x-pkcs7-crl    .crl
AddType application/x-x509-ca-cert .crt
AddType image/x-icon .ico
AddType text/cache-manifest .appcache
AddType text/html .shtml
AddType video/ogg .ogv
AddType video/webm .webm
AddType x-java-archive .jar
```

**Comment by metadave** [comment]
👏 thank you!

**Comment by jwhitlock** [comment]
Script at https://gist.github.com/jwhitlock/ba528e8f6748992734bc31e251fae3e2, in case I need to do similar work again

**Comment by escattone** [comment]
Nice work @jwhitlock, thanks!
