### ISSUE TITLE
Add an environment variable to all containers in k8s

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#250]
I think it'd be nice to have an easy and consistent way that our apps could know that they're running in k8s. We do (at least in bedrock) have to set certain things on k8s vs. Deis v1 due to how SSL is handled, but I could conceive of other things as well. It'd be great to know the cluster name (e.g. `K8S_CLUSTER=virginia`), but just knowing the type of cluster would be enough.

Talking to @jgmize about this on IRC he mentioned [some](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/) [docs](https://kubernetes.io/docs/tasks/configure-pod-container/environment-variable-expose-pod-information/) that may help. I'm not sure what to make of them, but perhaps they'll help whoever takes this.

**Comment by jgmize** [comment]
@pmac what decision(s) will bedrock make based on this hypothetical `K8S_CLUSTER` env var?

**Comment by jgmize** [comment]
I think the existing env vars that you used in https://github.com/mozilla/bedrock/pull/4808/files#diff-52cf8a0329d1c8ce19af17736450e402 make a lot of sense; if you want to add additional env vars using the same mechanisms I have no objections, but ideally I'd like to keep env vars explicitly tied to specific functionality.

**Comment by pmac** [comment]
I'm thinking things like `HTTPS=on` and whether to use the `x-forwarded-proto` headers, etc. We could also dynamically build New Relic App Name if we had cluster and app name in the environment. We had talked about reducing reliance on env variables and moving more to settings, and this would allow more of that.
