### ISSUE TITLE
Install node-problem-detector

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#275]
https://kubernetes.io/docs/tasks/debug-application-cluster/monitor-node-health/

See also: https://github.com/kubernetes/kops/issues/1179

**Comment by jgmize** [comment]
we've had several nodes fall into NotReady status recently without triggering alarms; I believe this should address that situation

**Comment by metadave** [comment]
installed in frankfurt, `node-problem-detector` namespace w/ configmap

https://github.com/kubernetes/node-problem-detector#installation
(non-helm install)

**Comment by metadave** [comment]
/remind me in 5 days to install on other clusters

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/pull/1093
