### ISSUE TITLE
Heapster -> Datadog

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#276]
https://github.com/kubernetes/heapster

https://github.com/kubernetes/kops/blob/master/docs/addons.md#monitoring-with-heapster---standalone

https://www.datadoghq.com/blog/how-to-collect-and-graph-kubernetes-metrics/#collecting-and-storing-metrics-from-heapster

**Comment by metadave** [comment]
note: heapster is already running in the `kube-system` namespace.

**Comment by jgmize** [comment]
Thanks, I've updated the description: I'd like to get the heapster metrics into Datadog.
