### ISSUE TITLE
cluster autoscaling issues

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#286]
The Virginia cluster autoscaler is broken:

       Cluster is not ready for autoscaling: wrong number of nodes for node group: nodes.virginia.moz.works expected: 7 actual: 5

The AWS ASG currently has min = 6, desired = 7, but the k8s autoscaler can't seem resolve to the correct state.

**Comment by jgmize** [comment]
We may want to evaluate (and potentially customize) alternative cluster autoscalers like https://github.com/openai/kubernetes-ec2-autoscaler

**Comment by jgmize** [comment]
We should also look at upgrading to the [latest release](https://github.com/kubernetes/autoscaler/releases/latest).

**Comment by jgmize** [comment]
Some differences between the openai autoscaler and the kubernetes autoscaler: https://github.com/openai/kubernetes-ec2-autoscaler/issues/22#issuecomment-285812953
