### ISSUE TITLE
K8s janitor

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#29]
See: https://trello.com/c/wYLjvoGk/76-k8s-janitor

https://janitor.technology
https://github.com/jankeromnes/janitor
https://www.youtube.com/watch?v=lOWt9-dB-Z4

**Comment by jgmize** [comment]
- main repo has moved to https://github.com/JanitorTechnology/janitor 
- requested k8s support be added to the supported project wishlist: https://github.com/JanitorTechnology/janitor/issues/24#issuecomment-290618780 
- would also like to deploy janitor to k8s, so we could dev k8s in janitor on k8s 😎
