### ISSUE TITLE
install apps in Frankfurt cluster

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#301]
automate as much as possible from https://github.com/mozmar/infra/issues/300

- [x] bedrock
  - [x] app installed and configured
  - [x] stage traffic policy
  - [x] stage traffic policy enabled
  - [x] prod traffic policy
  - [x] prod traffic policy enabled
- [x] snippets
  - [x] app installed and configured
  - [x] prod traffic policy
  - [x] prod traffic policy enabled
- [x] snippets-stats
  - [x] app installed and configured
  - [x] prod traffic policy
  - [x] prod traffic policy enabled
- [x] basket
  - [x] app installed and configured
  - [x] stage traffic policy
  - [x] stage traffic policy enabled
  - [x] prod traffic policy
  - [x] prod traffic policy enabled
- [x] careers
  - [x] app installed and configured
  - [x] prod traffic policy
  - [x] prod traffic policy enabled

**Comment by metadave** [comment]
Frankfurt certs requested

**Comment by jgmize** [comment]
Frankfurt certs approved and available in ACM.

**Comment by glogiotatidis** [comment]
Happy to do my part with careers (nit: not listed in plan) and snippets. I tried to login to the Deis cluster in Frankfurt there's no SSL cert yet. 

When the cert gets fixed feel free to ping me to proceed with the above.

Thanks!

**Comment by metadave** [comment]
@glogiotatidis cert for Deis ELB is now in place. I stepped through [these functions](https://github.com/mozmar/infra/blob/master/k8s/install/stage2_functions.sh#L291-L296
) manually, and missed the [config_annotations](https://github.com/mozmar/infra/blob/master/k8s/install/stage2_functions.sh#L234-L264) call.

**Comment by glogiotatidis** [comment]
> @glogiotatidis cert for Deis ELB is now in place. I stepped through these functions manually, and missed the config_annotations call.

roger that, thanks!

**Comment by metadave** [comment]
traffic policies and health checks created, traffic policies currently NOT enabled.

**Comment by metadave** [comment]
Jekins updated here:
https://github.com/mozmar/snippets-service/pull/248
https://github.com/mozmar/snippets-stats-proxy/pull/2
https://github.com/mozmar/lumbergh/pull/200

**Comment by metadave** [comment]
Waiting on https://bugzilla.mozilla.org/show_bug.cgi?id=1382211 to finish up snippets/snippets-stats

**Comment by metadave** [comment]
see also: https://github.com/mozmeao/infra/issues/358

**Comment by jgmize** [comment]
As I mentioned in https://github.com/mozmeao/infra/issues/335#issuecomment-317538890 we're planning to move nucleus from virginia to frankfurt this week. I just talked to @pmac and he's going to work on creating the deis apps for nucleus-dev & nucleus prod, along with some Jenkinsfile automation for deploying them to the new cluster on push to the master & prod branches, respectively. I'm going to create the nucleus dev & prod DBs in the existing RDS postgres instance in that region, and use pgdump to backup the current DBs in virginia and restore them to the new DBs in frankfurt.

**Comment by metadave** [comment]
@jgmize would love to see the nucleus stuff follow this format so the installation/automation/etc steps are documented: https://github.com/mozmeao/infra/tree/master/apps

**Comment by jgmize** [comment]
@metadave it looks like you already did that part in https://github.com/mozmeao/infra/tree/master/apps/nucleus

**Comment by metadave** [comment]
oh, cool! ok, so then any updates should go in setup.sh/teardown.sh/scale.sh as well, and if anything manual could be documented in the `./apps/nucleus/docs` folder, that would be 💯.

**Comment by metadave** [comment]
finished!

**Comment by pmac** [comment]
Switched basket deployment from virginia to frankfurt in https://github.com/mozmeao/basket/commit/4e36dbcd2e8268e2c4763c4fdfd986f9c21c380b
