### ISSUE TITLE
Prometheus eval

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#310]
- https://prometheus.io/
  - https://github.com/prometheus/prometheus
  - https://github.com/prometheus/alertmanager
- http://blog.runnable.com/post/153498635761/how-we-saved-98-on-infrastructure-monitoring
- https://github.com/micktwomey/prometheus_to_datadog
- https://github.com/DataDog/dd-agent/tree/master/utils/prometheus

**Comment by jgmize** [comment]
https://resources.coreos.com/coreos-fest/end-to-end-monitoring-with-the-prometheus-operator

**Comment by metadave** [comment]
https://www.loomsystems.com/single-post/2017/06/07/Prometheus-vs-Grafana-vs-Graphite---A-Feature-Comparison

**Comment by jgmize** [comment]
https://freshtracks.io/2017/09/deploying-an-ha-prometheus-in-kubernetes-on-aws-multiple-availability-zone-gotchas/

**Comment by jgmize** [comment]
- https://github.com/improbable-eng/thanos
  - https://improbable.io/games/blog/thanos-prometheus-at-scale
  - https://www.infoq.com/news/2018/06/thanos-scalable-prometheus
