### ISSUE TITLE
Mitigate fluentd operational issues

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#326]
- evaluate alternatives such as hindsight: #292 
- automatically delete fluentd pods
  - scheduled
    - jenkins job
    - k8s cron
  - in response to alerts
     - example alert text: `Alert open: Disk IO > 90% on 'virginia-ip-172-20-101-30'`
     - example pod kill command: `kubectl -n fluentd delete pod $(kubectl get pod -n fluentd -o wide | grep 172-20-101-30 | awk '{print $1'})`

**Comment by metadave** [comment]
It seems as though [this change](https://github.com/mozmeao/infra/pull/668) has helped quite a bit. I'm closing this issue for now.
