### ISSUE TITLE
reduce threshold for snippets-stats low metrics alerts

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#328]
We got several alerts that recovered the next minute and appear to have been due to legitimate low traffic on a holiday weekend rather than operational issues, reducing our alert actionability ratio. See also #174 

cc @glogiotatidis

**Comment by jgmize** [comment]
In response to more alerts about low snippets stats tonight and last night, I've lowered the threshold again. While this did not appear to be a load issue on any of the clusters, we have less visibility for this service than for others due to a [lack of NR support for asyncio](https://discuss.newrelic.com/t/support-for-python-3-asyncio-ioloop-eta/38234/16). Just in case, I'm increasing the minimum number of pods from 3 (as set in #164) to 5 in each cluster

**Comment by metadave** [comment]
should the `cmd` autoscaling be added [here](https://github.com/mozmeao/infra/blob/master/apps/snippets-stats/scale.sh) as well?

**Comment by glogiotatidis** [comment]
Actually the alarm was valid: a mis-configured traffic policy was pointing directly to the Deis nginx instead of the ELB instance. The served SSL cert was invalid for the domain and thus it failed to collect a bunch of data. This triggered the alarm. 

I fixed the traffic policy already. I'm working on improving the alarm by testing out datadog's anomaly detection algorithms. While I do that I changed the notification email to myself only to reduce the noise.

**Comment by glogiotatidis** [comment]
I also added a new synthetics monitor to check the SSL on snippet stats traffic policy named "Snippet Stats Traffic Policy"

**Comment by jgmize** [comment]
Good catch, @glogiotatidis. How can we get better visibility on snippets-stats so that we can catch this sort of problem sooner? Do you think we should prioritize #290 and/or #310 since we're basically flying blind on this service without NR support?

**Comment by glogiotatidis** [comment]
Yes, NR support for asyncio is a bummer and yes we could re-write the collector using other async workers.

For this problem there's alerting available which triggered correctly and that I already working on improving. Also I find k8s dashboards more useful than NR in some aspects. You can get CPU and MEM usage -not network unfortunately- which show that the service is very ok with current limits.

**Comment by jgmize** [comment]
> Yes, NR support for asyncio is a bummer and yes we could re-write the collector using other async workers.

I didn't intend to suggest rewriting the collector to use something supported by NR. I think the continued lack of asyncio support is only one of the reasons we should evaluate alternatives to NR. 

> For this problem there's alerting available which triggered correctly and that I already working on improving. Also I find k8s dashboards more useful than NR in some aspects. You can get CPU and MEM usage -not network unfortunately- which show that the service is very ok with current limits.

Good to know, thanks.
