### ISSUE TITLE
eval gitlab

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#329]
https://github.com/kubernetes/charts/tree/master/stable/gitlab-ce

**Comment by jgmize** [comment]
see also https://gitlab.com/gitlab-org/gitlab-ee/issues/2517

**Comment by jgmize** [comment]
https://gitlab.com/help/topics/autodevops/quick_start_guide.md

**Comment by jgmize** [comment]
@metadave I think it makes sense to spin up a dev cluser in GKE and configure gitlab to use it, for example at https://gitlab.com/mozmeao/infra/clusters/new. There's an option to give gitlab permission to do that for you too, but I'd rather not give gitlab full access to any production accounts at this point.

**Comment by jgmize** [comment]
Created "iowa-b" cluster with the following command:
```
gcloud beta container --project "meao-202709" clusters create "iowa-b" --zone "us-central1-b" --username "admin" --cluster-version "1.11.6-gke.3" --machine-type "n1-standard-1" --image-type "COS" --disk-type "pd-standard" --disk-size "100" --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" --num-nodes "2" --enable-cloud-logging --enable-cloud-monitoring --no-enable-ip-alias --network "projects/meao-202709/global/networks/default" --subnetwork "projects/meao-202709/regions/us-central1/subnetworks/default" --addons HorizontalPodAutoscaling,HttpLoadBalancing --enable-autoupgrade --enable-autorepair
```

**Comment by jgmize** [comment]
Copied the required values from ~/.kube/config to https://gitlab.com/mozmeao/infra/clusters/new and now the "integration status" for https://gitlab.com/mozmeao/infra/clusters/36336 is good, but I got the following when I tried to install Helm Tiller through the gitlab UI: 
![image](https://user-images.githubusercontent.com/161718/51736065-c2d83d00-204e-11e9-9230-cb136cdbaf81.png)

**Comment by safwanrahman** [comment]
>https://github.com/kubernetes/charts/tree/master/stable/gitlab-ce

I am not big fan of official helm charts! they are far from production ready!

**Comment by pmac** [comment]
I don't think we need to run Gitlab CE for ourselves. The hosted version at gitlab.com is great and makes it very easy to run the CI jobs on our infra much more simply. I got the www-admin repo running jobs successfully on my linode machine quite easily last night. Using the "shell" runner type we can run whatever scripts we want during the build and keep all secrets on the machine in whatever way we want, or even just run the gitlab-runner daemon on a privledged machine in the cluster, or in k8s itself. The gitlab-runner daemon polls gitlab, so the runner machine doesn't need to be externally accessible by gitlab (or anyone). It actually works quite similarly to git-sync-operator in that way, but acts more like traditional 3rd party hosted CI with a nice UI and logs and things.

**Comment by metadave** [comment]
Looks like this requires Redis and Postgresql. Can we see how far the [Gitlab Runner in K8s and/or shell](https://docs.gitlab.com/runner/#install-gitlab-runner) gets us?
