### ISSUE TITLE
move surveillance to S3/CloudFront

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#332]

**Comment by jgmize** [comment]
See https://github.com/mozmeao/infra/issues/335#issuecomment-317538890

**Comment by jgmize** [comment]
Requested and approved cert in us-east-1 region for use in cloudfront.

arn:aws:acm:us-east-1:236517346949:certificate/05191cfb-620b-4d16-bdda-ac155f5fd665

**Comment by jgmize** [comment]
https://github.com/mozmeao/infra/pull/376#issuecomment-318954399
