### ISSUE TITLE
scale down/decom Virginia cluster

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#335]

**Comment by metadave** [comment]
surveillance and snippets-stats are still running in Virginia.

**Comment by metadave** [comment]
- scaled down to 3 workers
- 3 masters are still online

**Comment by metadave** [comment]
@jgmize how far do we want to scale this cluster down?

**Comment by jgmize** [comment]
As discussed in IRC, there are some resources still being used by apps that are no longer in the production traffic policies, so I'm going to delete those deis apps & k8s namespaces after double checking the traffic polices. Once those are deleted we should have more available resources for the app(s) still in production on that cluster. I'd like to move those remaining apps off of the cluster this week if possible.

**Comment by jgmize** [comment]
The work described in my previous comment is now complete, and we have 2 remaining production apps on the virginia cluster:
- nucleus.mozilla.org
- surveillance.mozilla.org
As discussed, I hope to move nucleus to frankfurt and surveillance to s3+cloudfront this week so that we can decom the virginia cluster.

**Comment by metadave** [comment]
@jgmize we'll need to check "regular" New Relic and Synthetics for any stray monitors as well.

**Comment by metadave** [comment]
@jgmize one remaining that I dropped the ball on is moving the mdn-dev envs to frankfurt: https://github.com/mozilla/kuma/compare/dp-move-dev-env-to-frankfurt?expand=1

I don't think there's much work beyond what's on that branch, but I switched to K8s in Portland to unblock Ryan.

**Comment by jgmize** [comment]
@metadave my understanding of our discussion on IRC is that once https://github.com/mozilla/kuma/pull/4342 is merged there won't be any more need of the  virginia cluster for mdn. @escattone does that sound right to you?

**Comment by jgmize** [comment]
> @metadave my understanding of our discussion on IRC is that once mozilla/kuma#4342 is merged there won't be any more need of the virginia cluster for mdn. @escattone does that sound right to you?

Am I clear to shut down the virginia cluster now?

**Comment by metadave** [comment]
sure

**Comment by jgmize** [comment]
ok. destroyed virginia.

**Comment by jgmize** [comment]
> 3:30 PM <metadave> I created a resource group using the KubernetesCluster tag w/ virginia.moz.works to see if anything was left
> 3:31 PM <metadave> 1 ELB, 3 security groups, 1 VPC that kops probably didn't clean up
> 3:31 PM <metadave> and 7 EBS volumes
