### ISSUE TITLE
Add assets.mozilla.net to the cert for assets.moz.works

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#354]
I've filed a [bug to have a CNAME added for assets.mozilla.net](https://bugzilla.mozilla.org/show_bug.cgi?id=1382354) to point at assets.moz.works. Bedrock would rather use this domain since it's already in our CSP and will be much more easily identified as a 1st party resource.

**Comment by pmac** [comment]
The bug is now closed and the CNAME has been added and is working.

**Comment by jgmize** [comment]
requested & approved new cert, but when I tried to use it (see commit above) I got the following error:
```
aws_cloudfront_distribution.s3_distribution: InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.
```

**Comment by jgmize** [comment]
https://github.com/mozmeao/infra/pull/372#issuecomment-318716873
