### ISSUE TITLE
Move Nucleus to Frankfurt

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#363]
See also: https://github.com/mozmeao/infra/issues/184

**Comment by metadave** [comment]
ping @jgmize

**Comment by metadave** [comment]
related: https://github.com/mozilla/nucleus/pull/27

**Comment by jgmize** [comment]
using scripts and docs in https://github.com/mozmeao/infra/tree/master/apps/nucleus to create nucleus-dev & nucleus-prod apps in frankfurt

**Comment by jgmize** [comment]
https://github.com/mozmeao/infra/pull/375#issuecomment-318946168
