### ISSUE TITLE
provision Portland K8s cluster

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#366]
- single AZ
- install Deis Workflow, no other associated apps for now.

**Comment by escattone** [comment]
This would be great, since we could do our work against the latest Kubernetes.

**Comment by metadave** [comment]
@escattone here are the docs I use to startup a new cluster: https://github.com/mozmeao/infra/tree/master/k8s/install

**Comment by metadave** [comment]
@jgmize I requested a new cert for this cluster, can you approve when you get a chance?

**Comment by jgmize** [comment]
cert approved, thanks @metadave

**Comment by metadave** [comment]
- See [this](https://github.com/mozmeao/ee-infra-private/pull/108) PR for a node on the Deis install.
- https://github.com/mozmeao/ee-infra-private/pull/107

Cluster provisioned, monitoring installed (fluentd/mig/newrelic/etc), no production apps are running here.
