### ISSUE TITLE
MDN build automation

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#374]
Allow our MDN installation to support single-region/multi-environment (dev/stage/prod):
https://github.com/mozmeao/infra/pull/368#issuecomment-318690253

- this issue covers `k8s-services`/`k8s-deployment` from the image below.
- `aws-infra` will be tracked [here](https://github.com/mozmeao/infra/issues/378)

**Comment by metadave** [comment]
cc @escattone 
click the image to make it larger.
![mdn_make_targets_xmind](https://user-images.githubusercontent.com/58244/28840068-c39c1904-76c3-11e7-934a-eeef92db1742.png)

**Comment by metadave** [comment]
@escattone anything else we should include here, or do you think this issue can be closed?

**Comment by escattone** [comment]
@metadave I'd like to keep this open a bit longer, to do these things:
- adjust settings
- ensure kuma, kumascript, and integration tests (at least the ones that make sense) run fine
- decide how we're going to handle the stage/prod secrets

Does that make sense, or should we create new cards for those tasks?

**Comment by metadave** [comment]
works for me!

**Comment by metadave** [comment]
per a discussion with @escattone, we're going to close this.
