### ISSUE TITLE
Datadog for basket is not configured in tokyo or frankfurt

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#381]

**Comment by pmac** [comment]
It is configured correctly now, as of Wed, Aug 2nd. However some Datadog graphs on dashboards need to have the data from those regions added. Should we use this issue for that, or call it done?

For full-disclosure, @glogiotatidis gave me the fix on IRC:

```shell
# from jenkins server
$ DEIS_PROFILE=frankfurt deis2 config:set -a basket-prod STATSD_HOST=datadog-statsd.datadog.svc.cluster.local
```

**Comment by metadave** [comment]
@pmac I think it's fine to keep it in this issue

**Comment by metadave** [comment]
Which Datadog views need data from Frankfurt and Tokyo?

**Comment by pmac** [comment]
I'll have to audit that. I think this is about the dashboards, so I just need to go through them.

**Comment by metadave** [comment]
Thanks @pmac!
