### ISSUE TITLE
K8s rolling update testing

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#382]
lets explore how Kuma updates can work with 0-downtime:

See: https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/

**Comment by escattone** [comment]
I've created https://github.com/mozmeao/infra/pull/496 which adds initial make commands for performing rolling updates.

**Comment by metadave** [comment]
@escattone I can bump up the size of the deployment, let me know which one(s) you'd like me to adjust.

**Comment by escattone** [comment]
Wow, just "discovered" that K8s is much more intelligent about rolling updates when using [Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment) than I realized! Once the initial deployments have been made (i.e., "web", "api", "kumascript", "celery-worker", "celery-beat", and "celery-cam"), a rolling update for any one of the deployments can be triggered simply be deploying it again (using the same name of course), but this time with one or more changes to its `spec.template` YAML.

**Comment by escattone** [comment]
I'm going to update the "rollout" commands added in #496 given my new understanding.

**Comment by escattone** [comment]
See https://github.com/mozmeao/infra/pull/501

**Comment by metadave** [comment]
ok to close?

**Comment by escattone** [comment]
@metadave Let me add one or two more comments, for example on rolling back, and then I'll close it, thanks!

**Comment by escattone** [comment]
If a rolling update has been started or completed, for example let's say we're updating our Kuma deployments with a new image:
```
# start at the root of the infra repo
cd apps/mdn/mdn-aws/k8s
export KUMA_IMAGE_TAG=bf7935a
make k8s-kuma-deployments
```
and something goes wrong or we just don't want the update, we can easily roll it back by undoing the most recent update to the Kuma-based deployments (I'll simplify this later with a `make k8s-kuma-rollback` command):
```
kubectl rollout undo deployment web
kubectl rollout undo deployment api
kubectl rollout undo deployment celery-worker
kubectl rollout undo deployment celery-beat
kubectl rollout undo deployment celery-cam
```

**Comment by escattone** [comment]
See https://github.com/mozmeao/infra/pull/520
