### ISSUE TITLE
The mdn-dev namespace was stuck in "Terminating" state

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#390]
Posting this in case we have any similar issues w/ deleting a namespace.

The `mdn-dev` namespace has been stuck in `Terminating` state for 6 days. 
Issuing another delete didn't change the state:

        kubectl delete namespace mdn-dev

I checked for any existing resources in the `mdn-dev` namespace with:

        kubectl -n mdn-dev get all

I tried killing the k8s controller:

        kubectl -n kube-system get pods | grep controller
        kubectl -n kube-system delete pod ${CONTROLLER_POD}

After restarting the controller, a regular delete didn't work:

               kubectl delete namespace mdn-dev

But following that with a force delete seemed to help:

        kubectl delete ns mdn-dev --grace-period=0 --force

It's definitely possible that the force kill could have worked without killing the controller, but I wasn't aware that you could force kill a namespace.

cc @jgmize @escattone

**Comment by jgmize** [comment]
Thanks for the details @metadave!

**Comment by jgmize** [comment]
Let's block upgrading any other clusters to 1.7.2 until we have more details on the root cause.

**Comment by metadave** [comment]
It looks like the issue has been around for awhile, but it's been reported as fixed:
https://github.com/kubernetes/kubernetes/issues/19317
https://github.com/kubernetes/kubernetes/issues/37554
https://github.com/kubernetes/kubernetes/issues/37278

**Comment by gnufreex** [comment]
This does not work for me. It is still in terminating phase after killing the controller and force killing the namespace

**Comment by gnufreex** [comment]
kubectl get namespace/monitoring -o json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "creationTimestamp": "2017-09-24T19:23:07Z",
        "deletionTimestamp": "2017-09-24T19:33:44Z",
        "name": "monitoring",
        "resourceVersion": "11452539",
        "selfLink": "/api/v1/namespaces/monitoring",
        "uid": "cba1900b-a15d-11e7-8350-02a930332a2a"
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Terminating"
    }
}

**Comment by eigokor** [comment]
Have same issue, 3 namespaces are in "Terminating state"
--force -grace-period=0. has no effect

`→ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by metadave** [comment]
@gnufreex @eigokor we run Kubernetes, but we don't provide support. Your best bet is to update issues in https://github.com/kubernetes/kubernetes/

**Comment by eigokor** [comment]
Sry..
