### ISSUE TITLE
Jenkins deployments to AWS stage and prod

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#394]

**Comment by metadave** [comment]
see also: https://github.com/mozmeao/infra/issues/382

**Comment by metadave** [comment]
blocked by https://github.com/mozmeao/infra/issues/615

**Comment by escattone** [comment]
https://github.com/mozilla/kuma/pull/4488
https://github.com/mozmeao/infra/pull/629

**Comment by escattone** [comment]
These two PR's provide a special branch on both Kuma and Kumascript that pushes its associated image (Kuma or Kumascript) to stage when updated:

https://github.com/mozilla/kuma/pull/4503
https://github.com/mdn/kumascript/pull/395

**Comment by escattone** [comment]
Made a minor fix: https://github.com/mozilla/kuma/pull/4525

**Comment by escattone** [comment]
These PR's provide the Jenkins machinery for the special `prod-push` branch for both Kuma and Kumascript:
- https://github.com/mozilla/kuma/pull/4588
- https://github.com/mdn/kumascript/pull/436
