### ISSUE TITLE
Evaluate a tool for accepting github webhooks

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#403]
It seems wasteful to me that we're still having Jenkins check our github repos every minute for changes. I'm wondering if it wouldn't be better and more respectful of our resources to use something like this:

https://github.com/carlos-jenkins/python-github-webhooks

It could be run dockerized in the cluster with our Jenkins box and be used to take in hooks, filter the things in which a project is interested, and ping Jenkins on a private URL (not open to the public internet) based on all of that.

Could be overkill, or could be a layer of useful customization. I'm on the fence. This issue is for discussion of such a thing.

**Comment by pmac** [comment]
All this is assuming there isn't a secure way to do this with Jenkins itself. I'm pretty sure I recall us trying and failing to find such a thing in the past.

**Comment by jgmize** [comment]
@pmac please take a look at #386 and let me know what you think.

**Comment by jgmize** [comment]
https://github.com/kubernetes/test-infra/blob/master/prow/architecture.md

**Comment by pmac** [comment]
Prow does seem like it's what we want. That architecture doc to which you linked in #386 was full of words that I'm sure make sense to someone, but which would take me more than a few hours to look up. So I'm going to assume that it'll result in us being able to use Github webhooks to trigger jobs in Jenkins. If that's the case then I'm +1 on using Prow if that's what the SREs prefer and we can close this as a dupe 👍
