### ISSUE TITLE
decommission Portland Deis 1 cluster

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#404]
- notify teams for each hosted app that Jenkins will need to be updated to skip pushing to usw

**Comment by jgmize** [comment]
Created [VPC peering connection](http://docs.aws.amazon.com/AmazonVPC/latest/PeeringGuide/create-vpc-peering-connection.html#create-vpc-peering-connection-local) to allow nodes in new k8s VPC to talk to RDS, elasticache, etc in existing VPC.

**Comment by glogiotatidis** [comment]
> Created VPC peering connection to allow nodes in new k8s VPC to talk to RDS, elasticache, etc in existing VPC.

Thanks Josh. I still can't connect to ee-mariadb and ee-redis from portland.moz.works. Is there something 
additional i should be doing?
