### ISSUE TITLE
MDN architecture docs

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#407]
- lets start with a high level architecture diagram
- add other docs as needed

**Comment by escattone** [comment]
I updated the architecture diagram to include Elastic Cloud as well as all of the interconnections between the services.

**Comment by metadave** [comment]
![mdn_aws_conceptual_architecture_and_service_dependencies_-_google_drawings](https://user-images.githubusercontent.com/58244/29286264-6ef2fada-80ff-11e7-9f05-4d8d48d52087.png)

click to zoom.

**Comment by metadave** [comment]
closing for now, we're going to be working on better diagrams soonish.
