### ISSUE TITLE
Ark eval

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#411]
https://github.com/heptio/ark

utility for managing disaster recovery, specifically for Kubernetes cluster resources and persistent volumes

**Comment by jgmize** [comment]
This may be a suitable replacement for the EFS backups implemented in https://github.com/mozmeao/infra/pull/389

**Comment by metadave** [comment]
Ark requires K8s 1.7+, so our options for testing are currently limited.

**Comment by metadave** [comment]
https://github.com/heptio/ark/pull/692

**Comment by metadave** [comment]
- Ark installed in Oregon-A, Oregon-B, and Frankfurt w/ daily backups scheduled
- see infra-private/ark/* for cluster-specific install info

**Comment by metadave** [comment]
docs: https://github.com/mozmeao/infra/pull/892

**Comment by metadave** [comment]
- also installed in Portland and Iowa-A
- Portland required a client/server downgrade: https://github.com/mozmeao/infra/pull/893
