### ISSUE TITLE
MDN attachments with unicode characters are breaking sync from SCL3 to S3

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#412]
[Several MDN attachments](https://gist.github.com/metadave/88d586eb5db927476f8570a40e712d2e) include unicode characters in their names which prevents `aws s3` and `s3cmd` from copying data out of SCL3.

Lets figure out what can be done with these files to allow us to move forward.

see also: https://bugzilla.mozilla.org/show_bug.cgi?id=1271743

**Comment by metadave** [comment]
ok, I have a workaround that excludes each "broken file from SCL3: https://gist.github.com/metadave/e3e53720fe2fa133a91eb66483eff4ad

**Comment by jwhitlock** [comment]
I've [searched MDN](https://gist.github.com/jwhitlock/0806dd215dbc61a44d46378d625eaaa0), and it appears that all but one of the problem files are unused. The [last file](https://mdn.mozillademos.org/files/3324/transition-timing-function.png) was used on the English page until [December 2012](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions$revision/342403), when the page was re-worked.  There are a couple of translations, such as the [Spanish one](https://developer.mozilla.org/es/docs/Web/CSS/Transiciones_de_CSS), that continue to use it.

In any case, the attachment is loaded by ID, so it is safe to change the filename. The change needs to be synchronized between the database and the file system. I'll try on this one first, which will be obvious if it fails, and then change the other 15 files.

**Comment by jwhitlock** [comment]
I had to manually rename files with ``sudo``, but I was able to give the 15 files AWS-friendly names. I was able to [script](https://gist.github.com/jwhitlock/0806dd215dbc61a44d46378d625eaaa0) some of it. I confirmed the image used on MDN still works, and spot-checked others.

I was unable to rename two files, and had to duplicate them instead. I've opened [bug 1399237](https://bugzilla.mozilla.org/show_bug.cgi?id=1399237) to ask webops to look into deleting the files with the old names. Until that's done, the sync will continue having issues.

**Comment by metadave** [comment]
thanks @jwhitlock, I can easily get rid of the file [exceptions in the sync script](https://gist.github.com/metadave/e3e53720fe2fa133a91eb66483eff4ad#file-sync-sh-L15-L29) once this is all set.

**Comment by jwhitlock** [comment]
I was able to [move the containing directories out of the attachment folders](https://bugzilla.mozilla.org/show_bug.cgi?id=1399237#c1), so now the two AWS-unfriendly files are gone. @metadave, please update the sync script.

**Comment by metadave** [comment]
all set, reran the sync to S3 without issues.

**Comment by jwhitlock** [comment]
It looks like an additional action is needed (recreate the containers?) to see the new files in the mdn-mm web containers.  I'll also need to run the script that updates the file paths in the database.

**Comment by metadave** [comment]
@jwhitlock there's an hourly crontask that pulls content down from S3. I'll tweak it and make it happen sooner.

**Comment by metadave** [comment]
I changed the cronjob to run every minute for an initial pull of any new files, and then switched back to hourly.

**Comment by jwhitlock** [comment]
Thanks @metadave, I see the new files. It took me a few rounds to update my [script](https://gist.github.com/jwhitlock/0806dd215dbc61a44d46378d625eaaa0) for AWS. I had to encode file path names in UTF-8, rather than using unicode. This may be a setup issue, or I may need to send the environment variable``LANG`` for ssh connections.

The anon DB on mdn-mm has the paths for the new filenames, and is serving the ["problem" content](https://mdn-mm-demos.moz.works/files/3020/Avatar.jpg).

These manual steps goes against my assertion that we don't need to update the anon DB.  I think we can ignore 15 broken, unused files for a few months, though.
