### ISSUE TITLE
Jenkins on Kubernetes

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#42]
See also: https://github.com/kubernetes/charts/tree/master/stable/jenkins

**Comment by jgmize** [comment]
@glogiotatidis do you think you might have some time to work on this in Q2?

**Comment by jgmize** [comment]
https://www.youtube.com/watch?v=eMOzF_xAm7w

**Comment by glogiotatidis** [comment]
> @glogiotatidis do you think you might have some time to work on this in Q2? If not please move this to the Q3 milestone

Probably not with all the SUMO stuff

**Comment by jgmize** [comment]
cc @gleefulcoder

**Comment by jgmize** [comment]
cc @brittberwanger

**Comment by jgmize** [comment]
we should port https://github.com/mozmar/ee-infra-jenkins/blob/master/templates/nginx-cfg.j2 or better yet, a whitelist approach for presenting a limited public view

**Comment by brittberwanger** [comment]
https://kumorilabs.com/blog/k8s-6-integrating-jenkins-kubernetes/ - Tutorial walking through dynamically provisioning jenkins agents on a k8s cluster on AWS
