### ISSUE TITLE
CDN implementation analysis

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#424]
- do we create a new Cloudfront distribution ~or attempt to transfer the existing CF distribution (not even sure if that's possible in AWS)~
  - new Cloudfront distribution
- do we continue to use the developer.cdn.mozilla.net domain, or assume control of a new domain for more flexibility?
- how will this work when we go live, do we need to give ops a few weeks notice before making changes?

**Comment by jgmize** [comment]
Unless something has changed since the last time  we looked into it, transferring cloudfront distributions between AWS accounts is not possible to do without significant downtime. I believe the most straightforward path is to create a new CF distribution and set the `MEDIA_URL` in the new deployment to the new domain.

**Comment by metadave** [comment]
should we request that `developer.cdn.mozilla.net` be a CNAME for `mdn-cdn.moz.works`, which (for now) would point to the current IT managed CF distribution? Then we have the option to easily cutover to our new CF + domain. Otherwise, any suggestions for a new domain that we manage?

cc @jwhitlock @jgmize

**Comment by jwhitlock** [comment]
@jgmize has a better mental separation between CDNs and providers, so I think he's the authority.

CF is ambiguous to me. Is that [CloudFlare](https://www.cloudflare.com/lp/overview-a/?_bt=77653027916432&utm_term=cloudflare&utm_campaign=A100_Bing_Search_Brand_US_English&utm_source=bing&utm_medium=cpc) or [AWS's CloudFront](https://aws.amazon.com/cloudfront/)? ``developer.cdn.mozilla.net`` is currently a CloudFront site, according to headers.

My understanding was that CloudFront is tied to the DNS, and switching to a new account also means a new DNS name (immediate) or some downtime to transfer an existing DNS name.  I may be confusing this with S3-backed CloudFront, or some other issue.

I thought we would continue to point ``developer.cdn.mozilla.net`` at SCL3, and only switch to new CloudFront accounts with new DNS names.  This is configurable with ``MEDIA_URL`` in MDN, and so can serve dynamic pages from AWS servers while serving assets from SCL3, as long as both servers are on the same assets (which usually means the same commit, but there is some flexibility).

So, I thought we would continue to use ``developer.cdn.mozilla.net`` as an SCL3-backed CDN, including during maintenance mode tests, until we start moving the "master" services (staging, prod) to AWS, where a new CDN would take over. Or, we can continue deploying to SCL3 as well, during a DNS turnover, if CloudFront allows that.

**Comment by metadave** [comment]
HTTP2 info: https://bugzilla.mozilla.org/show_bug.cgi?id=1368126

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/issues/427
