### ISSUE TITLE
secure repo for MDN creds

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#426]
I'm thinking of creating an `mdn/infra-private` repo with [git crypt](https://www.agwa.name/projects/git-crypt/) to separate MDN credentials/secrets. Any thoughts or objections?

cc @jgmize @escattone @jwhitlock

**Comment by escattone** [comment]
Awesome, I love it! I've been meaning to ask you how you'd recommend handling credentials.

**Comment by metadave** [comment]
we can use https://github.com/mozmeao/mdn-k8s-private

**Comment by metadave** [comment]
@jwhitlock @escattone I see that your GPG keys are registered in https://github.com/mozmeao/mdn-k8s-private. Can you clone the repo, `git crypt unlock` and see if you can read `credentials.yml`? When you're finished, please run `git crypt lock`.

**Comment by jwhitlock** [comment]
yes, can ``git crypt unlock``.

**Comment by escattone** [comment]
Oh man, sorry for the delay, this got lost in last week's work! Yes, I can `git crypt unlock` as well, thanks @metadave !
