### ISSUE TITLE
serve legacy files from AWS

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#428]
see https://github.com/mozmeao/infra/issues/197

**Comment by escattone** [comment]
For the Kuma side, submitted https://github.com/mozilla/kuma/pull/4365, and for the K8s side submitted https://github.com/mozmeao/infra/pull/431 which depends on https://github.com/mozilla/kuma/pull/4365.

**Comment by jwhitlock** [comment]
Reviewed https://github.com/mozilla/kuma/pull/4365, small nits but it works. @metadave I can fix in a new commit if you want it merged ASAP.

**Comment by metadave** [comment]
@jwhitlock doesn't have to be ASAP, soonish would be great though!

**Comment by jwhitlock** [comment]
Fixed nits, merged https://github.com/mozilla/kuma/pull/4365

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/pull/431 has been merged, I'm closing this issue for now.
