### ISSUE TITLE
Implement and retire remaining Apache rules

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#436]
In https://github.com/mozilla/kuma/pull/4231, @metadave mentioned the rules in [config/htaccess](https://github.com/mozilla/kuma/blob/master/configs/htaccess) he didn't apply.  One of these is the cause of [bug 962148](https://bugzilla.mozilla.org/show_bug.cgi?id=962148#c10), a 4-year-old bug.

Since we have control of this Apache file, we can fix bad and broken redirects in the redirects library, and remove the bad rules from the file.

We can then continue by removing the rules that are implemented in Apache and in Kuma, leaving almost nothing in the ``.htaccess`` file. 

Tasks:

* Under [bug 1362438](https://bugzilla.mozilla.org/show_bug.cgi?id=1362438):
  * [x] Return 404 for ``patches``, ``web-tech``, and ``css``
  * [x] Return 404 for ``index.php``
  * [x] Redirect ``/contests`` to http://www.mozillalabs.com/
  * [x] Redirect ``/es4`` to http://www.ecma-international.org/memento/TC39.htm
* Under [bug 962148](https://bugzilla.mozilla.org/show_bug.cgi?id=962148#c10):
  * [x] Redirect ``/en/`` to ``/en-US/``
  * [x] Redirect ``/cn/`` to ``/zh-CN/``
  * [x] Redirect ``/zh_cn/`` to ``/zh-CN/``
  * [x] Redirect ``/zh_tw/`` to ``/zh-TW/``

**Comment by jwhitlock** [comment]
Added the remaining tasks as a checklist. I've opened https://github.com/mozmeao/infra/issues/445 for serving sitemap.xml, which might require adjusting the attachments feature that @escattone implemented, or some other AWS-specific view.

**Comment by jwhitlock** [comment]
Opened ttps://github.com/mozilla/kuma/pull/4381

**Comment by jwhitlock** [comment]
https://github.com/mozilla/kuma/pull/4381 now just covers [bug 1362438](https://bugzilla.mozilla.org/show_bug.cgi?id=1362438). I've moved the commit to branch [legacy-locales-962148](https://github.com/mozilla/kuma/compare/master...jwhitlock:legacy-locales-962148?expand=1), and @safwanrahman is working on an alternate solution in https://github.com/mozilla/kuma/pull/4387.

**Comment by escattone** [comment]
Thanks @jwhitlock and @metadave for all of your work in digging into the Apache rules and adding the `redirect_urls` middleware and associated redirects to Kuma.

**Comment by jwhitlock** [comment]
Both [PR 4381](https://github.com/mozilla/kuma/pull/4381) and [PR 4387](https://github.com/mozilla/kuma/pull/4387) were pushed to production.

**Comment by metadave** [comment]
fantastic, thank you @jwhitlock
