### ISSUE TITLE
Elastic Search 2017 Billing/Expensing

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#441]
Sort out Elastic Search 2017 Billing/Expensing. ES will not invoice unless we do a yearly contract so for the remainder of 2017 we will pay / expense. Tasks here are:

- [x] Submit legal agreement review via CASA -> https://biztera.com/projects/10505
- [x] Get account credentials from Ryan, change if needed but add to private encrypted repo.
- [ ] Set up billing
- [ ] Update [mana page](https://mana.mozilla.org/wiki/display/EN/Paid+Accounts)

**Comment by metadave** [comment]
@bensternthal is this all set?

**Comment by bensternthal** [comment]
Doh forgot to close this out. 

Yep we are all set and I communicated to Ryan all the details and what he needs to do to actually purchase.

Finance, Credit Card & Account are all sorted.
