### ISSUE TITLE
Bedrock Synthetics alert from Tokyo, August 25 2017

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#451]
At 6:16 PM UTC, we received an alert from New Relic [Synthetics](https://synthetics.newrelic.com/accounts/1299394/monitors/81a0480c-5c13-4539-8063-a38472f3d2d2/results/b4414986-9c72-4ac3-a1d0-9c8aa67f39c8?via=email&view=timeline) from Tokyo (not the K8s cluster) showing:
    
        NetworkError: Unrecognized SSL message, plaintext connection?

- The address specified in the alert shows: `https://www.mozilla.org:80`, which *should* fail, however the monitor is configured to use `http://www.mozilla.org`. I'm guessing the http->https redirect had something to do with this.
- New Relic doesn't seem to be having any [issues](https://status.newrelic.com/).
- mozilla.org seems to be loading fine, we'll continue to monitor through the work day.
- the alert closed as of 6:25 PM UTC

**Comment by jgmize** [comment]
> The address specified in the alert shows: https://www.mozilla.org:80, which should fail, however the monitor is configured to use http://www.mozilla.org. I'm guessing the http->https redirect had something to do with this.

@metadave while this sounds like a temporary blip that doesn't strictly require action on our part, can you think of any reason we shouldn't reconfigure the monitor to connect to https instead of http?
