### ISSUE TITLE
create K8s secrets resources for stage/prod

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#463]
we'll need to split out secrets so they don't need to be deployed with each Jenkins deployment.

**Comment by metadave** [comment]
@escattone this just hit me this morning, we'll need to create secrets for all the stage/prod environment vars so we can create those once and then let Jenkins push new deployments.

**Comment by escattone** [comment]
@metadave That's a good point! It doesn't make sense to have to deploy the secrets each time.

**Comment by metadave** [comment]
I'm thinking of how Jenkins will work, I don't think we can have an unlocked mdn-k8s-private repo on the Jenkins server to populate the secrets on each push. The secrets can be stored and deployed once from mdn-k8s-private.

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/pull/467
