### ISSUE TITLE
create an "under maintenance" app

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#464]
Should we create a single HTML page docker/K8s app that we can route traffic to during our migration?

We can change the Route 53 traffic policy from SCL3 to this site while DB backup/restore runs, and then change the traffic policy again to the new K8s-hosted MDN site. Otherwise, I'm not sure where to point developer.mozilla.org during our migration.

cc @escattone @jwhitlock @jgmize

**Comment by escattone** [comment]
@metadave My understanding was that we would deploy to SCL3 with `MAINTENANCE_MODE=True` (and optionally, a read-only db user/password, but it's not necessary). That will deploy a read-only MDN to SCL3 while we dump the database. This hasn't yet been tested in production in SCL3, but it has been tested in staging and we will test it prior with our short (several hour) MAINTENANCE_MODE test in AWS.

**Comment by metadave** [comment]
If the maintenance page runs in SCL3, wouldn't we want to migrate that too?

**Comment by metadave** [comment]
@escattone when do you think it will be reasonable to test maintenance mode in SCL3?

**Comment by jwhitlock** [comment]
Here's what SCL3 maintenance mode looks like:https://developer.mozilla.org/media/maintenance/

I think ``MAINTENANCE_MODE=True`` replaces this. We've successfully tested it in SCL3 production ([milestone MDN AWS A2](https://github.com/mozmeao/infra/milestone/14)), and will use that for the transfer.  I'm removing it from the AWS milestone.

@escattone, @metadave, do you see a value in this feature? It could be hosted with a simple nginx container. It would be useful when ``MAINTENANCE_MODE=True`` can't be used, but I'm not sure when that would be.  If there's no value, we can close the issue.

**Comment by jwhitlock** [comment]
We were able to complete the migration with ``MAINTENANCE_MODE=True``, which seems sufficient for planned maintenance until after the operations move from MozMEAO
