### ISSUE TITLE
Replace ELBs with NLBs and/or ALBs

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#466]
- https://aws.amazon.com/blogs/aws/new-network-load-balancer-effortless-scaling-to-millions-of-requests-per-second/
- https://github.com/kubernetes/kubernetes/issues/52173
- https://github.com/terraform-providers/terraform-provider-aws/issues/1618

**Comment by jgmize** [comment]
Need to evaluate NLB vs ALB use cases.
- https://aws.amazon.com/blogs/aws/new-application-load-balancer-sni/
- https://github.com/coreos/alb-ingress-controller

**Comment by jgmize** [comment]
ALBs support multiple SSL certs via SNI: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#https-listener-certificates

**Comment by metadave** [comment]
ALB's would let us use https://aws.amazon.com/waf/ if desired.

**Comment by MrCskncn** [comment]
Still no support?

**Comment by pb8226** [comment]
@MrCskncn I thought it was supported here by choosing the type of the LB: https://www.terraform.io/docs/providers/aws/r/lb.html#load_balancer_type
