### ISSUE TITLE
configure DNS for mdn-stage.moz.works

### ISSUE THREAD

**Issue by escattone** [mozmeao/infra#473]
@metadave Could you configure a DNS entry for `mdn-stage.moz.works` to point to the stage ELB `a57220b6c94df11e7b1e70287e8e34e8-2086634506.us-west-2.elb.amazonaws.com`? Is that the intermediate domain we're going to use for staging?

**Comment by metadave** [comment]
done! That's the correct ELB, and `mdn-stage.moz.works` is what we'll use for stage.

**Comment by metadave** [comment]
there doesn't appear to be a valid cert for `mdn-stage.moz.works`, I'll have to request one in the AM.

**Comment by metadave** [comment]
I see a developer.allizom.org and a developer.mozilla.org cert in us-west-2, but they don't have the .moz.works as additional names.

**Comment by metadave** [comment]
I reverted this change for now, developer.allizom.org points to mdn-stage.moz.works.

We may need a new domain before the release(s) so we don't interfere with existing MDN updates that use developer.allizom.org.

**Comment by metadave** [comment]
closing this for now!
