### ISSUE TITLE
Add env overrides for SCL3 production settings (bug 1308630)

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#477]
Add environment overrides for required settings in ``settings_local.py`` in SCL3, so that they can be set in AWS as well.

The SCL3 security sensitive settings are contained in a ``settings_local.py`` file that is the default Django settings file in production.  It loads settings (``from settings import *``), and then overrides and adds additional settings for production.

The files can be accessed from the ``developeradm`` admin node at:

* Production - ``/data/developer/src/developer.mozilla.org/kuma/settings_local.py``
* Staging - ``/data/developer-stage/src/developer.allizom.org/kuma/settings_local.py``

Due to the sensitive nature of these settings, I'll have to be vague about the values.

This environment override needs to be fixed:

* [x] ``ADMINS`` ([docs](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-ADMINS)) - a list of (name, email) pairs for administration emails. It is set to ``[('MDN devs', 'mdn-dev@mozilla.com')]`` in stage and prod.  The default override sets it to a list, which I believe will break if an email is sent. For [browsercompat](https://github.com/mdn/browsercompat/blob/e283cda792293c8d91f137d4ab2ae9856b024e07/wpcsite/settings.py#L191-L193), I split these into ``ADMIN_NAMES`` and ``ADMIN_EMAILS`` and joined them in ``settings.py``.

These environment overrides need to be added, and are OK in a non-secret file:

* [x] ``CELERYD_MAX_TASKS_PER_CHILD`` ([celery docs](http://docs.celeryproject.org/en/latest/userguide/configuration.html#worker-max-tasks-per-child) and [New Relic docs](https://docs.newrelic.com/docs/agents/python-agent/back-end-services/python-agent-celery#troubleshooting)). This setting causes the ``celeryd`` child process to terminate after running a certain number of tasks. This is set to 3000 in stage and 100 in production, and the default is ``None`` for unlimited. This was a common setting to deal with memory leaks in ``celeryd`` back in 2013 or so. I'd like to try leaving at the default of unlimited, but we may need to set it based on testing.
* [x] ``DEFAULT_AVATAR`` - ``STATIC_URL + 'img/avatar.png'`` in dev, `` MEDIA_URL + 'img/avatar.png'`` in production. Maybe. This is the external URL sent to the gravatar server.
* [x] ``DEFAULT_FROM_EMAIL`` ([docs](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-DEFAULT_FROM_EMAIL)) - email address for notifications from the server. ``notifications@developer.mozilla.org`` on prod, ``notifications@developer-dev.allizom.org`` (or similar) on stage. Alternatively, a non-mozilla.org address can be used.
* [x] ``EMAIL_BACKEND`` ([docs](https://docs.djangoproject.com/en/1.11/ref/settings/#email-backend)) - ``django.core.mail.backends.smtp.EmailBackend`` on stage and production.
* [x] ``ES_INDEX_PREFIX`` - Kuma setting. ``"mdnstage"`` on stage, ``"mdnprod"`` on prod, ``"mdn"`` on dev. Used to allow different indexes in the same ElasticSearch server, maybe not needed if we're going to use different servers per environment.
* [x] ``ES_LIVE_INDEX`` - Kuma setting. ``True`` in stage and prod, updates the index when documents change.
* [x] ``SERVER_EMAIL`` ([docs](https://docs.djangoproject.com/en/1.11/ref/settings/#server-email)) - Sender email address for error messages. ``server-error@developer-dev.allizom.org`` on stage,  ``'mdn-prod-noreply@mozilla.com`` on prod. A non-mozilla.org address can also be used, if allowed by the email provider.

These environment overrides need to be added, and should be secret:

* [x] ``EMAIL_HOST`` ([docs](https://docs.djangoproject.com/en/1.11/ref/settings/#email-host)) - same in stage and prod. This may need to change in AWS, but the SCL3 settings should work.
* [x] ``EMAIL_HOST_PASSWORD`` ([docs](https://docs.djangoproject.com/en/1.11/ref/settings/#email-host-password)) - same in stage and prod
* [x] ``EMAIL_HOST_USER`` ([docs](https://docs.djangoproject.com/en/1.11/ref/settings/#email-host-user)) - same in stage and prod

These are already handled by environment override, but may need to be set in AWS:

* [x] ``ALLOWED_HOSTS``
* [x] ``ATTACHMENT_HOST``
* [x] ``BROKER_URL``
* [x] ``CELERY_ALWAYS_EAGER`` - ``True`` in dev, should be ``False`` in production.
* [x] ``DATABASES``
* [x] ``DEBUG``
* [x] ``DOMAIN``
* [x] ``ES_URLS``
* [x] ``KUMASCRIPT_URL_TEMPLATE``
* [x] ``MEDIA_URL``
* [x] ``MEMCACHE_SERVERS``
* [x] ``PROTOCOL``
* [x] ``SENTRY_DSN`` (secret, includes credentials)
* [x] ``SITE_URL``
* [x] ``STATIC_URL``

These Django settings are legacy and can be ignored:

* ``BITLY_*``* - No longer used
* ``BROWSERID_*`` - Not used
* ``BROWSERID_CACERT_FILE`` - not used
* ``CACHES`` - Set in ``kuma/settings/common.py``, with ``MEMCACHE_SERVERS`` override
* ``CACHE_COUNT_TIMEOUT`` - Set in ``kuma/settings/common.py``, not customized
* ``CACHE_PREFIX`` - Set in ``kuma/settings/common.py``, not customized
* ``DEKIWIKI_*`` - not used
* ``DEMO_*``- Not used
* ``EMAIL_SUBJECT_PREFIX`` - Set in ``kuma/settings/common.py``, not customized
* ``ES_DISABLED`` - Not used
* ``ES_INDEXES`` -  Set in ``kuma/settings/common.py``, not customized
* ``ES_INDEXING_TIMEOUT`` -  Set in ``kuma/settings/common.py``, not customized
* ``MIGRATION_DATABASES`` - Unused
* ``PROD_DETAILS_DIR`` - Not used
* ``RECAPTCHA_*`` - Not used, or moved to constance
* ``RESPONSYS`` - not used
* ``SPHINX_*`` - Not used
* ``STATSD_*`` - Not used
* ``TEMPLATE_DEBUG`` - Moved to ``TEMPLATES``, handled

**Comment by jwhitlock** [comment]
I've updated the issue with a list of Django settings that need to be customized from the environment for parity with production and staging.

**Comment by escattone** [comment]
@jwhitlock 🎉 This is awesome, thanks so much! I started looking into this very task, but was pulled into other issues. Much appreciated!

**Comment by jwhitlock** [comment]
@escattone and I talked.  A few updates:

``DATABASES`` is unchecked because production and staging set some connection parameters, like the default encoding, that aren't in the base ``common.py`` settings. I think @escattone will try using those settings in the Docker environment, and see if they'd be good defaults, or if we need to get those into environment-controlled settings.

The current setting of ``DEFAULT_AVATAR`` appears to be working - https://mdn-mm.moz.works/en-US/profiles/dave. So we probably do not need an environment override for it.

There's other stuff that is controlled by Constance variables, which have a default in ``common.py`` and can be overridden in the database.  Some of these should continue to be Constance variables, but others may be better as environment variables from the secrets file. The solution may be setting the default value from an environment variable. Maybe. Waiting to see how annoying these are for testing and deployment.

**Comment by escattone** [comment]
I think this issue can be closed, as the following PR's addressed it fully:
-https://github.com/mozilla/kuma/pull/4424
-https://github.com/mozilla/kuma/pull/4426
-https://github.com/mozilla/kuma/pull/4427
-https://github.com/mozmeao/infra/pull/480
-https://github.com/mozmeao/infra/pull/486
-https://github.com/mozmeao/infra/pull/488

**Comment by escattone** [comment]
I missed that `kuma/settings/common.py` was already set-up to use `EMAIL_URL` as an env override rather than the separate `EMAIL_HOST`, `EMAIL_HOST_USER`, and `EMAIL_HOST_PASSWORD` used in the SCL3 prod and stage local settings files. So I changed the AWS deployment/secrets to use the single setting rather than the three separate settings. See:
- https://github.com/mozmeao/infra/pull/494
- https://github.com/mozmeao/mdn-k8s-private/pull/18

**Comment by jwhitlock** [comment]
Good catch @escattone! Sorry I lead you down the wrong path with ``EMAIL_HOST`` etc.
