### ISSUE TITLE
Add general security headers

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#482]
SCL3 sets some security headers in the Apache configuration that should be moved to Kuma:

```
Strict-Transport-Security: max-age=63072000
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
```
Some of these shouldn't be set in dev mode (``Strict-Transport-Security``, others may be OK.

**Comment by escattone** [comment]
This is almost ready to close. See:
- https://github.com/mozilla/kuma/pull/4429
- https://github.com/mozmeao/infra/pull/495

The one thing remaining is to update `KUMA_IMAGE_TAG` with a Kuma Docker image that contains the work in https://github.com/mozilla/kuma/pull/4429, and re-deploy https://mdn-mm.moz.works.

**Comment by jwhitlock** [comment]
Jenkins pipeline recovered over the weekend. I ran a scan during the MM test, and the score improved:

https://observatory.mozilla.org/analyze.html?host=mdn-mm.moz.works

At the time, HTTP Strict Transport Security was either not enabled or was set to less than 6 months.

**Comment by jwhitlock** [comment]
With the latest images deployed, the security headers are as expected.  The values for ``KUMA_SECURE_HSTS_SECONDS`` are correct for stage and production (https://github.com/mozmeao/infra/pull/495), so the score should be the same as the SCL3 servers.
