### ISSUE TITLE
MDN DNS

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#487]
We currently use the following moz.works CNAME's to map prod and stage to SCL3:
`devloper.allizom.org` -> `mdn-stage.moz.works` -> some SCL3 name
`developer.mozilla.org` -> `mdn-prod.moz.works` -> some SCL3 name

I'm proposing that we use `stage.mdn.moz.works` and `prod.mdn.moz.works` Route 53 traffic policies for weighted DNS during [this milesone](https://github.com/mozmeao/infra/milestone/12). 

DNS will look like this:

`developer.allizom.org` -> `mdn-stage.moz.works` -> `stage.mdn.moz.works` -> stage ELB
`developer.mozilla.org` -> `mdn-prod.moz.works` -> `prod.mdn.moz.works` -> prod ELB ***+ SCL3 (for testing only)***

Once our weighted test is complete against both SCL3 and AWS MM, we can remove one of the intermediary CNAMEs or traffic policy.

**Comment by metadave** [comment]
cc @jgmize @escattone @jwhitlock

**Comment by metadave** [comment]
cc @escattone @jgmize @jwhitlock

**Comment by jwhitlock** [comment]
This seems fine to me. I assume the extra layer is needed to cleanly implement weighted DNS. Is ``stage.mdn.moz.works`` so you can test the chain?

**Comment by metadave** [comment]
`stage.mdn.moz.works` is really just a nicer name for the ELB, I'm still think if I want to bother using it.

**Comment by jwhitlock** [comment]
``mdn.moz.works`` is also a nice place to hang a wildcard cert on, for post-deis demo deployments. Or are we jumping to Let's Encrypt for those?

**Comment by metadave** [comment]
We have a new ACM cert for `*.mdn.moz.works` in `us-east-1` (specifically for Cloudfront). I'm not yet sure if it's possible to use a `us-east-1` cert for ELB's or other services in `us-west-2`. However, it's easy enough to request a new wildcard cert We can explore using Let's Encrypt post migration.

**Comment by metadave** [comment]
depends on https://github.com/mozmeao/infra/issues/507

**Comment by metadave** [comment]
proposed `prod.mdn.moz.works` policy:

- v0: MDN MM testing - 100% SCL3 / 0% Portland K8s
- v1: MDN MM testing - 95% SCL3 / 5% Portland K8s
- v2: MDN MM testing - 85% SCL3 / 15% Portland K8s
- v3: MDN MM testing - 50% SCL3 / 50% Portland K8s
- v4: MDN MM testing - 0% SCL3 / 100% Portland K8s

**Comment by metadave** [comment]
`prod.mdn.moz.works` policy is in place, I'm not sure if we need the stage policy at this point.
