### ISSUE TITLE
Deploy a MM configuration for manual testing in AWS

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#497]
Deploy MM in AWS, suitable for manual testing by staff. Document the process enough that we can do it reliably. This may be expanding PR #469, or another form. The MM steps for this initial testing will be different than a month from now, and so they should be good enough to last a few weeks.

**Comment by jwhitlock** [comment]
@escattone is developing the scripts and processes for switching https://mdn-mm.moz.works/en-US/ to and from maintenance mode, and ran a test last night.

The ``celery-cam`` and ``celerybeat`` services should not run normally in maintenance mode or against a read-only database.  There were a few tracebacks related to this during the test:

* https://sentry.prod.mozaws.net/operations/mdn-stage/issues/649449/ - ``celery-cam`` not allowed to track a new task in the database
* https://sentry.prod.mozaws.net/operations/mdn-stage/issues/219457/ - ``celery-cam`` not allowed to update the task state to the database
* https://sentry.prod.mozaws.net/operations/mdn-stage/issues/219455/ - ``celery-cam`` not allowed to track a new worker state in the database
* https://sentry.prod.mozaws.net/operations/mdn-stage/issues/649450/ - ``celery-cam`` not allowed to update the worker state in the database

This issue would be fixed by disabling the ``celerybeat`` task, but there may be an AWS configuration issue with generating sitemaps:

* https://sentry.prod.mozaws.net/operations/mdn-stage/issues/649451/ - ``build-locale-sitemap`` task gets ``PermissionDenied`` error when writing to /mdn/www/sitemaps

**Comment by escattone** [comment]
This was done and tested. See https://github.com/mozmeao/infra/issues/498.
