### ISSUE TITLE
Manually test MM in AWS https://prod.mdn.moz.works

### ISSUE THREAD

**Issue by escattone** [mozmeao/infra#515]
Copied from PR #469.

Test the MM configuration on https://prod.mdn.moz.works

Here's some things to check when MDN is in maintenance mode.

This checklist uses these URLs:

* Base: https://prod.mdn.moz.works
* CDN: https://developer.cdn.mozilla.net
* Demo: https://mdn.mozillademos.org (Same as production)
* Interactive Examples: (Same as production)

# Manual Sanity Check

## Home page

Load https://prod.mdn.moz.works/en-US

* [x] Loads without errors
* [x] Has banner "MDN is currently in read-only maintenance mode. Learn more."
* [x] No login option or view profile at the top
* [x] Has entries for the Hacks Blog

## Article page

Load https://prod.mdn.moz.works/en-US/docs/Web/HTML

* [x] Loads without errors
* [x] Has banner "MDN is currently in read-only maintenance mode. Learn more."
* [x] No login option or view profile at the top

## Maintenance Mode page

Click a banner to load https://prod.mdn.moz.works/en-US/maintenance-mode

* [x] Page is the destination of the "Learn more" link in the banner
* [x] Loads without errors

# Automated Checks

Within a Kuma environment, [run the functional tests](https://kuma.readthedocs.io/en/latest/tests-ui.html), using a command like:

```
py.test --maintenance-mode tests/functional tests/redirects --base-url https://prod.mdn.moz.works --driver Chrome --driver-path /path/to/chromedriver
```

* [x] Functional tests pass

These check that disabled endpoints redirect to the maintenance page, and that
other pages are OK. It duplicates the Manual Sanity Check.

# Full Manual Tests

*Note: Many of these are candidates for headless testing*

* [x] https://mdn.mozillademos.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color - 200, sample as a stand-alone page
* [x] https://mdn.mozillademos.org/files/12984/web-font-example.png - 200, PNG of some "Hipster ipsum" text
* [x] https://prod.mdn.moz.works/@api/deki/files/3613/=hut.jpg - Redirects to https://mdn.mozillademos.org/files/2767/hut.jpg, image of a hat
* [x] https://prod.mdn.moz.works/admin/ - Redirects to MM page
* [x] https://prod.mdn.moz.works/contribute.json - 200, project info
* [x] https://prod.mdn.moz.works/diagrams/workflow/workflow.svg - 200, SVG with images
* [x] https://prod.mdn.moz.works/en-US/dashboards/macros - 200, list of macros and page counts
* [x] https://prod.mdn.moz.works/en-US/dashboards/revisions - 200, list of recent changes
* [x] https://prod.mdn.moz.works/en-US/dashboards/spam - Redirects to Maintenance Mode page
* [x] https://prod.mdn.moz.works/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Color - 200, with sample as iframe
* [x] https://prod.mdn.moz.works/en-US/docs/Learn/CSS/Styling_text/Fundamentals$toc - 200, HTML table of contents
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$children - 200, JSON list of child pages
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$compare?locale=en-US&to=1299417&from=1293895 - 200, compares revisions
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$history - 200, list of revisions
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$json - 200, JSON of page metadata
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$revision/1293895 - 200, historical revision
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$translate - Redirect to Maintenance Mode page
* [x] https://prod.mdn.moz.works/en-US/docs/all - 200, paginated list of docs
* [x] https://prod.mdn.moz.works/en-US/docs/ckeditor_config.js - 200, JavaScript
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/atom/files/ - 200, Atom feed of changed files
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/rss/all/ - 200, RSS feed of new pages
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/rss/needs-review/ - 200, RSS feed of pages needing review
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/rss/needs-review/technical - 200, RSS feed of pages needing technical review
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/rss/revisions - 200, RSS feed of changes
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/rss/tag/CSS - 200, RSS feed of pages with CSS tag
* [x] https://prod.mdn.moz.works/en-US/docs/needs-review/editorial - 200, paginated list of documents
* [x] https://prod.mdn.moz.works/en-US/docs/tag/ARIA - 200, list of documents
* [x] https://prod.mdn.moz.works/en-US/docs/tags - 200, paginated list of tags
* [x] https://prod.mdn.moz.works/en-US/docs/top-level - 200, paginated list of documents
* [x] https://prod.mdn.moz.works/en-US/docs/with-errors - 200, (empty?) paginated list of documents
* [x] https://prod.mdn.moz.works/en-US/docs/without-parent - 200, paginated list of documents
* [x] https://prod.mdn.moz.works/en-US/miel  - 500 Internal Server Error
* [x] https://prod.mdn.moz.works/en-US/profiles/sheppy - 200, Sheppy's profile
* [x] https://prod.mdn.moz.works/en-US/promote/ - 200, Promote MDN with 4 buttons
* [x] https://prod.mdn.moz.works/en-US/search - 200, Search results
* [x] https://prod.mdn.moz.works/fellowship/ - 200, 2015 MDN Fellowship Program
* [x] https://prod.mdn.moz.works/files/12984/web-font-example.png - Redirects to https://mdn.mozillademos.org
* [x] https://prod.mdn.moz.works/fr/docs/feeds/rss/l10n-updates/ - 200, RSS feed of out-of-date pages
* [x] https://prod.mdn.moz.works/fr/docs/localization-tag/inprogress - 200, paginated list of documents
* [x] https://prod.mdn.moz.works/humans.txt - 200, list of GitHub usernames
* [x] https://prod.mdn.moz.works/media/kumascript-revision.txt - 200, git commit hash for kumascript
* [x] https://prod.mdn.moz.works/media/revision.txt - 200, git commit hash for kuma
* [x] https://prod.mdn.moz.works/presentations/microsummaries/index.html - 200, 2006 OSCON presentation
* [x] https://prod.mdn.moz.works/robots.txt - 200, robots disallow list
* [x] https://prod.mdn.moz.works/samples/webgl/sample3 - 200, Shows WebGL demo
* [x] https://prod.mdn.moz.works/sitemap.xml - 200, list of sitemaps
* [x] https://prod.mdn.moz.works/sitemaps/en-US/sitemap.xml - 200, list of en-US pages

**Comment by escattone** [comment]
Here's what I did for preparation:
1. [Created an admin user](https://kuma.readthedocs.io/en/latest/installation.html#create-an-admin-user).
1. Created, populated, and promoted a search index via the admin console.
1. Created and added a GitHub social app for prod.mdn.moz.works to enable GitHub login.
1. Manually created the sitemaps files (`./manage.py make_sitemaps`)
1. Manually created the humans file (`./manage.py make_humans`)

**Comment by escattone** [comment]
All manual tests passed perfectly the first time. The functional tests had intermittent failures, but they were due to inherent flaws in the tests (timing issues), so the functional tests effectively passed. The results of my functional tests runs are here:

First full run results:
```
(mdntest) rjohnson-25186:kuma rjohnson$ py.test --maintenance-mode tests/functional tests/redirects --base-url https://prod.mdn.moz.works --driver Chrome --driver-path ~/pytest-selenium/chromedriver
=============================================== test session starts ===============================================
platform darwin -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
baseurl: https://prod.mdn.moz.works
driver: Chrome
sensitiveurl: .*
rootdir: /Users/rjohnson/repos/kuma, inifile: pytest.ini
plugins: base-url-1.1.0, html-1.10.1, rerunfailures-2.1.0, selenium-1.4.0, variables-1.4, xdist-1.16.0
collected 289 items

tests/functional/test_article.py ..s..s...
tests/functional/test_article_edit.py sss
tests/functional/test_article_new.py s
tests/functional/test_article_revision.py ..
tests/functional/test_article_translate.py s
tests/functional/test_content_experiment.py sss
tests/functional/test_dashboard.py ..ss.....
tests/functional/test_feedback.py ...
tests/functional/test_home.py ..F..s..
tests/functional/test_language_selector.py .
tests/functional/test_maintenance_mode_redirects.py .................................F...............................
tests/functional/test_notfound.py ...
tests/functional/test_profiles.py .
tests/functional/test_report.py F.
tests/functional/test_robots.py .
tests/functional/test_search.py .......
tests/redirects/test_redirects.py ..........................................................................................................................................................................
============================================= short test summary info =============================================
SKIP [1] tests/functional/test_article_new.py:8: the server is in maintenance mode
SKIP [1] tests/functional/test_article_translate.py:7: the server is in maintenance mode
SKIP [1] tests/functional/test_article_edit.py:20: the server is in maintenance mode
SKIP [1] tests/functional/test_dashboard.py:51: the server is in maintenance mode
SKIP [1] tests/functional/test_article.py:65: the server is in maintenance mode
SKIP [1] tests/functional/test_dashboard.py:68: the server is in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:35: got empty parameter set ['exp_id', 'locale', 'slug'], function test_content_exp_redirect at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:35
SKIP [1] tests/functional/test_article_edit.py:9: the server is in maintenance mode
SKIP [1] tests/functional/test_article_edit.py:54: the server is in maintenance mode
SKIP [1] tests/functional/test_home.py:64: the server is in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:61: got empty parameter set ['exp_id', 'locale', 'slug', 'variant'], function test_content_exp_variant at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:61
SKIP [1] tests/functional/test_article.py:34: the server is in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:48: got empty parameter set ['exp_id', 'locale', 'slug'], function test_content_exp_logged_in at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:48

==================================================== FAILURES =====================================================
__________________________________________________ test_callouts __________________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_home.py", line 32, in test_callouts
    page = HomePage(selenium, base_url).open()
  File "/Users/rjohnson/virtualenvs/mdntest/lib/python2.7/site-packages/pypom/page.py", line 93, in open
    self.wait_for_page_to_load()
  File "/Users/rjohnson/repos/kuma/tests/pages/base.py", line 23, in wait_for_page_to_load
    self.wait.until(lambda s: el.get_attribute('data-ffo-opensans'))
  File "/Users/rjohnson/virtualenvs/mdntest/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:

------------------------------------------------- pytest-selenium -------------------------------------------------
URL: https://prod.mdn.moz.works/en-US
___________________________________ test_redirect[get-{locale}/dashboards/spam] ___________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_maintenance_mode_redirects.py", line 96, in test_redirect
    mm_page.wait_for_page_to_load()
  File "/Users/rjohnson/repos/kuma/tests/pages/base.py", line 21, in wait_for_page_to_load
    self.wait.until(lambda s: self.seed_url in s.current_url)
  File "/Users/rjohnson/virtualenvs/mdntest/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:

------------------------------------------------- pytest-selenium -------------------------------------------------
URL: https://prod.mdn.moz.works/en-US/dashboards/spam
_______________________________________________ test_report_content _______________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_report.py", line 23, in test_report_content
    assert page.header.is_report_content_url_expected(selenium, report_url)
AssertionError: assert False
 +  where False = <bound method Header.is_report_content_url_expected of <pages.base.Header object at 0x106945f50>>(<selenium.webdriver.chrome.webdriver.WebDriver (session="b2ca692758341d5e8ebc91e4f68f4593")>, 'https://prod.mdn.moz.works/en-US/docs/User:anonymous:uitest')
 +    where <bound method Header.is_report_content_url_expected of <pages.base.Header object at 0x106945f50>> = <pages.base.Header object at 0x106945f50>.is_report_content_url_expected
 +      where <pages.base.Header object at 0x106945f50> = <pages.article.ArticlePage object at 0x106945790>.header
------------------------------------------------- pytest-selenium -------------------------------------------------
URL: about:blank
=============================== 3 failed, 273 passed, 13 skipped in 410.89 seconds ================================
```

Second full run results:
```
(mdntest) rjohnson-25186:kuma rjohnson$ py.test --maintenance-mode tests/functional tests/redirects --base-url https://prod.mdn.moz.works --driver Chrome --driver-path ~/pytest-selenium/chromedriver
=============================================== test session starts ===============================================
platform darwin -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
baseurl: https://prod.mdn.moz.works
driver: Chrome
sensitiveurl: .*
rootdir: /Users/rjohnson/repos/kuma, inifile: pytest.ini
plugins: base-url-1.1.0, html-1.10.1, rerunfailures-2.1.0, selenium-1.4.0, variables-1.4, xdist-1.16.0
collected 289 items

tests/functional/test_article.py ..s..s...
tests/functional/test_article_edit.py sss
tests/functional/test_article_new.py s
tests/functional/test_article_revision.py ..
tests/functional/test_article_translate.py s
tests/functional/test_content_experiment.py sss
tests/functional/test_dashboard.py ..ss.....
tests/functional/test_feedback.py ...
tests/functional/test_home.py .....s..
tests/functional/test_language_selector.py .
tests/functional/test_maintenance_mode_redirects.py .................................................................
tests/functional/test_notfound.py ...
tests/functional/test_profiles.py .
tests/functional/test_report.py F.
tests/functional/test_robots.py .
tests/functional/test_search.py .......
tests/redirects/test_redirects.py ..........................................................................................................................................................................
============================================= short test summary info =============================================
SKIP [1] tests/functional/test_article_new.py:8: the server is in maintenance mode
SKIP [1] tests/functional/test_article_translate.py:7: the server is in maintenance mode
SKIP [1] tests/functional/test_article_edit.py:20: the server is in maintenance mode
SKIP [1] tests/functional/test_dashboard.py:51: the server is in maintenance mode
SKIP [1] tests/functional/test_article.py:65: the server is in maintenance mode
SKIP [1] tests/functional/test_dashboard.py:68: the server is in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:35: got empty parameter set ['exp_id', 'locale', 'slug'], function test_content_exp_redirect at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:35
SKIP [1] tests/functional/test_article_edit.py:9: the server is in maintenance mode
SKIP [1] tests/functional/test_article_edit.py:54: the server is in maintenance mode
SKIP [1] tests/functional/test_home.py:64: the server is in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:61: got empty parameter set ['exp_id', 'locale', 'slug', 'variant'], function test_content_exp_variant at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:61
SKIP [1] tests/functional/test_article.py:34: the server is in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:48: got empty parameter set ['exp_id', 'locale', 'slug'], function test_content_exp_logged_in at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:48

==================================================== FAILURES =====================================================
_______________________________________________ test_report_content _______________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_report.py", line 23, in test_report_content
    assert page.header.is_report_content_url_expected(selenium, report_url)
AssertionError: assert False
 +  where False = <bound method Header.is_report_content_url_expected of <pages.base.Header object at 0x10ad8b110>>(<selenium.webdriver.chrome.webdriver.WebDriver (session="1dc1b071bbcb84f26b40b544ec96d7e9")>, 'https://prod.mdn.moz.works/en-US/docs/User:anonymous:uitest')
 +    where <bound method Header.is_report_content_url_expected of <pages.base.Header object at 0x10ad8b110>> = <pages.base.Header object at 0x10ad8b110>.is_report_content_url_expected
 +      where <pages.base.Header object at 0x10ad8b110> = <pages.article.ArticlePage object at 0x10ad8bd50>.header
------------------------------------------------- pytest-selenium -------------------------------------------------
URL: about:blank
=============================== 1 failed, 275 passed, 13 skipped in 385.57 seconds ================================
```

Third partial run results for `tests/functional/test_report.py`:
```
(mdntest) rjohnson-25186:kuma rjohnson$ py.test --maintenance-mode tests/functional/test_report.py --base-url https://prod.mdn.moz.works --driver Chrome --driver-path ~/pytest-selenium/chromedriver
=============================================== test session starts ===============================================
platform darwin -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
baseurl: https://prod.mdn.moz.works
driver: Chrome
sensitiveurl: .*
rootdir: /Users/rjohnson/repos/kuma, inifile: pytest.ini
plugins: base-url-1.1.0, html-1.10.1, rerunfailures-2.1.0, selenium-1.4.0, variables-1.4, xdist-1.16.0
collected 2 items

tests/functional/test_report.py ..

============================================ 2 passed in 9.45 seconds =============================================
```

**Comment by escattone** [comment]
@jwhitlock @metadave Success! 🎉 🍾 I think we can close this issue.

**Comment by metadave** [comment]
this is amazing, thanks so much @escattone @jwhitlock!
