### ISSUE TITLE
Configure AWS staging for read/write testing

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#517]
* [x] Serve web at https://stage.mdn.moz.works
* [x] Serve in read/write mode (``MAINTENANCE_MODE=False``)
* [x] Configure GitHub login
* [x] Serve CDN at ~~https://stage-cdn.mdn.moz.works~~ https://stage-cdn.mdn.mozilla.net
* [x] Serve Demos / Attachments at https://stage-files.mdn.moz.works

**Comment by metadave** [comment]
stage cdn = `stage-cdn.mdn.mozilla.net`
I have `developer-samples.allizom.org ` listed on the stage cert to serve demos/attachments, not sure if that's correct.

**Comment by jwhitlock** [comment]
``developer-samples.allizom.org`` is the SCL3 name, but I like this new naming convention. What would be the effect of changing that to ``stage-files.mdn.moz.works``?

**Comment by metadave** [comment]
I just have to create a `stage-files.mdn.moz.works` CNAME and request a new allizom cert.

**Comment by metadave** [comment]
Cert requested

**Comment by escattone** [comment]
We're going to stay with `stage-cdn.mdn.mozilla.net` rather than moving to `stage-cdn.mdn.moz.works`?

**Comment by escattone** [comment]
Oh, it looks like they're both the same anyway.

**Comment by metadave** [comment]
`stage-cdn.mdn.mozilla.net` is a CNAME for `stage-cdn.mdn.moz.works`. We try not to let the `*.moz.works` stuff "leak out" into production services, but it's probably fine in stage. ~I might have to make a small tweak to Cloudfront if we decide to use `stage-cdn.mdn.moz.works`.~ I'm fine with either. 

These both work right now:
- https://stage-cdn.mdn.moz.works/static/img/favicon72.deefe20a0360.png
- https://stage-cdn.mdn.mozilla.net/static/img/favicon72.deefe20a0360.png

**Comment by metadave** [comment]
- `stage.mdn.moz.works` now points to the stage ELB
- `stage-files.mdn.moz.works` now points to `stage.mdn.moz.works`

There will be one more cert update for the stage ELB to get the `stage-files.mdn.moz.works` name included. For now, if you access `stage-files.mdn.moz.works`, you'll get a cert error.
Note, as I'm writing this comment, the stage K8s deployments have not yet been created, so none of these dns entries will appear to work :-)

**Comment by escattone** [comment]
This is done. I had some trouble (of my own doing) when I deleted the existing `Site` object and created a new one instead of just changing the existing one's domain name, but that's fixed now. All that's left is to wait until we can update the stage ELB with the new cert that includes `stage-files.mdn.moz.works`. See https://github.com/mozmeao/infra/blob/master/apps/mdn/mdn-aws/k8s/regions/portland/stage.mdn.moz.works.sh for the configuration of what's been deployed to staging.

**Comment by jwhitlock** [comment]
@escattone good work!

I smiled, and then I thought about having to explain this for the new few years:

![staging GitHub trust screen](https://user-images.githubusercontent.com/286017/30744562-35c26750-9f68-11e7-9267-ee546d38eb1e.png)

Let's make the staging login look more official before we create too many social accounts. I've made you an owner of the MDN org at https://github.com/mdn. Can you recreate the GitHub OAuth application credentials as the MDN org?

**Comment by escattone** [comment]
@jwhitlock Done! I recreated the GitHub OAuth application as an MDN-owned OAuth application. Thanks for adding me as an owner of the MDN org!
