### ISSUE TITLE
Evaluate Deis Workflow RDS Size

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#525]
Currently Deis workflow RDS instances in portland, frankfurt and tokyo are sized at db.m3.xlarge. Looking at stats CPU utilization for the past few weeks looks very low (2% seems the usual, never saw a spike over 5%).

Network usage also looks to be quite low.

We should validate if we can bump down the size and save some $.

**Comment by metadave** [comment]
RDS instances for Deis are have been previously downgraded to `db.t2.small`
