### ISSUE TITLE
Enable New Relic, use unique NEW_RELIC_APP_NAME for each MDN deployment

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#526]

**Comment by jwhitlock** [comment]
We currently group the web servers and celery servers under ``developer.mozilla.org``, and the kumascript servers under ``developer.mozilla.org-kumascript``.

Existing examples are:

* ``bedrock-dev-eu-west``
* ``bedrock-dev-frankfurt``
* ``bedrock-dev-tokyo``
* ``bedrock-dev-us-west``
* ``bedrock-dev-virginia``

There are 10 more, for the ``-prod-`` and ``-stage-`` variants

I'd like to use New Relic's [multiple app name feature](https://docs.newrelic.com/docs/agents/manage-apm-agents/app-naming/use-multiple-names-app) to monitor the parts together and distinctly.

* ``kuma-prod-portland`` - All the services for production
* ``kuma-web-prod-portland`` - Django serving public traffic
* ``kuma-api-prod-portland`` - Django serving KumaScript
* ``kuma-kumascript-prod-portland`` - KumaScript rendering
* ``kuma-celery-prod-portland`` Celery, ``celerycam`` and ``celerybeat``

There would be another 5 for stage. I don't think it is worth monitoring the development or demo instances.

**Comment by jwhitlock** [comment]
We use a ``newrelic.ini`` file to configure New Relic in SCL3. We should use [Environment Variables](https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-configuration#environment-variables) to configure it in SCL3.

I'm now unsure that the developer.mozilla.org app in New Relic was getting any reports from k8s for the maintenance mode tests last week...

**Comment by metadave** [comment]
@jwhitlock looking at the multiple app name feature, it notes that we are limited to 3 names per app.

**Comment by metadave** [comment]
I've added the appropriate environment vars for K8s in [this](https://github.com/mozmeao/infra/pull/542) PR.

**Comment by jwhitlock** [comment]
For Python, not everything is available from the environment, so a ``newrelic.ini`` file is needed, and the command needs to be wrapped in ``newrelic-admin run-program``. Working through the issues to get it working on ``api``, ``web``, ``celery``, etc.

Node.js has a different method, and will continue to share some config with SCL3.  I'm working through a PR and environment settings for ``kumascript``.

We definitely were not sending reports to New Relic last week.

**Comment by jwhitlock** [comment]
PR #542 is merged and running on https://prod.mdn.moz.works.  We're getting New Relic traffic for:

* [kuma-prod-portland](https://rpm.newrelic.com/accounts/1299394/applications/34419452)
* [kuma-web-prod-portland](https://rpm.newrelic.com/accounts/1299394/applications/34459612)
* [kuma-api-prod-portland](https://rpm.newrelic.com/accounts/1299394/applications/34459625)
* [kuma-celery-prod-portland](https://rpm.newrelic.com/accounts/1299394/applications/34419451)

Looking into kumascript pods, and will test in mdn-stage as well.

**Comment by jwhitlock** [comment]
After two tries (PR #547, PR #548), KumaScript is reporting:

* [kuma-kumascript-prod-portland](https://rpm.newrelic.com/accounts/1299394/applications/34476242)

**Comment by jwhitlock** [comment]
And now the stage apps:

* [kuma-stage-portland](https://rpm.newrelic.com/accounts/1299394/applications/34476932)
* [kuma-web-stage-portland](https://rpm.newrelic.com/accounts/1299394/applications/34476941)
* [kuma-api-stage-portland](https://rpm.newrelic.com/accounts/1299394/applications/34476949)
* [kuma-celery-stage-portland](https://rpm.newrelic.com/accounts/1299394/applications/34476931)
* [kuma-kumascript-stage-portland](https://rpm.newrelic.com/accounts/1299394/applications/34476937)

It looks like Python and Node.js don't like each other:

* [kuma-prod-portland](https://rpm.newrelic.com/accounts/1299394/applications/34419452)
* [kuma-prod-portland (Node.js)](https://rpm.newrelic.com/accounts/1299394/applications/34476243)
* [kuma-stage-portland](https://rpm.newrelic.com/accounts/1299394/applications/34476932)
* [kuma-stage-portland (Node.js)](https://rpm.newrelic.com/accounts/1299394/applications/34476938)

so there's no reason to roll-up KumaScript into the ``kuma-*-prod`` application.  If I can, I'm going to rename these to:

* ``kumascript-prod-portland``
* ``kumascript-stage-portland``

And, just to make things complex, if you look at ``kuma-celery-prod-portland``, there's nothing for Web transactions, only under Non-web transactions. And for ``kuma-api-prod-portland``, it populates Web transactions and not Non-web transactions. I'm considering lumping both under ``kuma-backend-prod-portland``.

**Comment by escattone** [comment]
@jwhitlock @metadave Nice work!! 🎉 👏 🍾 I like the idea of lumping `kuma-celery-prod-portland` and `kuma-api-prod-portland` into `kuma-backend-prod-portland`.

**Comment by jwhitlock** [comment]
Implemented ideas in PR #549, haven't deployed yet

**Comment by jwhitlock** [comment]
Deployed to https://stage.mdn.moz.works and https://prod.mdn.moz.works. New apps:

* [kuma-prod-portland](https://rpm.newrelic.com/accounts/1299394/applications/34419452), which includes:
  - [kuma-web-prod-portland](https://rpm.newrelic.com/accounts/1299394/applications/34459612)
  - [kuma-backend-prod-portland](https://rpm.newrelic.com/accounts/1299394/applications/34601198)
* [kumascript-prod-portland](https://rpm.newrelic.com/accounts/1299394/applications/34601198)
* [kuma-stage-portland](https://rpm.newrelic.com/accounts/1299394/applications/34476932), which includes:
   - [kuma-web-stage-portland](https://rpm.newrelic.com/accounts/1299394/applications/34476941)
   - [kuma-backend-stage-portland](https://rpm.newrelic.com/accounts/1299394/applications/34593864)
* [kumascript-stage-portland](https://rpm.newrelic.com/accounts/1299394/applications/34595609)

There's some additional filters provided by labels:
* Namespace [mdn-prod](https://rpm.newrelic.com/accounts/1299394/applications?filterBy=Namespace:mdn-prod) vs [mdn-stage](https://rpm.newrelic.com/accounts/1299394/applications?filterBy=Namespace:mdn-stage)
* Cluster [portland](https://rpm.newrelic.com/accounts/1299394/applications?filterBy=Cluster:portland) vs frankfurt (someday soon)
* Project [mdn](https://rpm.newrelic.com/accounts/1299394/applications?filterBy=Cluster:portland)

Thanks @jgmize for the initial suggestion.
