### ISSUE TITLE
[Bug 1402708] Restrict URLs for untrusted (files / samples) and CDN domains

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#529]
The domain mdn.mozillademos.org is used to serve user uploaded attachments and "live samples", served by Kuma. In SCL3, Apache is used to filter the URLs that are accepted by Kuma.  In AWS, the web deployment currently handles these requests as well, but on a different domain name. In staging, this means all the content, such as the homepage, is also available from the files / samples domain https://stage-files.mdn.moz.works.

A new deployment is needed, backed by Kuma in "files / samples" mode, so that it only replies to the required subset of endpoints. Alternatively, a Apache / nginx layer could be used to restrict URLs to the backend from the samples domain.

**Comment by jwhitlock** [comment]
Tracking as [bug 1402708](https://bugzilla.mozilla.org/show_bug.cgi?id=1402708), since I'm expecting code changes as well.

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/issues/214#issuecomment-299575411

**Comment by metadave** [comment]
I'm a 👎 for nginx and a 👍 for customized Kuma deployment, as there would be less moving parts.

**Comment by jwhitlock** [comment]
We also like the name "untrusted" for this deployment, since the purpose is to serve untrusted user attachments and live samples from a different domain, leaning on the browser content security model.

**Comment by jwhitlock** [comment]
We also need to evaluate if a similar customization is needed for the deployment behind the CDN. It should also not serve the homepage.

**Comment by escattone** [comment]
I spent the afternoon looking into this more, exploring the option of modifying the Kuma code such that an environment variable would determine which URL's would be served. It seems that we'd want to put Kuma into one of three modes: `normal` (for serving docs), `untrusted` (for serving file attachments), and `cdn` (for serving the CDN with the media and static URL's).

That seems messier than I originally thought. For example, if Kuma was placed into "untrusted" mode, it would serve the `kuma.health.urls` collection, the `kuma.attachments.urls` collection, the URL's named `wiki.raw_code_sample_file` and `wiki.code_sample` from the `kuma.wiki.urls` collection, and nothing else. In `cdn` mode, it would serve the media and static (WhiteNoise) URL's (as well as the `kuma.health.urls` collection) and nothing else. In `normal` mode, it would serve everything else. It seems that we would also need to change our tests to accommodate these modes.

We would also have to create two additional K8s services, `untrusted` and `cdn`, each backed by an ELB with the DNS name `stage-files.mdn.moz.works` pointed at the `untrusted` ELB and `stage-cdn.mdn.mozilla.net` pointed at the `cdn` ELB. We would also need three new certs, a different one for each of the `web`, `untrusted`, and `cdn` ELB's.

Does that make sense?

**Comment by metadave** [comment]
@escattone if it's too messy to do in Kuma, would the nginx solution be easier?

**Comment by jwhitlock** [comment]
I'm negative on using nginx, because we've spent six months going down the "no nginix" road, and this feels like a weak reason to go back to it. However, nginix today may be a quicker solution, and the full change could be done in Q4, but @escattone has thought most about it.

How about ``public`` or ``web``  or ``docs`` instead of ``normal``?  When we go multi-region, we may want to distinguish between servers that can be used for read/write operations and the one that is used to edit documents.  I think that's 2018 work at the earliest.

We'll eventually want ``api`` as well, but since those servers are internal, they can share configuration with the public servers.

I thought we may want ``dev`` as well, to say "serve all the endpoints, like development", but I'm still deciding if the development environment should mirror production (my preference), or if we should minimize changes for now (to get to AWS faster).  If we decide to alter development, the changes in [Kuma PR 4430](https://github.com/mozilla/kuma/pull/4430) may be needed for per-container environment variables.

**Comment by jwhitlock** [comment]
After a discussion with @metadave, @escattone, and @jgmize, @escattone is going to try another option - adding decorators to each view that filters requests to a particular domain.

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/4446

**Comment by escattone** [comment]
For now, we (@metadave, @jwhitlock, and myself) decided to only restrict endpoints for the **untrusted** domain (see https://github.com/mozilla/kuma/pull/4446#issuecomment-333620903). When using the **cdn** domain, no endpoints are restricted. Closing this issue.
