### ISSUE TITLE
Redirect http ↬ https for *.moz.works

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#541]
`curl http://snippets-prod.frankfurt.moz.works` returns 200 instead of 301 to https. 

We should either fix #540 (preferred! 🙏) or get a redirect service for moz.works.

This blocks `*-admin` apps from getting deployed on k8s.

**Comment by glogiotatidis** [comment]
@metadave @jgmize now that we move fwd with #705 what's the plan with this and #540?

**Comment by metadave** [comment]
I'm currently working on boto3 automation to create ELBs for Oregon-b that we'll use in our newer clusters. This will replace any K8s allocated ELBs, so we'll have full control of config settings.
