### ISSUE TITLE
Manual test of MM in AWS https://prod.mdn.moz.works (for second MM traffic test)

### ISSUE THREAD

**Issue by escattone** [mozmeao/infra#552]
Here's some things to check when MDN is in maintenance mode.

This checklist uses these URLs:

* Base: https://prod.mdn.moz.works
* CDN: https://developer.cdn.mozilla.net
* Demo: https://mdn.mozillademos.org

# Preparing for Maintenance Mode

* [x] Load a recent backup
* [x] Generate the search index
* [x] Generate sitemaps
* [x] Generate humans.txt
* [x] Restart web servers, etc. in Maintenance Mode

# Manual Sanity Check

## Home page

Load https://prod.mdn.moz.works/en-US

* [x] Loads without errors
* [x] Has banner "MDN is currently in read-only maintenance mode. Learn more."
* [x] No login option or view profile at the top
* [x] Has entries for the Hacks Blog

## Article page

Load https://prod.mdn.moz.works/en-US/docs/Web/HTML

* [x] Loads without errors
* [x] Has banner "MDN is currently in read-only maintenance mode. Learn more."
* [x] No login option or view profile at the top

## Maintenance Mode page

Click a banner to load https://prod.mdn.moz.works/en-US/maintenance-mode

* [x] Page is the destination of the "Learn more" link in the banner
* [x] Loads without errors

# Automated Checks

With a Kuma environment, [run the functional tests](https://kuma.readthedocs.io/en/latest/tests-ui.html), using a command like:

```
py.test --maintenance-mode tests/functional tests/redirects --base-url https://prod.mdn.moz.works --driver Chrome --driver-path /path/to/chromedriver
```

Some tests will fail the first time they are run against a server with cold caches. Some tests are flakey, and will intermittantly fail. If a test passes once in three tries, we consider it a success.

* [x] Functional tests pass

These check that disabled endpoints redirect to the maintenance page, and that other pages are OK. It duplicates the Manual Sanity Check.

# Full Manual Tests

*Note: Many of these are candidates for headless testing*

* [x] https://mdn.mozillademos.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color - 200, sample as a stand-alone page
* [x] https://mdn.mozillademos.org/files/12984/web-font-example.png - 200, PNG of some "Hipster ipsum" text
* [x] https://prod.mdn.moz.works/@api/deki/files/3613/=hut.jpg - 200, image of a hat
* [x] https://prod.mdn.moz.works/admin/ - Redirects to maintenance mode page
* [x] https://prod.mdn.moz.works/contribute.json - 200, project info
* [x] https://prod.mdn.moz.works/diagrams/workflow/workflow.svg - 200, SVG with images
* [x] https://prod.mdn.moz.works/en-US/dashboards/macros - 200, list of macros and page counts
* [x] https://prod.mdn.moz.works/en-US/dashboards/revisions - 200, list of recent changes
* [x] https://prod.mdn.moz.works/en-US/dashboards/spam - Redirects to Maintenance Mode page
* [x] https://prod.mdn.moz.works/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Color - 200, with sample as iframe
* [x] https://prod.mdn.moz.works/en-US/docs/Learn/CSS/Styling_text/Fundamentals$toc - 200, HTML table of contents
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$children - 200, JSON list of child pages
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$compare?locale=en-US&to=1299417&from=1293895 - 200, compares revisions
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$history - 200, list of revisions
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$json - 200, JSON of page metadata
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$revision/1293895 - 200, historical revision
* [x] https://prod.mdn.moz.works/en-US/docs/Web/HTML$translate - Redirect to Maintenance Mode page
* [x] https://prod.mdn.moz.works/en-US/docs/all - 200, paginated list of docs
* [x] https://prod.mdn.moz.works/en-US/docs/ckeditor_config.js - 200, JavaScript
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/atom/files/ - 200, Atom feed of changed files
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/rss/all/ - 200, RSS feed of new pages
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/rss/needs-review/ - 200, RSS feed of pages needing review
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/rss/needs-review/technical - 200, RSS feed of pages needing technical review
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/rss/revisions - 200, RSS feed of changes
* [x] https://prod.mdn.moz.works/en-US/docs/feeds/rss/tag/CSS - 200, RSS feed of pages with CSS tag
* [x] https://prod.mdn.moz.works/en-US/docs/needs-review/editorial - 200, paginated list of documents
* [x] https://prod.mdn.moz.works/en-US/docs/tag/ARIA - 200, list of documents
* [x] https://prod.mdn.moz.works/en-US/docs/tags - 200, paginated list of tags
* [x] https://prod.mdn.moz.works/en-US/docs/top-level - 200, paginated list of documents
* [x] https://prod.mdn.moz.works/en-US/docs/with-errors - 200, (empty?) paginated list of documents
* [x] https://prod.mdn.moz.works/en-US/docs/without-parent - 200, paginated list of documents
* [x] https://prod.mdn.moz.works/en-US/miel  - 500 Internal Server Error
* [x] https://prod.mdn.moz.works/en-US/profiles/sheppy - 200, Sheppy's profile
* [x] https://prod.mdn.moz.works/en-US/promote/ - 200, Promote MDN with 4 buttons
* [x] https://prod.mdn.moz.works/en-US/search - 200, Search results
* [x] https://prod.mdn.moz.works/fellowship/ - 200, 2015 MDN Fellowship Program
* [x] https://prod.mdn.moz.works/files/12984/web-font-example.png - Redirects to https://prod-files.mdn.moz.works
* [x] https://prod.mdn.moz.works/fr/docs/feeds/rss/l10n-updates/ - 200, RSS feed of out-of-date pages
* [x] https://prod.mdn.moz.works/fr/docs/localization-tag/inprogress - 200, paginated list of documents
* [x] https://prod.mdn.moz.works/humans.txt - 200, list of GitHub usernames
* [x] https://prod.mdn.moz.works/media/kumascript-revision.txt - 200, git commit hash for kumascript
* [x] https://prod.mdn.moz.works/media/revision.txt - 200, git commit hash for kuma
* [x] https://prod.mdn.moz.works/presentations/microsummaries/index.html - 200, 2006 OSCON presentation
* [x] https://prod.mdn.moz.works/robots.txt - 200, robots disallow list
* [x] https://prod.mdn.moz.works/samples/webgl/sample3 - 200, Shows WebGL demo
* [x] https://prod.mdn.moz.works/sitemap.xml - 200, list of sitemaps
* [x] https://prod.mdn.moz.works/sitemaps/en-US/sitemap.xml - 200, list of en-US pages

**Comment by escattone** [comment]
- The functional tests run but there are several flaky tests, for example:
```
(mdntest) rjohnson-25186:kuma rjohnson$ py.test --maintenance-mode tests/functional/test_report.py --base-url https://prod.mdn.moz.works --driver Chrome --driver-path ~/pytest-selenium/chromedriver
=============================================== test session starts ===============================================
platform darwin -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
baseurl: https://prod.mdn.moz.works
driver: Chrome
sensitiveurl: .*
rootdir: /Users/rjohnson/repos/kuma, inifile: pytest.ini
plugins: base-url-1.1.0, html-1.10.1, rerunfailures-2.1.0, selenium-1.4.0, variables-1.4, xdist-1.16.0
collected 2 items

tests/functional/test_report.py F.

==================================================== FAILURES =====================================================
_______________________________________________ test_report_content _______________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_report.py", line 23, in test_report_content
    assert page.header.is_report_content_url_expected(selenium, report_url)
AssertionError: assert False
 +  where False = <bound method Header.is_report_content_url_expected of <pages.base.Header object at 0x10576f5d0>>(<selenium.webdriver.chrome.webdriver.WebDriver (session="517c8e0ff58146b8cbdb234991bce93a")>, 'https://prod.mdn.moz.works/en-US/docs/User:anonymous:uitest')
 +    where <bound method Header.is_report_content_url_expected of <pages.base.Header object at 0x10576f5d0>> = <pages.base.Header object at 0x10576f5d0>.is_report_content_url_expected
 +      where <pages.base.Header object at 0x10576f5d0> = <pages.article.ArticlePage object at 0x10576f590>.header
------------------------------------------------- pytest-selenium -------------------------------------------------
URL: about:blank
======================================= 1 failed, 1 passed in 12.10 seconds =======================================
```

- I get a 504 when trying https://prod.mdn.moz.works/presentations/microsummaries/index.html

**Comment by escattone** [comment]
It seems that something is amiss with this file `/mdn/www/presentations/microsummaries/index.html` on the prod EFS volume? I've hung when trying to `cat` or `more` that file, but it seems intermittent.

**Comment by metadave** [comment]
@escattone I was able to cat the file in a loop for a few minute without issue. The only thing I can think of that may be contributing to the issue is the EFS mount target is multi-AZ. I'll do some research to ensure this isn't an issue.

https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html

**Comment by metadave** [comment]
The security group looks fine, but I won't post details in this issue.

**Comment by jwhitlock** [comment]
This works for me on the staging server - https://stage.mdn.moz.works/presentations/microsummaries/index.html . Do they share an EFS mount?

**Comment by metadave** [comment]
stage and prod efs mounts are separate.

To see the persistent voluments/persistent volume claims:

```
kubectl get pv
kubectl -n mdn-stage get pvc
kubectl -n mdn-prod get pvc
```
To see the actual mount points:
```
kubectl -n mdn-stage exec -it web-686914878-7h68r mount | grep west
kubectl -n mdn-prod exec -it web-280916567-10mwf mount | grep west
```

https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by jwhitlock** [comment]
After getting the load balancer configured to send prod.mdn.moz.works traffic to k8s, this appeared to work.  @escattone can this task be closed?

**Comment by escattone** [comment]
Yes it can! Thanks metadave.
