### ISSUE TITLE
Implement home page and 404 for untrusted domain

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#558]
The MDN 404 handler is customized for MDN: https://developer.mozilla.org/en-US/404.  It includes the MDN header and footer.

We're using the same handler for the untrusted domain, but when the 404 page is rendered, it fails, because there is no URL named ``home`` for it to reverse ([Sentry issue](https://sentry.prod.mozaws.net/operations/mdn-prod/issues/654881/)). This is becoming a common source of errors.

We need to either

1. Continue using the [MDN 404 handler](https://github.com/mozilla/kuma/blob/master/kuma/core/views.py), but configure URLs so that it will render.
2. Use a simpler 404 handler (and 403, and 500) that doesn't include the header and footer.

This may involve adding a simple home page for the untrusted domain, as requested in [bug 1402926](https://bugzilla.mozilla.org/show_bug.cgi?id=1402926).

**Comment by escattone** [comment]
Created https://bugzilla.mozilla.org/show_bug.cgi?id=1405519 to track Kuma changes in bugzilla.

**Comment by escattone** [comment]
Created https://github.com/mozilla/kuma/pull/4454 to at least partially address this issue. mozilla/kuma#4454 does not address [bug 1402926](https://bugzilla.mozilla.org/show_bug.cgi?id=1402926) (adding a new homepage for the untrusted domain).

**Comment by escattone** [comment]
We didn't implement the home page, but we do now handle 403, 404, and 500 errors for the **untrusted** domain. Closing this issue.
