### ISSUE TITLE
Merge frankfurt, tokyo, virginia snippet prod and stage buckets into us-west

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#559]
With https://github.com/mozmeao/snippets-service/pull/296 we're going to merge S3 buckets for snippets for different regions into one, to reduce infra complexity and improve caching of content.

The issue tracks the removal of

 - [x] `snippets-prod-eu-west`
 - [x] `snippets-prod-eu-west-logs`
 - [ ] `snippets-prod-frankfurt`
 - [ ] `snippets-prod-frankfurt-logs`
 - [ ] `snippets-prod-tokyo`
 - [ ] `snippets-prod-tokyo-logs`
 - [x] `snippets-prod-us-east`
 - [x] `snippets-prod-us-east-logs`
 - [x] `snippets-stage-eu-west`
 - [x] `snippets-stage-eu-west-logs`
 - [ ] `snippets-stage-frankfurt`
 - [ ] `snippets-stage-frankfurt-logs`
 - [ ] `snippets-stage-tokyo`
 - [ ] `snippets-stage-tokyo-logs`
 - [x] `snippets-prod-tokyo-backup`

and the update of [snippets infra configuration](https://github.com/mozmeao/infra/tree/master/apps/snippets) to reflect those changes.

**Comment by glogiotatidis** [comment]
@jgmize @metadave do you have any objections about making all snippets deployments use the same bucket?

**Comment by metadave** [comment]
I think it's ok.

**Comment by glogiotatidis** [comment]
The code is now in production and the buckets listed in OP are not used.

@metadave can I manually remove those or should I update the TF to do it?

**Comment by metadave** [comment]
feel free to remove the us-west/eu-west/us-east buckets manually, the others should be removed in Terraform. I created [an issue](https://github.com/mozmeao/infra/issues/567) to track that.

**Comment by glogiotatidis** [comment]
OK! I'll remove *eu-west* and *us-east*. 

Note that **all instances use us-west** now, it must not be removed.

**Comment by glogiotatidis** [comment]
3 hours later... still working on this. deleting S3 buckets can be a pain from the console since it fails with no obvious reason. cli seems to be working but slowly.

**Comment by metadave** [comment]
@glogiotatidis I had to use this Python script to delete buckets: https://github.com/mozmeao/infra/pull/531#issuecomment-332858343

**Comment by glogiotatidis** [comment]
> @glogiotatidis I had to use this Python script to delete buckets: #531 (comment), it still took a few hours for each bucket.

I'm using similar script (without the `all()` part, the say it's faster this way), I'm almost done.

**Comment by glogiotatidis** [comment]
OK done removing the `us-west` and `eu-west` buckets. Also emptied `frankfurt` and `tokyo` buckets to make deleting with TF straightforward.

Closing this one, thanks!
