### ISSUE TITLE
MDN SLA / Engage With Moc

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#560]
- [x] Write up [doc ](https://docs.google.com/document/d/1kLAR2sk6vMMY2xdiKWHFGwW4mmz7Yv6p3CrhwoqK7QQ/edit#)
- [ ] Sign off from stakeholders
- [ ] Put docs into mana
- [ ] File bug and engage with moc

**Comment by jwhitlock** [comment]
It looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1406428 is covering this work. How much is left in this task?

**Comment by bensternthal** [comment]
I am checking in the bug as from my perspective this is done.

**Comment by escattone** [comment]
Spoke with @bensternthal and this can be closed. We will next "sort escalation paths in Austin and implement them in pager duty".
