### ISSUE TITLE
snippets bucket cleanup

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#567]
Update [snippets terraform](https://github.com/mozmeao/infra/blob/master/apps/snippets/infra/multi_region/tf/snippets.tf) to remove unused buckets.

See:
https://github.com/mozmeao/infra/issues/559

**Comment by glogiotatidis** [comment]
List of buckets to be removed with tf for cross check:

 - [ ] `snippets-prod-frankfurt`
 - [ ] `snippets-prod-frankfurt-logs`
 - [ ] `snippets-prod-tokyo`
 - [ ] `snippets-prod-tokyo-logs`
 - [ ] `snippets-stage-frankfurt`
 - [ ] `snippets-stage-frankfurt-logs`
 - [ ] `snippets-stage-tokyo`
 - [ ] `snippets-stage-tokyo-logs`

**Comment by metadave** [comment]
Buckets removed per [this](https://github.com/mozmeao/infra/issues/567#issuecomment-335758842) comment.
 
`snippets-prod-tokyo` needed some manual cleanup as versioning and logging were enabled. See also https://github.com/mozmeao/infra/pull/531

```
import boto3
s3 = boto3.resource('s3')
bucket = s3.Bucket('snippets-prod-tokyo')
bucket.object_versions.all().delete()
```
