### ISSUE TITLE
Investigate issues with sending emails

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#576]
* [Sentry MDN-PROD-96](https://sentry.prod.mozaws.net/operations/mdn-prod/issues/666821/) - ``error: [Errno 110] Connection timed out`` on ``connection.open()`` in ``tidings.events._fire_task``
* [Sentry MDN-PROD-6W](https://sentry.prod.mozaws.net/operations/mdn-prod/issues/608982/) - Same error, ``kuma.users.tasks.send_welcome_email``
* [Sentry MDN-STAGE-1S](https://sentry.prod.mozaws.net/operations/mdn-stage/issues/656046/) - ``tidings.events._fire_task`` on stage.

**Comment by jwhitlock** [comment]
Running this:

```
for POD in `kubectl -n mdn-prod -o=custom-columns=NAME:.metadata.name -l app=web get pods | cut -d" " -f1 | tail +2`
do
  echo $POD
  kubectl -n mdn-prod exec -it $POD -- bash -c "echo \"from django.core import mail; conn=mail.get_connection(fail_silently=True); conn.open(); conn.close()\" | /app/manage.py shell"
done
```

Pods appear to be opening connections without issue.  I did notice that ``django-tidings`` isn't explicitly closing connections:

https://github.com/mozilla/django-tidings/blob/896212d0b0c2e31093e246c5c246b70511c4de96/tidings/events.py#L130

**Comment by jwhitlock** [comment]
I was able to reproduce the issue by repeatedly opening and closing connections in a loop in AWS.  The timeout appears to be 120 seconds or more, so setting a longer timeout is unlikely to fix the issue.

There may be a step needed with our current email provider. I do not have login credentials, so I can't see if there is a self-service option. I'll start with a webops bug.

One solution may be to restrict sending emails to a single worker. This would require creating a new deployment of one pod, that is assigned to the ``mdn-emails`` queue.  This may make it less likely to trigger connection issues.

Another solution is to switch email providers. AWS SES should work reliably.  This would be a good time to standardize on ``developer.mozilla.org`` as the sending domain, and get our SPF record correct.

Some of our emails, such as the welcome email, may be candidates for life-cycle marketing.

**Comment by metadave** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/

**Comment by jwhitlock** [comment]
Great find @metadave! For some reason, I was sure we were using 587 already, but we aren't specifying a port, so we're getting the default of 25.  We can try a different port on staging.  We may need to adjust security groups if we're blocking outbound ports.

I found these links with candidates in [bug 1086923](https://bugzilla.mozilla.org/show_bug.cgi?id=1086923):

https://support.socketlabs.com/index.php/Knowledgebase/Article/View/94
https://support.socketlabs.com/index.php/Knowledgebase/Article/View/105

**Comment by metadave** [comment]
outbound connections aren't blocked in our security groups.

**Comment by metadave** [comment]
Security groups aren't blocking outbound connections in this case.

**Comment by jwhitlock** [comment]
@metadave deployed new secrets to stage and prod, manually deployed to stage and tested. We then deployed a new image to prod (PR #581), and the timeouts have gone away 😁
