### ISSUE TITLE
Improve caching headers for file serving on MDN

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#578]
We were able to handled the "web" traffic with 6 pods with 4 workers each. We're currently serving web + file traffic with 20 pods with 8 workers each. The pod capacity needed to serve files is a lot larger.

**Comment by jwhitlock** [comment]
One option is to add some caching headers, so at least browsers will not re-download a file.

Sample file: https://mdn.mozillademos.org/files/12984/web-font-example.png

SCL3 headers:
```
HTTP/1.1 200 OK
Server: Apache
X-Backend-Server: developer4.webapp.scl3.mozilla.com
X-Backend-Server: developer4.webapp.scl3.mozilla.com
Content-Type: image/png
Strict-Transport-Security: max-age=63072000
Date: Wed, 11 Oct 2017 17:02:28 GMT
Keep-Alive: timeout=5, max=999
x-xss-protection: 1; mode=block
Accept-Ranges: bytes
x-content-type-options: nosniff
Connection: Keep-Alive
Last-Modified: Thu, 14 Apr 2016 14:45:09 GMT
X-Frame-Options: ALLOW-FROM developer.mozilla.org
X-Cache-Info: cached
Content-Length: 53845
```

In AWS:
```
HTTP/1.1 200 OK
Content-Type: image/png
Date: Wed, 11 Oct 2017 17:07:51 GMT
Last-Modified: Thu, 14 Apr 2016 14:45:09 GMT
Server: meinheld/0.6.1
strict-transport-security: max-age=63072000
Vary: Cookie
x-content-type-options: nosniff
X-Frame-Options: ALLOW-FROM developer.mozilla.org
x-xss-protection: 1; mode=block
Content-Length: 53845
Connection: keep-alive
```

**Comment by jwhitlock** [comment]
For completeness, here are the headers for https://developer.mozilla.org/files/12984/web-font-example.png.

In SCL3:

```
HTTP/1.1 301 MOVED PERMANENTLY
Content-Type: text/html; charset=utf-8
Date: Wed, 11 Oct 2017 17:19:29 GMT
Location: https://mdn.mozillademos.org/files/12984/web-font-example.png
Server: Apache
Strict-Transport-Security: max-age=63072000
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Backend-Server: developer2.webapp.scl3.mozilla.com
X-Cache-Info: caching
X-Frame-Options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```

In AWS:
```
HTTP/1.1 301 MOVED PERMANENTLY
Connection: keep-alive
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Wed, 11 Oct 2017 17:22:54 GMT
Location: https://mdn.mozillademos.org/files/12984/web-font-example.png
Server: meinheld/0.6.1
Vary: Cookie
X-Frame-Options: DENY
strict-transport-security: max-age=63072000
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```

**Comment by escattone** [comment]
Thanks so much for those results @jwhitlock!

**Comment by escattone** [comment]
Spent too much time researching why the `Vary: Cookie` header is being set, which is a problem since it can significantly limit the benefits of caching. It is added by the `django.contrib.sessions.middleware.SessionMiddleware` when `request.session.accessed` is `True`, which is the case for most requests.

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/4461

**Comment by jwhitlock** [comment]
See https://github.com/mozilla/kuma/pull/4469 for remaining endpoints.

**Comment by escattone** [comment]
@jwhitlock's mozilla/kuma#4469 was deployed to production today and eliminated the `Vary: Cookie` header from the remaining endpoints. The task remaining is to ensure that all of the untrusted domain endpoints appropriately set (or not) the `Cache-Control` header:

1. `attachments.raw_file` (e.g., https://mdn.mozillademos.org/files/12984/web-font-example.png)
    - The appropriate cache-control headers (public, 5-minute default max age that can be modified from settings) and handling (last-modified) are already applied.
1. `attachments.mindtouch_file_redirect` (e.g., https://developer.mozilla.org/@api/deki/files/2926/=AudioTest_(1).ogg)
    - The response is always a permanent redirect (to the `attachments.raw_file` endpoint). There is no need for cache-control headers since the response will always be permanently cached.
1. `wiki.code_sample`(e.g., https://mdn.mozillademos.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color):
    - The response is dynamically-rendered HTML that depends on two things: the `wiki/code-sample.html` template, and the code sample extracted from the document.
    - We can add `public` and some `max-age` to the cache-control header, but I'm not sure what the best approach (`ETag` or `Last-Modified`), if any, is in terms of handling validation.
        - It seems to me we can't use the `Last-Modified` approach unless we cheat. We'd have to use the `max` of the two dates, one for the document and one for the template, but I don't think there's a fast and reliable way to get the last-modified date of a template. We could cheat and just use the last-modified date of the document, assuming that the template will rarely change, but we'd need a way to invalidate the cache in the rare event of a template change.
        - If we use the `ETag` approach, we'd have to select a way to generate its value. We could generate a SHA1 (or other) hash of the rendered HTML and use that, but that doesn't save much (if any) since we still must perform a complete render on validation requests and we're adding the hash computation as well.
    - Maybe the best step forward is to not include a `ETag` or `Last-Modified` header for now, decide on a max-age setting for code samples, and just use `Cache-Control: public, max-age=X`.
1. `wiki.raw_code_sample_file` (e.g., `https://mdn.mozillademos.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color/files/<id>/<filename>`)
    - The response is always a temporary redirect (to the `attachments.raw_file` endpoint), so the cache-control header will be used. It seems we could either change this to a permanent redirect, or set the cache-control header to `public` with a large `max-age` (at least a month?).
@jwhitlock's mozilla/kuma#4469 was deployed to production today and eliminated the `Vary: Cookie` header from the remaining endpoints. The task remaining is to ensure that all of the untrusted domain endpoints appropriately set (or not) the `Cache-Control` header:

1. `attachments.raw_file` (e.g., https://mdn.mozillademos.org/files/12984/web-font-example.png)
    - The appropriate cache-control headers (public, 5-minute default max age that can be modified from settings) and handling (last-modified) are already applied.
1. `attachments.mindtouch_file_redirect` (e.g., https://developer.mozilla.org/@api/deki/files/2926/=AudioTest_(1).ogg)
    - The response is always a permanent redirect (to the `attachments.raw_file` endpoint). There is no need for cache-control headers since the response will always be permanently cached.
1. `wiki.code_sample`(e.g., https://mdn.mozillademos.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color):
    - The response is dynamically-rendered HTML that depends on two things: the `wiki/code-sample.html` template, and the code sample extracted from the document.
    - We can add `public` and some `max-age` to the cache-control header, but I'm not sure what the best approach (`ETag` or `Last-Modified`), if any, is in terms of handling validation.
        - It seems to me we can't use the `Last-Modified` approach unless we cheat. We'd have to use the `max` of the two dates, one for the document and one for the template, but I don't think there's a fast and reliable way to get the last-modified date of a template. We could cheat and just use the last-modified date of the document, assuming that the template will rarely change, but we'd need a way to invalidate the cache in the rare event of a template change.
        - If we use the `ETag` approach, we'd have to select a way to generate its value. We could generate a SHA1 (or other) hash of the rendered HTML and use that, but that doesn't save much (if any) since we still must perform a complete render on validation requests and we're adding the hash computation as well.
    - Maybe the best step forward is to not include a `ETag` or `Last-Modified` header for now, decide on a max-age setting for code samples, and just use `Cache-Control: public, max-age=X`.
1. `wiki.raw_code_sample_file` (e.g., `https://mdn.mozillademos.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color/files/<id>/<filename>`)
    - The response is always a temporary redirect (to the `attachments.raw_file` endpoint), so the cache-control header will be used. It seems we could either change this to a permanent redirect, or set the cache-control header to `public` with a significant `max-age` (at least 5 days?).

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/4476

**Comment by jwhitlock** [comment]
We may still tune the headers, but we've got the basics in place.
