### ISSUE TITLE
Evaluate Redis Cache sizes

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#580]
We're using big Redis instances (via ElastiCache) to get the needed network throughput for snippets. After [recent changes](https://github.com/glogiotatidis/snippets-service/commit/26866fe26d5434c6b20d98062b8ad1d5a63cb58a) in Snippets App we've reduced the use of Redis drastically.

NewRelic Graphs for [Tokyo](https://rpm.newrelic.com/accounts/1299394/applications/24982923/datastores#/overview/Redis?value=total_call_time_per_minute) [Frankfurt](https://rpm.newrelic.com/accounts/1299394/applications/30227071/datastores#/overview/Redis?value=total_call_time_per_minute) [US-West](https://rpm.newrelic.com/accounts/1299394/applications/13687987/datastores#/overview/Redis?value=total_call_time_per_minute)

This issue tracks the re-eval of the Redis cluster sizes based on the new utilization.

**Comment by metadave** [comment]
We can choose from the instance types listed here: http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/CacheNodes.SelectSize.html

Current configuration is:
us-west-2: `cache.m3.xlarge`
Frankfurt: `cache.m4.xlarge`
Tokyo: `cache.m4.xlarge`

**Comment by metadave** [comment]
Let's take a look and see where we can save some $$$.

**Comment by metadave** [comment]
let's revisit this in Q3/Q4 as part of our reserved instance planning.
