### ISSUE TITLE
Update developer.mozilla.org documentation in Mana

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#583]
The main infrastructure documentation is at https://mana.mozilla.org/wiki/display/websites/developer.mozilla.org+Cluster, and describes the SCL3 infrastructure. A new page is needed to describe the AWS infrastructure, and the Mana docs need a review.

**Comment by jwhitlock** [comment]
Closing incomplete. Tracking moved to [private bug 1434694](https://bugzilla.mozilla.org/show_bug.cgi?id=1434694)
