### ISSUE TITLE
Use production favicon.ico on MDN

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#585]
The production favicon is [a black dino on a blue background](https://cdn.mdn.mozilla.net/static/img/favicon.78cc2f51b652.ico). The local icon is [a black dino on a red background](https://cdn.mdn.mozilla.net/static/img/favicon32-local.png). In SCL3, the icon is decided based on if the request domain is the production URL (developer.mozilla.org). In AWS, the request domain appears to be different (maybe prod.mdn.moz.works?) which results in the local icon being used.

**Comment by stephaniehobson** [comment]
I am assigning the blue dino to all servers until the root of this problem can be fixed.

**Comment by metadave** [comment]
given that the value `request.META.SERVER_NAME` is checked, I'm guessing that it's no longer available in the request. Some server side debugging will help diagnose.

**Comment by jwhitlock** [comment]
Closing incomplete. Tracking has moved to [bug 1434690](https://bugzilla.mozilla.org/show_bug.cgi?id=1434690).
