### ISSUE TITLE
Make tagged document list view resilient

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#586]
Pages like https://developer.mozilla.org/en-US/docs/tag/CSS are associated with downtime due to non-compliant scrapers in SCL3. It was associated with a downtime incident on Oct 12 in AWS.

The pages can be improved in a few ways:
* Only request data needed to create the pages from the database, instead of all document data
* Move data collection to the backend, and cache for X minutes.
* Display "Refresh in a few minutes" if cache is not available

**Comment by jwhitlock** [comment]
[PR 4463](https://github.com/mozilla/kuma/pull/4463) minimizes the data returned from the database, and adds test coverage.

**Comment by jwhitlock** [comment]
https://github.com/mozilla/kuma/pull/4463 is merged and deployed. Waiting for additional alerts to prioritize follow-on work.
