### ISSUE TITLE
Call "./manage.py update_feeds" every 10 minutes

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#587]
``./manage.py update_feeds`` was called every 10 minutes in SCL3, to update the Hacks posts on the front page of MDN.  Two options:

* Create a task wrapper for the management command, and handle with ``celerybeat``
* Convert to a Kubernetes Cron Job

Kuma changes can be tracked in [bug 1238806](https://bugzilla.mozilla.org/show_bug.cgi?id=1238806).

**Comment by metadave** [comment]
"soft" +1 to the celerybeat option, it's less infra moving parts.

**Comment by jwhitlock** [comment]
Closing as incomplete. Tracking is moving to [bug 1428945](https://bugzilla.mozilla.org/show_bug.cgi?id=1428945).
