### ISSUE TITLE
Enable demo instances

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#589]
Bedrock-style, Deis-backed demo instances were added in Q1 2017. A new mechanism is needed for deploying a demo instance in Kubernetes. 

We don't anticipate needing this for Q4 2017, but may need it in Q1 2018, to demonstrate experiments for user testing.

**Comment by jwhitlock** [comment]
Closing this as incomplete. There are parts of the solution in place (such as https://github.com/mozmeao/mdn-mysql), but demo instances are not part of the current workflow. We'll pick up this work when we anticipate needing a demo instance again.
