### ISSUE TITLE
Add CDN for  attachments domain

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#590]
The attachments domain (currently mdn.mozillademos.org) serves four types of requests:

* ``/files`` like [files/12984/web-font-example.png](https://mdn.mozillademos.org/files/12984/web-font-example.png), which are user attachments. It is possible to replace a user attachment with a new file, and we can cache on the modification date.
* ``@api`` files like [@api/deki/files/3613/=hut.jpg](https://mdn.mozillademos.org/@api/deki/files/3613/=hut.jpg), which redirect to a ``/files`` endpoint. These could be cached for a long time.
* ``$samples`` like [/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color](https://mdn.mozillademos.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color), which are extracted from user-written wiki content.  The content changes when the page is updated.
* 403 (Permission Denied), 404 (Not Found), and 50x (Server Error) pages

These are good candidates for a CDN. Unlike the static assets, we would want short cache times, so that if a file is removed or updated, it will take effect quickly.  We could also use the CloudFront Invalidation API.

Cache headers for ``/files`` were improved in #578.

NOTE: notes above by @jwhitlock, my name shows as I converted it from a project card to an issue.

**Comment by jwhitlock** [comment]
We can base it off of:

* [The current prod CDN config](https://github.com/mozmeao/infra/blob/master/apps/mdn/mdn-aws/infra/mdn-cdn/mdn_cdn.tf#L24-L32)
* [Terraform settings](https://github.com/mozmeao/infra/blob/master/apps/mdn/mdn-aws/infra/mdn-cdn/cloudfront/cloudfront.tf)

Possibly relevant CloudFront docs:

* [Values that you specify when you create or update a web distribution](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html) - settings we can set
  * [Viewer Protocol Policy](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesViewerProtocolPolicy) - Redirect HTTP to HTTPS
  * [Allowed HTTP Methods](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesAllowedHTTPMethods) - GET, HEAD, OPTIONS
  * [Forward Cookies](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesForwardCookies) - I think we can not forward cookies. Will need to double-check the Kuma endpoints
  * [Query String Forwarding and Caching](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesQueryString) - I think we can pick None
 * [Error Caching Minimum TTL](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesErrorCachingMinTTL) - Something low like content, like 300 seconds.
* [Specifying how long objects stay in a CloudFront Edge Cache](http://dcs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html) - It looks like w want to set ``max-age=X`` in the ``Cache-Control`` headers, and CF **Minimum TTL** to 0 seconds, to control from the app.
 * [Requirements and Recommendations for using Amazon EC2 and other custom origins](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CustomOriginBestPractices.html) - Good tips. The k8s-provided node image [does not include NTP](https://github.com/kubernetes/kube-deploy/blob/b7474dd2050d0dceb36cfdf0966d593c1be635e6/imagebuilder/templates/1.5.yml#L116-L123).
 * [Request and response behavior for custom origins](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html) - The details, such as handling of specific HTTP headers
    * [Persistent Connections](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-persistent-connections) - CF attempts to maintain a persistent connection, which may have an impact on the number of workers needed behind CF.
    * [How CloudFront processes responses from your custom origin](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-persistent-connections) - Useful details
 * [How CloudFront processes HTPP 3xx status codes from your origin](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-3xx-status-codes.html) - caches redirects, controlled by settings and headers
 * [How CloudFront processes and caches HTTP 4xx status codes from your origin](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/HTTPStatusCodes.html) - caching, but more complicated. It is unclear if CF will return our custom 404 page, unless we add it as a standalone page. 
 * [Requiring HTTPS for communication between viewers and CloudFront](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-https-viewers-to-cloudfront.html) - Settings plus set the SSL certs.
 * [Requiring HTTPS for communication between CloudFront and Your Custom Origin](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-https-cloudfront-to-custom-origin.html) - I'm OK w/ HTTP, but existing CDN uses SSL, so why not.
 * [Using alternate domain names and HTTPS](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-https-alternate-domain-names.html) - Extra steps are needed for a domain name that isn't a subdomain of ``cloudfront.net``

**Comment by metadave** [comment]
- Changes:
    - [ ] change primary mdn cdn to use developer.mozilla.org as an origin
        - current config: cdn.mdn.mozilla.net -> cdn.mdn.moz.works CNAME
    - [ ] create a DNS entry for mdn-demos-origin.moz.works -> mdn-prod.moz.works
        - CNAME
    - [ ] request a Cloudfront cert (us-east-1):
        mdn.mozillademos.org
        - mdn-demos.moz.works not needed
        - Don't need to request a new cert
    - [ ] request a cert in portland (ELB):
        - developer.mozilla.org
        - mdn.mozillademos.org
        - mdn-demos-origin.moz.works
        - prod.mdn.moz.works
    - [ ] request a cert in frankfurt (ELB):
        - developer.mozilla.org
        - mdn.mozillademos.org
        - mdn-demos-origin.moz.works
        - prod.mdn.moz.works
    - [ ] change CDN origin to (currently a PR):
        - mdn-demos-origin.moz.works
    - [ ] change CDN aliases to:
        - mdn.mozillademos.org
        - mdn-demos.moz.works
    - [ ] change mdn-demos.moz.works to point to the Cloudfront Distribution
        - blocked by Kuma change
    - [ ] update support docs

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/pull/624

**Comment by escattone** [comment]
https://github.com/mozilla/kuma/pull/4479
https://github.com/mozmeao/infra/pull/623

**Comment by metadave** [comment]
deployed!
