### ISSUE TITLE
Implement deployment auto-scaling

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#591]
Automatically scale deployments up and down due to CPU pressure, maybe other factors:

* ``web``
* ``celery-worker``
* ``api``
* ``kumascript``

**Comment by jwhitlock** [comment]
We've used manual scaling for the rare times when it seems useful. MDN is running alone in the Kubernetes cluster, and by all appearances would be a lousy roommate. We can revisit when MDN is more stable, and there may be room to dynamically use a lower capacity.
