### ISSUE TITLE
bug 1392457: Make document list view resilient

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#596]

**Comment by jwhitlock** [comment]
Associated with downtime incident on Nov 12.

The next step is to move the processing for this view into the backend. A scraper / JS disabled browser will get a page that says "refresh in a minute to see the data". A full browser may see the same message, followed by an auto-refresh to display the data.

**Comment by jwhitlock** [comment]
Rate limiting seems to protect this view from abuse. I'm closing [bug 1392457](https://bugzilla.mozilla.org/show_bug.cgi?id=1392457), will reopen if it becomes a problem again.
