### ISSUE TITLE
Make revision dashboard resilient

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#598]
The revision dashboard at https://developer.mozilla.org/en-US/dashboards/revisions is associated with downtime due to non-compliant scrapers in SCL3. It was associated with a downtime incident on Oct 12 in AWS.

The pages can be improved in a few ways:
* Only request data needed to create the pages from the database, instead of all document data
* Move data collection to the backend, and cache for X minutes.
* Display "Refresh in a few minutes" if cache is not available

**Comment by jwhitlock** [comment]
No further downtime incidents have been associated with this endpoint. De-prioritizing this work.

**Comment by jgmize** [comment]
There was a brief downtime at approximately 2:55AM CT Sunday morning that appears to be associated with this view.

**Comment by jwhitlock** [comment]
https://github.com/mozilla/kuma/pull/4520 is deployed. The numbers look better, but the traffic is also lower, so it's unclear if we've mitigated misbehaving scrapers yet. It appears to have introduced [bug 1419419](https://bugzilla.mozilla.org/show_bug.cgi?id=1419419).

| Metric | Last 7 Days | Yesterday | Last Week |
| --- | --- | --- | --- |
| Response time | 1590 ms | 1420 ms | 2650 ms |
| Apdex | 0.77 | 0.79 | 0.75 |
| Throughput | 0.514 rpm | 0.546 rpm | 0.724 rpm |

I've added it as a key transaction for detailed monitoring, but we may need to lower the alert thresholds to ensure we aren't waking anyone up.

**Comment by jwhitlock** [comment]
The revisions dashboard does not appear to be a factor in recent incidents. [bug 1419419](https://bugzilla.mozilla.org/show_bug.cgi?id=1419419) is still open, but is priority 2 (Q2 2018)
