### ISSUE TITLE
Generate tarball backup of MDN

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#600]
The tarball mirror of MDN is advertised on the [About page](https://developer.mozilla.org/en-US/docs/MDN/About#Downloading_content).  It's new home is in S3, in [mdn-downloads.s3-us-west-2.amazonaws.com](https://mdn-downloads.s3-us-west-2.amazonaws.com/index.html).

We'll need to update Kuma to redirect to the new location - see [bug 1410931](https://bugzilla.mozilla.org/show_bug.cgi?id=1410931)

**Comment by jwhitlock** [comment]
In SCL3, the script at ``/data/bin/tarball-generate.sh`` generated the tarball:

```
#!/bin/sh

DIR=$(mktemp -d /tarball/tarball-generate.XXXXXX)

pushd $DIR > /dev/null
nice -n 15 ionice -c 3 wget -q -m -p -k -E -T 5 -t 3 -R 'mov,ogv,mp4,gz,bz2,zip,exe,download,flag*,login*,*\$history,*\$edit,*\$translate,*\$move,*\$subscribe,*\$json*,\$revision' -D developer.mozilla.org -X '*/profiles'  --reject-regex='(.*)(\$revert|$revision|search\?)(.*)' -np https://developer.mozilla.org/en-US/
nice -n 15 ionice -c 3 tar czf /tarball/developer.mozilla.org.tar.gz developer.mozilla.org
popd > /dev/null
cp /tarball/developer.mozilla.org.tar.gz /mnt/netapp/developer.mozilla.org
rm -rf $DIR
```

This could be adjusted for running in Kubernetes, or we could try a different tactic.

**Comment by metadave** [comment]
current tarball looks to be ~2.1GB, I'm wondering if we'll need to allocate an EBS volume for this to work in a pod/cronjob. 

I'm guessing that this will take about 2 days of effort to turn this into a K8s cronjob (building a docker image, setup cronjob + S3 secrets, build templating, documentation).

**Comment by jwhitlock** [comment]
2.1GB compressed, much larger uncompressed.

There would be advantages to re-using a volume between runs. I believe ``wget`` could use caching headers in the requests to see if it already has a copy of a file.  But that may add unneeded state and complexity.

**Comment by metadave** [comment]
I've had problems binding/unbinding an EBS volume multiple times when creating/deleting a pod definition. This may have to be a long-running pod with it's own crontab so it only has to bind to EBS once.

**Comment by jwhitlock** [comment]
Closing incomplete. Tracked in [bug 1410931](https://bugzilla.mozilla.org/show_bug.cgi?id=1410931)
