### ISSUE TITLE
bug 801623: Add <meta name="robots" content="noindex,nofollow"> for non-indexable domains

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#601]
MDN is available on several alternate domains:

- mdn-demos-origin.moz.works
- prod.mdn.moz.works

When served on these domains, a ``<meta name="robots" content="noindex,nofollow">`` header should be added.

**Comment by jwhitlock** [comment]
Closing incomplete. Tracking is now in [bug 801623](https://bugzilla.mozilla.org/show_bug.cgi?id=801623) and [Taiga User Story 3771](https://tree.taiga.io/project/viya-mdn-durable-team/us/3771)
