### ISSUE TITLE
Bug 1409523 - Add GZip with BREACH protection

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#611]
The ZLBs provided support for compressing HTML, etc. with GZip. This needs to be added as a Kuma middleware. See [bug 1409523](https://bugzilla.mozilla.org/show_bug.cgi?id=1409523).

The CSRF protection in Django up to 1.10 is vulnerable to [BREACH](http://breachattack.com/) attacks. We can mitigate this with:

1. denying GZip on the search page, and
2. using [django-debreach](https://pypi.python.org/pypi/django-debreach)

**Comment by Elchi3** [comment]
Related, brotli compression: https://bugzilla.mozilla.org/show_bug.cgi?id=1412891

**Comment by escattone** [comment]
See:
https://github.com/mozilla/kuma/pull/4524
https://github.com/mozilla/kuma/pull/4522

**Comment by escattone** [comment]
Closing, as this has been pushed to production. We can open a new issue for the Brotli compression.

**Comment by metadave** [comment]
awesome, @escattone, thank you!
