### ISSUE TITLE
oregon-b setup

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#615]
create a new oregon-b cluster:
  - use existing VPC
  - skip Terraform output
  - skip Deis Workflow install and k8s annotations
  - install mig/datadog/newrelic/fluentd
  - new ELBs
  - test Redis/Memcached/EFS connectivity
  - install mdn-prod secrets
  - create mdn-prod cron tasks
  - create mdn-prod services
  - create mdn-prod deployments

**Comment by jwhitlock** [comment]
Why? And why "oregon-b"?
