### ISSUE TITLE
Missing CORS headers from mozorg.cdn.mozilla.net

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#633]
I got a ping from @johngian today that `mozorg.cdn.mozilla.net` does not return CORS headers anymore, which causes mozillians.org to fail to load fonts.

I advised against hot-linking to mozorg for fonts but I thought to file this issue anyway to make sure that this is intended and planned behavior. 

/cc @pmac @jgmize

**Comment by pmac** [comment]
There are a couple of [related](https://bugzilla.mozilla.org/show_bug.cgi?id=1413597) [bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1408469). It's being worked on now. Thanks!

**Comment by pmac** [comment]
This should now be fixed. Bugs are closed.
