### ISSUE TITLE
Install latest New Relic agent for each app

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#640]
- [x] basket
- [x] bedrock
- [x] careers 
- MDN
  - [x] kuma
  - [ ] kumascript ?
- [x] nucleus
- snippets
  - [x] snippets-service
  - [ ] snippets-stats https://github.com/mozmeao/snippets-stats-proxy/issues/3
- [ ] sumo - NOTE: https://github.com/mozilla/kitsune/pull/2960#issuecomment-345620352

**Comment by metadave** [comment]
https://github.com/mozmeao/basket/pull/56
