### ISSUE TITLE
replace base image for MozMEAO projects

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#641]
Our recommendations for setting up a Dockerfile for your project are as follows:

- use the appropriate Dockerfile from [mozmeao/pythode](https://github.com/mozmeao/docker-pythode) as an example for your project

- use the `python:2.7-slim` or `python:3.6-slim` image for Python projects

The following applications need to be updated to reflect this change:

- [x] mdn
- [x] bedrock
- [x] snippets
- [x] snippets-stats
- [x] careers
- [x] basket
- [x] nucleus
- [x] cloudfront -> datadog sync
   - uses `python:2-alpine`, which is still supported (and small!)

@pmac @jgmize @glogiotatidis @jwhitlock @escattone @bensternthal

**Comment by pmac** [comment]
To clear up any confusion, the request here is to use the official python image in your `FROM` line as they're more up to date and secure. An example from bedrock is:

```docker
FROM python:2.7-slim

# from https://github.com/mozmeao/docker-pythode/blob/master/Dockerfile.footer

# Extra python env
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

# add non-priviledged user
RUN adduser --uid 1000 --disabled-password --gecos '' --no-create-home webdev

# Add apt script
COPY docker/bin/apt-install /usr/local/bin/

# end from Dockerfile.footer
```

The `apt-install` script is just a helper I wrote that does and apt update, install, and the removal of the cache to keep images small. You can [find it in the pythode repo](https://github.com/mozmeao/docker-pythode/blob/master/apt-install) if you want it. You can also use the `python:2.7-slim-stretch` if you need features from Debian Stretch (the latest stable release). This is basically just a combination of the `Dockerfile.python-2.7` and `Dockerfile.footer` from the [pythode repo](https://github.com/mozmeao/docker-pythode).

**Comment by glogiotatidis** [comment]
> snippets-stats

Snippets-stats uses python:3-onbuild

**Comment by glogiotatidis** [comment]
> snippets-stats
> 
> Snippets-stats uses python:3-onbuild

And as @pmac pointed out, according to the docker hub pages the onbuild variants are deprecated, I'll update!

**Comment by glogiotatidis** [comment]
> cloudfront -> datadog sync

Uses python:2-alpine which is supported and we agreed to keep it as is

**Comment by metadave** [comment]
Images that aren't included on the list above may be ok if they're supported and frequently updated. Just add a note here and we can all review. Thanks so much for the quick turnaround on this!

**Comment by pmac** [comment]
> Images that aren't included on the list above may be ok if they're supported and frequently updated. Just add a note here and we can all review. Thanks so much for the quick turnaround on this!

Agreed. Official images from Debian for example are fine IMHO, but we could discuss.

**Comment by escattone** [comment]
For MDN, both mozilla/kuma#4506 and mdn/kumascript#396 have been merged to master and passed the stage integration tests. I could deploy to production tomorrow, but we'll see what @jwhitlock thinks about that first.

**Comment by escattone** [comment]
The following have been deployed to production on MDN:
https://github.com/mozilla/kuma/pull/4516
https://github.com/mozilla/kuma/pull/4506
So MDN can be checked off. 🎉
