### ISSUE TITLE
updated MDN ELB cert

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#644]
must include the following domains:

- developer.mozilla.org
- mdn.mozillademos.org
- mdn-demos-origin.moz.works
- prod.mdn.moz.works
- developer.mozilla.com
- devmo.developer.mozilla.org
- mdn.mozilla.org
- developer-new.mozilla.org
- developers.mozilla.org

https://bugzilla.mozilla.org/show_bug.cgi?id=1415464

**Comment by jgmize** [comment]
Certs approved and issued: arn:aws:acm:us-west-2:236517346949:certificate/068df2ec-5165-4728-a084-149dc7658ffa

**Comment by metadave** [comment]
MDN ELB's updated in [this](https://github.com/mozmeao/infra/pull/645) PR
