### ISSUE TITLE
Redirect legacy domains

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#646]
These legacy domains should permanently redirect to developer.mozilla.org:

- developer.mozilla.com
- devmo.developer.mozilla.org
- mdn.mozilla.org
- developer-new.mozilla.org
- developers.mozilla.org

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/4589 and https://github.com/mozmeao/infra/pull/672

**Comment by escattone** [comment]
https://github.com/mozmeao/infra/pull/672 has been merged. https://github.com/mozilla/kuma/pull/4589 has been merged and pushed to stage, but not to production yet.

**Comment by metadave** [comment]
do you mean that each domain should be a CNAME, or an actual HTTP redirect?

**Comment by escattone** [comment]
Each domain should be an actual HTTP redirect.

**Comment by metadave** [comment]
I think this could just be a single K8s/nginx app (similar to the [http->https redirector](https://github.com/mozmeao/infra/tree/master/k8s/install/services/http_to_https_redirector)) that just returns a redirect to developer.mozilla.org.

**Comment by escattone** [comment]
@metadave That would work too, thanks. I already have added mozilla/kuma#4589 so I think we can just go with that for now (less infra parts). It has been pushed to stage and production.

**Comment by metadave** [comment]
OH! yes indeed, I hastily added my response before actually reading the other issues :-(
thanks @escattone!
