### ISSUE TITLE
Increase reliability of Jenkins build/push of Kuma Docker images

### ISSUE THREAD

**Issue by escattone** [mozmeao/infra#650]
On changes to the Kuma master branch, we build a new Docker image for Kuma and push it to quay.io. This build fails quite often on the `make compose-test` command because the `mysql` container, although running, is not yet able to accept connections. This in turn affects deployments because they expect to be able to pull a tagged Docker image from quay.io. Let's figure out a way to make this more reliable.

**Comment by jwhitlock** [comment]
I think the cause is MySQL containers from past runs left running, #602

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/4536

**Comment by escattone** [comment]
I'll close this for now, since mozilla/kuma#4536 has been pushed to production, but we can re-open if we find that the problem persists.

**Comment by escattone** [comment]
I'm opening this since the issue persists (see https://ci.us-west.moz.works/blue/organizations/jenkins/mdn_multibranch_pipeline/detail/master/1418/pipeline). It may be that mozilla/kuma#4536 helped, but it did not solve the issue. I'm going to try delaying the other containers until `mysql` is ready.

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/4581

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/4585

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/4587

**Comment by escattone** [comment]
See https://github.com/mdn/kumascript/pull/435

**Comment by escattone** [comment]
See mozilla/kuma#4599

**Comment by escattone** [comment]
I'm closing this issue, since I think we've addressed the reliability problems. We can re-open if they re-appear.
