### ISSUE TITLE
Upgrade ci.us-west to latest (17.10) docker engine 

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#655]
ci.us-west runs docker 1.13.1 which lacks the latest and greatest docker features. I'd like to use `COPY --from` in Kitsune to produce minimal and more secure docker images. 

Can we make this happen?

**Comment by jwhitlock** [comment]
What is ``COPY --from``?

**Comment by glogiotatidis** [comment]
`COPY --from` is a very neat dockerfile command. I's reading about multi-stage dockerfiles and figured out that I can create a docker image with all the build dependencies to process staticfiles  (for kitsune that means node, npm, bower and a gazillion node packages) and run `collectstatic`. Let's name this image `staticfiles`.

Then in another Dockerfile (or in the same if you're doing multi-stage in one dockerfile) you can do something like `COPY --from staticfiles /app/static /app/static` and it will extract the `static` directory from the `staticfiles` image and copy it to /app/static. \o/

I have something in the works but I haven't completed this work yet so some things may change.

**Comment by metadave** [comment]
cc @pmac

**Comment by pmac** [comment]
I've also been working on this for bedrock. We're blocked because the `us-west` cluster is still Deis 1 and the worry is that a newer Docker would produce incompatible images. We should be able to upgrade after the decommission of that last Deis 1 cluster.

**Comment by glogiotatidis** [comment]
I'd very much like to get this upgrade before 2018. What if we build some test images elsewhere and push them to `us-west` to check if they work?

**Comment by jwhitlock** [comment]
I've been thinking of a build vs serve workflow for Kuma development, as a work-around for the issue of file system slowness on OSX. A builder container would be in charge of mounting the host system, and a host-native file watcher would run the command to build the static assets and deploy to web containers on source asset changes. ``COPY --from`` would be a nice way to automate that when building production images.

Alternatively, there may be a way to abuse Python package creation and installation to bundle static files for production.

**Comment by glogiotatidis** [comment]
With the Deis v1 decom complete this can now move forward :bangbang:

**Comment by jgmize** [comment]
The docker engine was being held at version 1.13.1 with the following:
```
$ cat /etc/apt/preferences.d/docker-engine
Package: docker-engine
Pin: release v=1.13.1*
Pin-Priority: 1001
```
I removed the file, but I am waiting to do the apt upgrade until after the current bedrock prod push is done.  I also decommissioned the old private docker registries which were running under supervisor.

**Comment by jgmize** [comment]
Uninstalled old version and installed docker 18.03.1-ce using the instructions at https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by jgmize** [comment]
Followup PRs related to this change:

- https://github.com/mozilla/nucleus/pull/48
- https://github.com/mozilla/bedrock/pull/5664
