### ISSUE TITLE
Upgrade Elasticsearch from 2.4 to 5.6

### ISSUE THREAD

**Issue by escattone** [mozmeao/infra#666]
Elasticsearch 2.4 reaches end of life (EOL) on February 28, 2018, and since our Elastic Cloud service for MDN  is currently running 2.4, we will need to upgrade. However, the Elastic Cloud service will support version 2.4 for 6 months longer, until August 28, 2018.

This is from an email I received from Elastic:

> We highly recommend all customers to upgrade their 2.x clusters to Elasticsearch 5.6. Elasticsearch 5.6 has lots of goodness that will make your life a bit more zen and it is the perfect bridge to the new 6.0 release.
> 
> Usually, EOL means that we won’t provide support for clusters after this date. However, since this is the last version on the 2.x Elasticsearch branch, we understand that it can take time to test your application on a new major version, iron out any issues and complete the upgrade. We will therefore support Elasticsearch 2.4 clusters until August 28, 2018. If you have not upgraded your Elastic Cloud clusters by this date, Elasticsearch 2.4 will no longer be maintained and supported after this date.

**Comment by safwanrahman** [comment]
@escattone Can we update it to latest `6.x`. `elasticsearch-dsl` seems to have support of `6.x` within few days.

**Comment by jwhitlock** [comment]
Moved to https://github.com/mdn/infra/issues/8
