### ISSUE TITLE
Create s3 buckets for bedrock static database files

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#667]
I'm working on a system by which bedrock instances will use a pre-loaded sqlite database file. The update system will upload data-loaded files to s3, and the instances will download these files on a schedule to keep themselves updated. So I need 3 buckets in portland:

* bedrock-db-prod
* bedrock-db-stage
* bedrock-db-dev

The files in them will not be private, so read-only HTTP access should be global, and write access should be restricted to a key ID and Secret that you create and is unique to each of the buckets. To be clear, I need: 3 buckets and 3 credentials, one for each bucket. I think it's best to keep the creds unique to reduce the risk of a dev or demo breach (or mistake) from impacting stage or prod.

Thanks! 🍥

**Comment by metadave** [comment]
@pmac do you want S3 logging and [versioning](http://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html) enabled in these buckets?

**Comment by pmac** [comment]
I don't think we'll need versioning. I'll be naming the file uploads differently every time. There will be a consistently named JSON file, but I don't believe we'll need that versioned either. Logging does sound like a good idea.

Thanks!

**Comment by pmac** [comment]
Having a file expiration policy would probably be good though. Can it be something like 7 days after last access? We can discuss that if you want. We just won't need them to hang around for that long after they fall out of use.

**Comment by pmac** [comment]
Hmm... I'll see if I can manage the objects from the scripts then. Thanks again Dave! 💯
