### ISSUE TITLE
Update DNS for developer.mozilla.com

### ISSUE THREAD

**Issue by escattone** [mozmeao/infra#673]
The current DNS for `developer.mozilla.com` points to SCL3 which in turn permanently redirects to `developer.mozilla.org`. Hopefully, this is the last vestige of reliance on SCL3. Once https://github.com/mozilla/kuma/pull/4589 and https://github.com/mozmeao/infra/pull/672 are merged and deployed, update the DNS for `developer.mozilla.com` to be a CNAME for `developer.mozilla.org` (the Django instances in AWS will then handle the permanent redirect).

**Comment by metadave** [comment]
once we're ready, this has to be handled by the DNS folks via bugzilla.

**Comment by escattone** [comment]
mozilla/kuma#4589 and #672 have been merged and deployed to stage and production. Thanks @metadave, do you know the proper `Product` and `Component` selections I should use to file the bug? Would the `Product` be "Infrastructure & Operations" and the `Component` "Infrastructure: DNS"?

**Comment by metadave** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1423995

**Comment by escattone** [comment]
That's full service, thanks @metadave! 😄

**Comment by metadave** [comment]
The DNS change has been applied.

**Comment by escattone** [comment]
Thanks so much @metadave!
