### ISSUE TITLE
*.allizom.org cert has expired

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#679]
Which leaves www-dev.allizom.org, demo1.allizom.org, etc, all broken.

**Comment by metadave** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1427756

**Comment by pmac** [comment]
Does that mean that we can get that cert and use it?

/cc @alexgibson @jpetto

**Comment by glogiotatidis** [comment]
Same for snippets.allizom.org

**Comment by metadave** [comment]
@jgmize how should we proceed?

**Comment by jgmize** [comment]
My apologies, I thought this cert had already been switched to ACM with automatic renewal. I've switched the ELB in us-west-2 to a new ACM cert valid for *.allizom.org and will switch the other regions next.

**Comment by metadave** [comment]
@jgmize would you mind replacing the old ARNs with the new cert ARN in https://github.com/mozmeao/infra/tree/master/elbs ?

**Comment by jgmize** [comment]
Based on what I'm seeing in the AWS console, we only appear to be using the *.allizom.org cert in us-west-2, not the other regions. That region was provisioned manually before we started using terraform, so there isn't an entry under https://github.com/mozmeao/infra/tree/master/elbs.  I see references like https://github.com/mozmeao/infra/blob/master/elbs/frankfurt/provision.sh#L17 and https://github.com/mozmeao/infra/blob/master/elbs/tokyo/provision.sh#L17 to wildcard varfiles ignored in https://github.com/mozmeao/infra/blob/d9ca27de41884fe1742e1447f2d7e942154916a7/.gitignore#L2 but they don't appear to have been used to generate any ELBs. I also see a reference to the now expired wildcard cert for allizom.org issued by digicert in https://github.com/mozmeao/infra/blob/d9ca27de41884fe1742e1447f2d7e942154916a7/elbs/frankfurt/provision.sh#L63 but the ELB is not using that cert; it's using a different ACM cert valid for *.frankfurt.moz.works, which looks correct to me.
