### ISSUE TITLE
Bedrock Deis issues in Frankfurt/Tokyo

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#683]

**Comment by alexgibson** [comment]
Some extra info here:

- We're seeing frequent (almost 100% in prod) headless test failures in our CI for both Tokyo and Frankfurt stage and prod instances. An example of such a failure can be seen at the following link [1] 
- These issues started somewhere between the 17th and 21st November 2017, and before then things we're passing pretty reliably. 
- We're not seeing the same issue with either tokyo-dev or frankfurt-dev.
- Things don't seem to be deployment related, as I can see the same failures when running headless tests on my local machine, independent of a deploy.
- On bedrock, we've tried reducing the number of headless tests we're running against frankfurt and tokyo considerably, to try and ease the issues. This hasn't worked unfortunately, and tests are still failing even with a relatively small load of parallel tests [2]

[1] https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/frankfurt-prod/18/pipeline
[2] https://github.com/mozilla/bedrock/blob/master/tests/functional/test_generated_pages.py

**Comment by jgmize** [comment]
> [...] I can see the same failures when running headless tests on my local machine, independent of a deploy.

Are you running the tests against a local dev instance or against a remote deployment? Which URL(s), specifically?

**Comment by alexgibson** [comment]
> Are you running the tests against a local dev instance or against a remote deployment? Which URL(s), specifically?

Running the test locally against frantfurt/tokyo prod. The tests are linked above

**Comment by alexgibson** [comment]
Here's a gist: https://gist.github.com/alexgibson/9b98c5aa0d5adbb8c27dde7b6723fd0e

**Comment by jgmize** [comment]
While we don't have a solution yet, @metadave and I worked on this yesterday, @pmac and I worked on this today, and @pmac and I will  be working more on this tomorrow.  In the mean time, I will follow up with a yaml export of the current deployments from tokyo and frankfurt

**Comment by jgmize** [comment]
Closing out old issue that was resolved months ago.
