### ISSUE TITLE
migrate openwebdevice to Netlify or S3/Cloudfront or github pages

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#698]
https://github.com/mozmeao/infra/issues/705

**Comment by metadave** [comment]
move to Terraform/S3/Cloudfront

**Comment by jgmize** [comment]
site source is at https://github.com/mozilla/mozilla-flask-crb

**Comment by jgmize** [comment]
Moved to github pages, following the instructions in https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/
