### ISSUE TITLE
migrate snippets to Oregon-b

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#703]
- include snippets-admin
https://github.com/mozmeao/infra/issues/705

**Comment by jgmize** [comment]
- [X] snippets-stats
- [X] snippets-stage
- [X] snippets-prod
- [X] snippets-admin
- https://gist.github.com/jgmize/c41e2bb9b2f6a74b084b9b6a59d1a3c3#snippets

**Comment by jgmize** [comment]
- [ ] add NR monitoring
- [ ] scale stage & prod clock procs up in oregon-b after scaling them down in usw

**Comment by jgmize** [comment]
- [ ] file PR adding oregon-b to snippets-service deployments

**Comment by glogiotatidis** [comment]
Also after push to production `ADMIN_REDIRECT_URL` in `snippets-prod` and `snippets-admin` in all clusters needs to be updated

**Comment by glogiotatidis** [comment]
Filed a ServiceNow request to update callback urls for oidc logins

**Comment by glogiotatidis** [comment]
> Filed a ServiceNow request to update callback urls for oidc logins

done

**Comment by jgmize** [comment]
snippets-stage and snippets-prod are in oregon-b now; planning to move snippets-admin and snippets-stats in a few hours.

**Comment by jgmize** [comment]
snippets-stats and snippets-admin are now live in oregon-b.
