### ISSUE TITLE
migrate Bedrock to Oregon-b

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#704]
https://github.com/mozmeao/infra/issues/705

**Comment by jgmize** [comment]
- [X] bedrock-dev
- [X] bedrock-stage
- [X] bedrock-prod
- [ ] ELBs
- [ ] add NR monitors
- [ ] demos
- [ ] add to traffic policies
- https://gist.github.com/jgmize/c41e2bb9b2f6a74b084b9b6a59d1a3c3#bedrock

**Comment by jgmize** [comment]
Done!
