### ISSUE TITLE
migrate careers to Oregon-B

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#708]
https://github.com/mozmeao/infra/issues/705

**Comment by glogiotatidis** [comment]
- [ ] Scale cron process up in oregon-b after completing the migration

**Comment by jgmize** [comment]
-   careers-stage already moved
-   [X] create careers-prod nodeport
    
        cd ~/src/mozilla/infra/apps/careers/k8s
        kubectl apply -f careers-prod-nodeport.yaml
-   [X] fix https redirects
    
        deis config:set SECURE_SSL_REDIRECT=True -a careers-prod
-   [ ] get cert
    -   valid for careers-prod.oregon-b.moz.works & careers.mozilla.org
-   [ ] create ELB
-   [ ] route53
    -   [ ] create healthcheck using /readiness endpoint
    -   [ ] traffic policy
-   [ ] close ticket

**Comment by jgmize** [comment]
Migration complete.
