### ISSUE TITLE
Things Found When Setting Up New Relic Alerts

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#717]
Things I found that may or may not be things to fix:

* Bedrock Ping URL Only Set For US est
* No alert policy for IRL podcast.
* Nucleus "Sugar" - Unsure if this is production app or something else.
* Nucleus Does Not Have Ping URLs Set
* Basket Ping URL Only Has Admin Us West Set
* Snippets Only Has _admin oregon b_ and _prod oregon-b_ in an alert policy
* Snippets Has No Ping URL Set
* ~~MDN Alerts Only Has Kuma-Web-Prod In alert policy~~

**Comment by jwhitlock** [comment]
``MDN Alerts`` is for the user-facing part of MDN, and only covers the web portion. Backend processes such as Celery, the rendering API, KumaScript, and staging deployments are tracked in ``MDN Dev Alerts``, so that we can avoid an on-call alert.

**Comment by glogiotatidis** [comment]
> Snippets Has No Ping URL Set

![image](https://user-images.githubusercontent.com/584352/35566399-ed9ef826-05c9-11e8-8b70-1d1c233aa921.png)


@bensternthal is this what you mean by "no ping url set"? 

We have Synthetics monitors for Snippets, I believe the ping urls are legacy https://docs.newrelic.com/docs/alerts/new-relic-alerts/managing-notification-channels/availability-monitoring-legacy
