### ISSUE TITLE
Audit sites for compatibility with HTTP and TCP ELBs

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#739]
We'll need them to be compatible with both for a time while we transition them all to HTTP. I'll check all of the sites for compatibility with both and for support of the newer Django SecurityMiddleware.

- [x] Bedrock
- [x] Basket
- [x] Nucleus
- [ ] Snippets
- [ ] Careers

**Comment by pmac** [comment]
To switch the compliant ones set:

## For HTTP ELB

```
SECURE_SSL_REDIRECT=True
HTTPS=off
```

## For TCP ELB

```
SECURE_SSL_REDIRECT=False
HTTPS=on
```

**Comment by pmac** [comment]
Snippets has the `SECURE_SSL_REDIRECT` setting and the right middleware, but not the WSGI hack to use `HTTPS=on` for the TCP ELB.

**Comment by pmac** [comment]
The above is also true for [Careers](https://github.com/mozmeao/lumbergh/blob/c41d16bbcbe10329046147b1a3babbf57b2c8ddd/careers/settings.py#L201)

**Comment by bensternthal** [comment]
@pmac anything left on this ?

**Comment by pmac** [comment]
I believe we're good on this. Thanks for checking.
