### ISSUE TITLE
request SUMO certificates

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#742]
@jgmize and I discussed the following:

#### DNS configuration:

```
support.mozilla.org 
    -> prod.sumo.moz.works (traffic policy) 
    -> [prod-oregon-a.sumo.moz.works, 
           prod-oregon-b.sumo.moz.works, 
           prod-frankfurt.sumo.moz.works]
```

```
support.allizom.org
    -> stage.sumo.moz.works (traffic policy)
    -> [stage-oregon-a.sumo.moz.works, 
           stage-oregon-b.sumo.moz.works, 
           stage-frankfurt.sumo.moz.works]
```

#### Certs we need to request:
- dev/stage:
    - *.allizom.org, *.sumo.moz.works
- prod:
    - *.sumo.moz.works, support.mozilla.org, support.mozilla.com

#### Questions:
- do we need mobile.support.mozilla.org on the prod cert?
- are there any dev subdomains on allizom.org?

**Comment by metadave** [comment]
@pmac @glogiotatidis do you have any input on the questions section above?

**Comment by glogiotatidis** [comment]
> are there any dev subdomains on allizom.org?

yes, historically we used `support-dev.allizom.org` (currently unused b/c we dropped dev during the last code freeze). I filed bug [1441553](https://bugzilla.mozilla.org/show_bug.cgi?id=1441553) to add the DNS entry. I guess we need a cert for this too?

> do we need mobile.support.mozilla.org on the prod cert?

AFAIK mobille.support.mozilla.org is not used and it doesn't serve a valid cert atm. I also checked in mozilla-central and there's no reference to this domain. I'll email the SUMO team to cross confirm the unused status. If so we don't need to migrate this.

**Comment by glogiotatidis** [comment]
> do we need mobile.support.mozilla.org on the prod cert?
> 
> AFAIK mobille.support.mozilla.org is not used and it doesn't serve a valid cert atm. I also checked in mozilla-central and there's no reference to this domain. I'll email the SUMO team to cross confirm the unused status. If so we don't need to migrate this.

mobile.support.m.o was never used in production, we can safely ignore.

**Comment by jgmize** [comment]
Cert ARNs: 
- prod
  -  support.mozilla.org, support.mozilla.com, *.sumo.moz.works
  - oregon
    - arn:aws:acm:us-west-2:236517346949:certificate/b427fcf8-4321-41ca-8fe0-57a90da17d52
  - frankfurt
    - arn:aws:acm:eu-central-1:236517346949:certificate/88ff1ddb-7a2f-4a78-85b3-cdcc0ea97124
- dev/stage
  - *.allizom.org, *.sumo.moz.works
  - oregon
    - arn:aws:acm:us-west-2:236517346949:certificate/192b6409-996e-46ac-a3d9-c78a69670dae
  - frankfurt
    - arn:aws:acm:eu-central-1:236517346949:certificate/b74e73f7-6fd7-4fea-99fa-c67e34556077
