### ISSUE TITLE
support.mozilla.org PagerDuty Setup

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#750]
- [x] Update [mana page](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=50267455)
- [ ] Create pagerduty service and escalation path.
- [x] Create application & policy in New Relic

### Implementation Notes
sumo-prod-frankfurt
sumo-prod-oregon-a
sumo-prod-oregon-b

We need ping urls for the above.

**Comment by bensternthal** [comment]
@glogiotatidis OK this is all setup except for ping monitoring.. Need your help on this one.

Can you provide the 3 (I think based on the servers setup in NR) urls we need to monitor.

**Comment by glogiotatidis** [comment]
> Can you provide the 3 (I think based on the servers setup in NR) urls we need to monitor. Additionally am I OK to set this up now or should I wait?

I've setup NewRelic Synthetics monitors for
 - SUMO (cdn global)
 - SUMO Prod Frankfurt
 - SUMO Prod Oregon A
 - SUMO Prod Oregon B

and configured them to send to Slack and Email (same as with other services). AFAIK we don't use NR APM Ping since that's deprecated. 

Is this what you need?

**Comment by bensternthal** [comment]
For the other applications we have _application policies_ set for apdex, error rate and downtime (see screenshot). When triggered these alerts hit slack and also use the pager duty api to both open an incident and close when resolved. I know this style of alert will eventually be deprecated but afaik synthetic monitors do not have this ability.

I suspect we will move this type of alerting to datadog prior to NR fully deprecating these alerts. 

All that being said I think I can just look at the URLs you have added to synthetics and add them into legacy alerts. If this is a bad idea or something I should not setup.. just let me know and I will remove.

<img width="749" alt="screen shot 2018-03-15 at 8 40 11 am" src="https://user-images.githubusercontent.com/198507/37474913-b332efbc-282e-11e8-9e1e-60221270c374.png">

**Comment by bensternthal** [comment]
@glogiotatidis  Note: I could not find a synthetics alert for **SUMO (cdn global)** - can you double check that one.

**Comment by glogiotatidis** [comment]
> All that being said I think I can just look at the URLs you have added to synthetics and add them into legacy alerts. If this is a bad idea or something I should not setup.. just let me know and I will remove.

Sounds good

> @glogiotatidis Note: I could not find a synthetics alert for SUMO (cdn global) - can you double check that one.

My bad, I meant "SUMO" 

Thanks!
