### ISSUE TITLE
Fix basket-admin NR synthetics alert

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#752]
- [X] Remove "OK" content validation
  - this stopped being the case when https://github.com/mozmeao/basket/pull/64 went into production
- [X] switch from /healthz/ to /readiness/
- [x] add alert channel
  - discuss with @pmac which channel would be appropriate

**Comment by pmac** [comment]
since this just checks the health of basket itself and not its connection to salesforce (so far) it seems appropriate for a real alert, like the #meao-alerts channel or PD.

**Comment by jgmize** [comment]
Added slack (via email) and ee mailing list alert channels.
