### ISSUE TITLE
Query www.mozilla.org CDN logs for traffic to .ics files

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#753]
The Thunderbird team has setup https://www.thunderbird.net/ to be the new host of all things Thunderbird. The Bedrock team is removing all of that content and adding a bunch of redirects to that site in https://github.com/mozilla/bedrock/pull/5477 but are going to keep the holiday calendar files on mozilla.org for a while since Thunderbird itself can't yet save new redirects when it encounters a 301 for subscribed calendars. If we do the redirects now then we'll get all the hits, send 301s, then thunderbird.net will get them all as well. These files have already been setup and are also [being hosted at thunderbird.net](https://www.thunderbird.net/en-US/calendar/holidays/), and we're being asked how much traffic we get to them now and therefore how much they can expect once these redirects do work and we put them in place. These will be requests to URLs like:

* https://www.mozilla.org/media/caldata/USHolidays.ics
* https://www.mozilla.org/projects/calendar/caldata/USHolidays.ics

Both of those URLs point to the same file, but they repesent the old and new URLs that we still support on the site (we just symlink the caldata folder from media into the other).

/cc @kewisch

**Comment by pmac** [comment]
I expect the answer to this one is similar to https://github.com/mozmeao/infra/issues/754#issuecomment-374338436 ? That seem right @metadave ?

**Comment by metadave** [comment]
@pmac yes, we can do some querying against Cloudflare logs for this.

**Comment by metadave** [comment]
```
#!/bin/bash

FIELDS="ClientCountry,ClientDeviceType,ClientIP,ClientIPClass,ClientRequestBytes,ClientRequestHost,ClientRequestMethod,ClientRequestProtocol,ClientRequestReferer,ClientRequestURI,ClientRequestUserAgent,ClientSSLCipher,ClientSSLProtocol,ClientSrcPort,OriginResponseBytes,OriginResponseHTTPExpires,OriginResponseHTTPLastModified,OriginResponseStatus,OriginResponseTime"
These are the only dates that seemed to work without the API returning "the start date is too early" or "the end date is too soon":

START_TIME="2018-03-21T00:00:00Z"
END_TIME="2018-03-26T00:00:00Z"
COUNT=100000
curl -s -H "X-Auth-Email: someone@mozilla.com" \
    -H "X-Auth-Key: some_key" \
    "https://api.cloudflare.com/client/v4/zones/some_zone/logs/received?start=${START_TIME}&end=${END_TIME}&count=${COUNT}&fields=${FIELDS}"
```
https://drive.google.com/file/d/1ZMEOH_U1YMTBCBMn99yOoFhHz4CFfyLw/view?usp=sharing
