### ISSUE TITLE
Log file analysis of googlebot behavior

### ISSUE THREAD

**Issue by rraue** [mozmeao/infra#754]
First of all, I am quite new to log file analysis and don't know much about it. Keep that in mind for my request and lets dicuss.

I would like to see a bit more of what and how googlebot and other crawlers are navigating www (and later otehr websites as well). It would tell me much more about possible issues on crawling then just having the errors in search console and bing webmastertools. 

To understand what I am searching for one case I am working on:

Google is having trouble with our language setup for a while.  Some pages show up in a differnet language then they should. In the uk searching for "firefox download" returned the serbian firefox/new/ page. We fixed the hreflang setup and several other related minor issues and still google keeps on changing the language of random pages for a while, then it works fine again, when the page is recrawled.

I suspect our redirects based on accept language being a possible cause. If I would see the log files for the googlebot I could find out if the bot is hitting on uk is redirected to rs and if thats not the case short before it works again. 

It still will be hard to find, as I cant define any patetrn right now, but I guess thats the only way to find out if this is caused by Googlebot crawling wth differnet accept languages. 

I am not sure if we need to collect all log file date or if we could just cut out the googlebot to not collect too much userdata, but maybe somebody has a good idea how to get me what I need.

A plus would be to find a way to do this constantly but just with the googlebot data, so I can digg into this data always we have a problem with crawling or other weird results in the search results.

**Comment by pmac** [comment]
I believe we can do this via our CDN log analysis tool in AWS right @metadave ?

**Comment by metadave** [comment]
Papertrail logs can be exported to Athena for SQL querying: https://github.com/mozmeao/infra/issues/225 There would be some manual setup on our side + IAM security, I'll talk to @jgmize and see if this is possible. I'm not sure if loading logs into Athena is something that could be automated, I don't see any AWSCLI calls to setup a database on top of S3.

We can also use the [Cloudflare Logpull rest API](https://support.cloudflare.com/hc/en-us/articles/216672448-Enterprise-Log-Share-Logpull-REST-API) to scrape a chunk of data given a duration. Output is a JSON doc for each log line, so it's annoying to parse. 

Ex: 

```
#!/bin/bash
FIELDS="ClientCountry,ClientDeviceType,ClientIP,ClientIPClass,ClientRequestBytes,ClientRequestHost,ClientRequestMethod,ClientRequestProtocol,ClientRequestReferer,ClientRequestURI,ClientRequestUserAgent,ClientSSLCipher,ClientSSLProtocol,ClientSrcPort,OriginResponseBytes,OriginResponseHTTPExpires,OriginResponseHTTPLastModified,OriginResponseStatus,OriginResponseTime"
START_TIME="2018-03-15T00:00:00Z"
END_TIME="2018-03-19T00:00:00Z"
COUNT=100000
curl -s -H "X-Auth-Email: email@mozilla.com" \
    -H "X-Auth-Key: some_key_value" \
    "https://api.cloudflare.com/client/v4/zones/your_zone_id/logs/received?start=${START_TIME}&end=${END_TIME}&count=${COUNT}&fields=${FIELDS}"
```

**Comment by pmac** [comment]
I think the Cloudflare logs would be the most useful since Papertrail only captures those requests which hit our servers, the percent of which I believe is pretty small.

**Comment by metadave** [comment]
+1.

Also, I was unsure if the [fields from Cloudflare](https://support.cloudflare.com/hc/en-us/articles/216672448-Enterprise-Log-Share-Logpull-REST-API) were enough.

**Comment by jgmize** [comment]
> I suspect our redirects based on accept language being a possible cause. [...]

I share your suspicions, and I would be strongly in favor of eliminating them for reliability reasons as well.

@pmac @rraue has there been any recent discussion of alternatives to our current approach, such as replacing the redirects with index pages that link to the corresponding localized URLs progressively enhanced via js "redirects" based on navigator.languages (inspired by https://github.com/mozilla/bedrock/pull/2242/)? Are there any existing bugs or issues we should link to for such a discussion?

**Comment by jgmize** [comment]
> Papertrail logs can be exported to Athena for SQL querying: #225 There would be some manual setup on our side + IAM security, I'll talk to @jgmize and see if this is possible. I'm not sure if loading logs into Athena is something that could be automated, I don't see any AWSCLI calls to setup a database on top of S3.

As described in https://medium.com/@dnorth98/analyzing-papertrail-logs-with-aws-athena-2427d3dd14f2 the papertrail logs are being dumped into an s3 bucket on an hourly basis. 
- The relevant settings page in papertrail: https://papertrailapp.com/account/archives
- s3 bucket name: papertrail-moz-works
- [saved athena query that loads the data from s3 into the papertrail_logs table](https://us-west-2.console.aws.amazon.com/athena/home?force&region=us-west-2#query/history/e94dfa80-8441-45d1-a64c-79a4435e96cb)

> We can also use the Cloudflare Logpull rest API to scrape a chunk of data given a duration. Output is a JSON doc for each log line, so it's annoying to parse.

https://github.com/cloudflare/logshare is a library & CLI client that addresses many of these annoyances.

**Comment by jgmize** [comment]
@rraue you should have an invite to our papertrail account in your inbox.

**Comment by jgmize** [comment]
@rraue you should also have an invite to our cloudflare account granting you raw logs access, which you can use together with the logshare tool linked above.

**Comment by rraue** [comment]
Thank you so much. Not sure how to deal with that data, but will find a way. Lets wait with changes on the redirects until we know more about the missbehavior and I have to dive deeper into navigator.languages if this solves our problem. I like the solution of apple, not redirecting but showing the right version as a link on top of the pages, when the accept language doesnt fit the page. I will open a bug once I am sure the issue is not solvable in a easier way.

**Comment by pmac** [comment]
> I like the solution of apple, not redirecting but showing the right version as a link on top of the pages, when the accept language doesnt fit the page. I will open a bug once I am sure the issue is not solvable in a easier way.

You're suggesting having the locale-free URLs be English and other languages be prefixed with the locale code? I don't think that would go down well with our non-english communities.  The banner at the top is beside the point for this as it will do nothing for SEO. I would like to add it back since it's good UX, but as for google search something else is wrong.

**Comment by rraue** [comment]
The crawler not being redirected is the benefit. So basically crawler and
user always get where they landed and the banner on top is just a
suggestion based on accept language so we let know all users there if there
are their language available.

I mean most people come anyways from google and will hit their Language
version if available.

It’s not like I get to apple.com/en/ often, I usually follow links or
search and get to the de version.

**Comment by pmac** [comment]
> It’s not like I get to apple.com/en/ often, I usually follow links or search and get to the de version.

that's a 404 though. they just have the english page as the default. that would work, but would I think be less good UX wise. I'd be happy for us to investigate this as a possibility however both for SEO and UX. We'd need buy-in from the l10n team as well to make sure changing the URLs would work okay for them.

**Comment by rraue** [comment]
Haha, yes, they have no /en/, my bad. We would not need to change our urls
would be my guess. The locale-free version could and should still redirect
if a user has no cookie (are we handling the first redirect via a cookie?).
The locale-free versions are not indexed because they always redirect,
that’s fine. The problem is only if indexed pages are redirected like when
I only have fr as accept language, I hit Mozilla.org/id/Firefox/ and get
redirected to /fr/Firefox/ for example. Mozilla.org/Firefox/ could still
redirect to your accept language.

We would not change so much then. Just in locale Version exchange the
redirect with a hint that there is a version in your language available.

That would be same ux, just no directive but with an offer.

**Comment by pmac** [comment]
Ah! I see what you're saying. Your specific example should not be happening. The /id/firefox/ page works regardless of your accept-language. If we had not translated that page into "id" then it might redirect, I'd have to check. I thought it just went to the default language, but it might use accept-language. Haven't looked at that bit of the code for a while. But that could well be the source of our issues actually because if those redirects are cached then it could be returning whichever redirect was cached first as we don't turn off cache for those I'm guessing.

**Comment by pmac** [comment]
Okay, so it does do the `accept-language` header-based redirect if you go to a valid language for the site but at a page that does not have that translation. e.g. https://www.mozilla.org/ach/firefox/. If you have your `accept-language: fr` then you'll go to FR. I also see that the cache is appropriately turned off for this, so it should be working correctly. If you think this is causing problems though then we can look at doing something else.

**Comment by pmac** [comment]
I'm not sure what else we can do in this case apart from just issuing a 404 and hopefully enhance that to detect when its for an unavailable translation for an otherwise valid page and give the user those options. We could redirect to the default language always when the user tries to hit an unavailable translation, but that doesn't seem like a great UX either.

**Comment by pmac** [comment]
Oh, and to answer your question we do not use cookies in the redirection (or for much really). We just try to figure out the best translation to which to send them based on their accept-language header and the list of available languages for the particular page.

**Comment by rraue** [comment]
Yes, this is what I need to find out. I suspect googlebot getting
redirected there a lot and being confused because then the canonical
indexed and the one fetched aren’t the same anymore.

I see a lot “Googlebot chooses a different canonical” issues in Search
Console at pages where there is no other canonical but the one pointing to
itself and I can’t find any other explanation.

Thats why I want to look in the logs if googlebot is redirected a lot on
the pages listed as this issue on the day the issue was last crawled.

I will fly back home today and probably will need next week some help
analising the logs, the way Josh showed is a little to developer heavy for
my skills ;)

**Comment by jgmize** [comment]
> I will fly back home today and probably will need next week some help analising the logs, the way Josh showed is a little to developer heavy for my skills ;)

@rraue feel free to send me a calendar invite for next week

**Comment by jgmize** [comment]
@rraue and I did some looking through papertrail and we are seeing some 301s that may be causing problems. An example search: https://papertrailapp.com/groups/1644803/events?q=%2Fde%2Ffirefox%2Fnew%2F%20301%20bedrock

example result with IP addresses stripped:
```
Mar 28 08:38:24 kubernetes.var.log.containers.bedrock-prod-web-1563323990-vmpdl_bedrock-prod_bedrock-prod-web-02a7015283d0e57453f6c4015b10b549f235980cb5841c18e3574adb1432455d.log: {"log":" - - [28/Mar/2018:08:38:23 -0900] \"GET /de/firefox/new/ HTTP/1.1\" 301 0 \"https://www.mozilla.org/de/firefox/new/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36\"\n","stream":"stdout","time":"2018-03-28T15:38:23.645146968Z"}
```

Note that this is a 301 from /de/firefox/new/ which should be either a 200 or a 304.

**Comment by jgmize** [comment]
@rraue is going to file a followup bug for identifying the cause of the behavior above; the initial log analysis is complete and based on our session he has a better understanding of how to interpret the logs he has access to in the future.

**Comment by pmac** [comment]
I still don't see the problem. The 301 was to the same URL. That is odd, but could it have just been an http -> https redirection?

**Comment by jgmize** [comment]
> I still don't see the problem. The 301 was to the same URL. That is odd, but could it have just been an http -> https redirection?

1. The https://www.mozilla.org/de/firefox/new/ is the *referrer* not the location response header
  1. it's already https
  2. this appears to be at least the 2nd redirect at this url, possibly a redirect loop to itself
2. We do http->https redirects with a separate dedicated service, so bedrock should never do http->https redirects
