### ISSUE TITLE
Sort out Tokyo Reserve Instance Decom

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#771]
Sort out:

- [ ] Plan to sell tokyo reserve instances.
- [ ] Financial impact of sale and increased non RI resources in frankfurt.

**Comment by metadave** [comment]
We can't sell RDS RI's: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ri-market-general.html#ri-seller-limits

Here's [some analysis](https://docs.google.com/spreadsheets/d/10YIlN_Glz7A0i5Z9x0znlvafBRpzKVJAwBzhIUVcZGA/edit?usp=sharing).
