### ISSUE TITLE
Switch route53 healthchecks to use readiness endpoints instead of healthz

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#774]
- [x] bedrock
- [x] basket
- [x] snippets-service
  - no longer blocked by mozmeao/snippets-service#369
- [x] sumo
- [x] careers

**Comment by jgmize** [comment]
Blocked by https://github.com/mozmeao/snippets-service/issues/369 for snippets service

**Comment by metadave** [comment]
we'll need to discuss the state of bedrock-prod route53 healthchecks

**Comment by metadave** [comment]
snippets-stage isn't in the traffic policy.
