### ISSUE TITLE
MDN prod CDN go-live

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#775]
setup MDN production primary CDN using [this PR](https://github.com/mozmeao/infra/pull/726)

**Comment by metadave** [comment]
## Release plan:

- provision prod CDN
- update the `mdn-prod.moz.works.` CNAME to point at the new CDN

## Emergency rollback:

- update the `mdn-prod.moz.works.` CNAME to point at `prod.mdn.moz.works.`

---

current state:

```
dig developer.mozilla.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> developer.mozilla.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56050
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;developer.mozilla.org.		IN	A

;; ANSWER SECTION:
developer.mozilla.org.	60	IN	CNAME	mdn-prod.moz.works.
mdn-prod.moz.works.	60	IN	CNAME	prod.mdn.moz.works.
prod.mdn.moz.works.	60	IN	CNAME	a8583e1be9a3711e7b1e70287e8e34e8-2077023531.us-west-2.elb.amazonaws.com.
a8583e1be9a3711e7b1e70287e8e34e8-2077023531.us-west-2.elb.amazonaws.com. 60 IN A 34.212.89.102
a8583e1be9a3711e7b1e70287e8e34e8-2077023531.us-west-2.elb.amazonaws.com. 60 IN A 52.24.17.241
```

**Comment by metadave** [comment]
@escattone @jwhitlock let's capture any tech details here for the MDN CDN switch next week.

**Comment by escattone** [comment]
Does this make sense as a checklist?

- [x] Successful testing on stage.
- [x] Create the new primary CDN ([via this Terraform](https://github.com/mozmeao/infra/pull/726/files#diff-790cd9740f7816b0c7811190c12f0a69)) with an origin of `prod.mdn.moz.works` (`d2jhm933xpgpf7.cloudfront.net`)
- [x] Manually order the behaviors in the new primary CDN
- [ ] Make the DNS switch: `developer.mozilla.org` switched to the new primary CDN `d2jhm933xpgpf7.cloudfront.net`. At this point, the static and media files will still be served from the `cdn.mdn.mozilla.net` CDN.
- [ ] Stop using the `cdn.mdn.mozilla.net` CDN for static/media files (review, merge, and deploy https://github.com/mozmeao/infra/pull/757).
- [ ] De-commission the `cdn.mdn.mozilla.net` CDN sometime in the future.

**Comment by jwhitlock** [comment]
That sounds good to me @escattone. Do you want to update https://tree.taiga.io/project/viya-mdn-durable-team/us/3938 with the tasks? Or maybe put it back in the archive and write a new user story?

Is there a good way to determine when we can turn off ``cdn.mdn.mozilla.net``? Do we need to setup a redirector that will outlive the CloudFront CDN? We have a similar issue with http://stage-cdn.mdn.mozilla.net/ .

**Comment by jwhitlock** [comment]
Two more things.

The pitch for this CDN change is:
1. We now have HTTP/2 for the HTML *and* the assets. This may mean a faster page load from the last byte of the HTML to the final processing of all the CSS and JS.
2. Visitors in China, India, etc. will access the site faster, because they will talk to edge CDN servers rather than Oregon servers.

We should look for a way to measure these stats with today's configuration, so that we can measure again with next week's configuration. We'll have some general numbers from Google Analytics later in April, but it would be nice to have a quick measurements on Tuesday, especially if the hypothesis is wrong (see Brotli). The [HTTP/2 on MDN article](https://mozilla.github.io/meao/2017/06/26/http2/) has some good examples. @schalkneethling or @stephaniehobson may have ideas.

The second thing is that there is a chance that our IP-based rate limiting is now a really bad idea, since potentially *everyone* in India may look like they are coming from the same edge server. It would be nice to determine if this is the case on the staging CDN, and if it is, we may want to tell Worf to go into testing mode and disable the endpoint-based rate limits.

**Comment by schalkneethling** [comment]
@jwhitlock Yes so, this would now be a good time to prioritise the work on getting Webpack into Kuma and optimising our front-end pipeline to take advantage of HTTP2

In terms of some stats before and after. I will run a Sonarwhal test today and can then another one on Wednesday to see how things improve. I will also record a load via devtools today, and again on Wednesday to see how speeds improve for me out here in Africa ;)

**Comment by schalkneethling** [comment]
Here are the results from Sonarwhal:
https://sonarwhal.com/scanner/c18fe63b-e765-4009-976e-9ae01da24f3a

Here is a network graph of the landing page with cache disabled and a force refresh:

<img width="1549" alt="screen shot 2018-04-12 at 09 49 06" src="https://user-images.githubusercontent.com/10350960/38663375-e80d28ce-3e36-11e8-80f4-d1a0daa92398.png">

And a plain refresh after the above load with caching enabled

<img width="1553" alt="screen shot 2018-04-12 at 09 49 30" src="https://user-images.githubusercontent.com/10350960/38663461-1e4c699a-3e37-11e8-8be7-36d427c943d6.png">

**Comment by stephaniehobson** [comment]
https://tools.pingdom.com/ and http://www.webpagetest.org/ will both let you run tests from different places around the world. That increases their chances of spotting the HTTP2 improvements. 

When we made the last switch to HTTP2 I found the results fluctuated a lot from test to test even with the same tool. I did not discover that until after we'd flicked the switch. If I had it to do over I'd do multiple tests with the same tool and take an average.

More HTTP2 thoughts:
- The debug mode of the site does not bundle all the CSS and JS assets, which means something somewhere is able to print the individual files to the page right now. I suspect there is a function somewhere where one could change a parameter or two and get unbundled files in production.

Excited to see HTTP2 work progressing! Perf improvements have really clear user benefits and were on my wishlist for a long time :)

**Comment by escattone** [comment]
@jwhitlock I updated the status of the Taiga tasks for user-story 4496, added tasks to user-story 3938, and added user story 3938 to the sprint.

Good question about when we can turn off `cdn.mdn.mozilla.net`. I'm not sure either.

**Comment by jwhitlock** [comment]
I've started a spreadsheet to collect these metrics:

https://docs.google.com/spreadsheets/d/1-6NJb3WB7yGrBy_VbrU09wnKqtSwe4DpGbBq_Wj4kLY/edit#gid=1366588612

I'm not sure about the webpagetest numbers - many of the servers appear to be hosted in EC2, and I'd expect the requests from one Amazon server to another to be very fast. It is also possible that our caching headers are having some effect. Still, let's be surprised after the CDN ships.

I still have Pingdom metrics to add. Kadir has a contact at Mozilla that has been running Pingdom against  MDN for a while, so maybe we can get some numbers from early February, before the caching headers started to change.

**Comment by jwhitlock** [comment]
I think the turn-off-CDN strategy would be:

* Add the asset CDN domain as a CNAME on the now primary CDN
* Add the asset CDN domain to ``ALLOWED_HOSTS`` (so request will be served) and ``LEGACY_HOSTS`` (so the response will be redirected to the primary CDN)
* Switch DNS for the asset CDN to the primary CDN. I think this automatically works for Kuma (https://developer.allizom.org/static/build/js/selectivizr.091e18cf669b.js is the same asset as https://stage-cdn.mdn.mozilla.net/static/build/js/selectivizr.091e18cf669b.js)
* Watch usage stats in AWS for the assets CDN to go toward zero
* Delete the assets CDN
* Enjoy a beverage

An alternate service:

**Comment by escattone** [comment]
@jwhitlock 👍 I like your turn-off-CDN strategy, nice plan. I'm going to add `cdn.mdn.mozilla.net` to the `LEGACY_HOSTS` in https://github.com/mozmeao/infra/pull/757, and then when we merge/deploy that PR (which makes the switch away from the asset CDN to the primary CDN), we'll be ready to make the DNS switch that points `cdn.mdn.mozilla.net` to the primary CDN.

**Comment by metadave** [comment]
The following CNAME's need to be added to the prod Cloudfront distribution:

- mdn.mozillademos.org
- ~prod.mdn.moz.works~
- mdn-demos-origin.moz.works
- developer.mozilla.com
- devmo.developer.mozilla.org
- mdn.mozilla.org
- developer-new.mozilla.org
- developers.mozilla.org

**Comment by metadave** [comment]
See also: [multiple MDN CNAME changes for legacy domains](https://bugzilla.mozilla.org/show_bug.cgi?id=1454729)

**Comment by jwhitlock** [comment]
There's a few remaining AWS tasks:

* Zone URLs like https://developer.mozilla.org/en-US/Firefox/Releases/60 can't be edited. @escattone has made the changes for staging and tested it, and we'll ship the changes for production today.
* The assets CDN cdn.mdn.mozilla.net needs to be converted to a legacy domain like developer.mozilla.com. If possible, the first step is to change cdn.mdn.mozilla.net DNS to be a cname for the production ELB, so the request is handled directly by Kuma. When the CDN traffic heads to zero, we can delete it.

There are further dev-only tasks (gather Google Analytics page timing data after a week), but I think we can close this task when these first two are complete.

**Comment by metadave** [comment]
can this issue be closed and new issues be opened for the remaining tasks?

**Comment by escattone** [comment]
Yes, thanks for the reminder @metadave! The remaining AWS tasks noted above have been completed and pushed to production. See https://github.com/mozmeao/infra/pull/794 and https://github.com/mozmeao/infra/pull/819.
