### ISSUE TITLE
GCP evaluation and writeup

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#778]
https://github.com/mozmeao/infra/issues/847
https://github.com/mozilla/bedrock/issues/5762

**Comment by jgmize** [comment]
Current status:
- Initial GKE cluster deployed running 1.9.2
- Experimented with deploying Deis Workflow in the interests of getting bedrock up and running ASAP, but ran into errors during helm install and decided to try to get an initial version of git-sync-operator deployed instead: mozmeao/git-sync-operator#1
- Began GKE-specific ingress eval: https://github.com/mozmeao/infra/issues/187#issuecomment-385730058

**Comment by metadave** [comment]
eval doc wip: https://docs.google.com/document/d/1YgGvnuKqpIuF9MgDvnCM49l662CqfKcmr5-JKAYoENw/edit?usp=sharing

**Comment by metadave** [comment]
TODO:
- cost writup
- performance comparison

**Comment by metadave** [comment]
followup issues:

https://github.com/mozmeao/infra/issues/864
https://github.com/mozmeao/infra/issues/863
