### ISSUE TITLE
SUMO production issue postmortem writeup April 12 2018

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#779]
- include Apr 5 issue

**Comment by metadave** [comment]
WIP doc [here](https://docs.google.com/document/d/1ckrcI8k0372WyjaEqfoMsfWNbu4J8AgHL-5Pr3YgbT0/edit?usp=sharing)

**Comment by metadave** [comment]
let's post this to mana

**Comment by jgmize** [comment]
Added to https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=52265112
