### ISSUE TITLE
Decom unused MDN CDNs

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#781]
- once the [primary CDN is in prod](https://github.com/mozmeao/infra/issues/775), identify CDN's to decom and remove from Terraform.

- See also https://github.com/mozmeao/infra/pull/757

**Comment by jwhitlock** [comment]
A DNS change and/or bouncer service may be needed as well, to point the old CDN domains to the production domains.

**Comment by metadave** [comment]
cc @jgmize

**Comment by jwhitlock** [comment]
CDNs that are in use:

* ``d2qvj2imcvj3x`` - developer.allizom.org
* ``d2jhm933xpgpf7`` - developer.mozilla.org
* ``d12hez81brmsmv`` - mdn.mozillademos.org (via mdn-demo.moz.works, different configuration)

I don't see any of the asset CDNs in the list, which was the main task on this issue.
