### ISSUE TITLE
experiment with wsgiworkers for SUMO

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#782]
- 4 wsgiworkers per pod
- 25 pods
- try Oregon-A first, observe performance
- followup with Oregon-B, observe performance

**Comment by pmac** [comment]
I do wish we could get some info on how many processes on average are busy for a pod. That info would allow us to tweak this in a much more informed way IMHO. Without that however, what I was suggesting is that we seem to be on the very low-end of recommendations of workers. The typical for async workers seems to be at least `NUM_PROCS * 2 +1`, but can be higher for I/O bound services, which kitsune certainly is. My suggestion is based on my feeling that gunicorn will do a good job of managing resources with these procs, and that if it does max out then k8s could kill the pod exacerbating load issues we may be having.

**Comment by metadave** [comment]
I'm +1 on bumping WSGI_NUM_WORKERS to 6, as long as we don't hit any pod mem/cpu limits.
