### ISSUE TITLE
Move To New Relic Alerts By May 10th (EOL May 15th)

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#789]
We need to transition to the _new_ new relic alerts by May 15th.

https://docs.newrelic.com/docs/alerts/new-relic-alerts/getting-started/transition-legacy-alerting-new-relic-alerts

**Comment by jgmize** [comment]
- [ ] pull existing legacy alert policies via [legacy API](https://docs.newrelic.com/docs/alerts/rest-api-alerts/legacy-alerts-rest-api)
- [ ] create new alert policies
   - will evaluate using [newrelic-cli](https://github.com/NativeInstruments/newrelic-cli) vs web UI
- switching to new alerts may require coordination with IT as we manage a sub-account and the transition is for the entire account

**Comment by metadave** [comment]
policies for Basket, Bedrock, Careers, Nucleus, Snippets and SUMO have been created in alerts.newrelic.com.

report tool: https://github.com/mozmeao/infra/pull/818

**Comment by escattone** [comment]
Thanks so much @metadave! I would be happy to create a separate Slack channel for alerts, but let's see what @jwhitlock thinks.

**Comment by jwhitlock** [comment]
Thanks, we do need a new Slack channel for MDN alerts. I'm trying to get MDN off the MozMEAO New Relic account and onto the Moz Emerging Tech account. That will involve updating the New Relic API key in our deployment secrets, and recreating the alerts in that account.

**Comment by metadave** [comment]
the new alerts have been enabled.

**Comment by metadave** [comment]
@escattone @jwhitlock I'm happy to help (re)configure any MDN alerts.
