### ISSUE TITLE
Sort Snippets CDN Costs

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#791]
IT reported massive increase in snippet CDN costs. Looks like we went from bundling 4 snippets to 150 snippets so cost has increased ~25x.

- [x] Confirm if this is the new normal.
- [x] Communicate to stakeholders costs and need for more budget.
- [x] Based on above request $ to cover IT chargeback and future cost.

**Comment by metadave** [comment]
review on or after May 15th

**Comment by bensternthal** [comment]
We look stable. No further action needed at this time.

![screen shot 2018-05-16 at 12 46 10 pm](https://user-images.githubusercontent.com/198507/40140351-9019c438-5907-11e8-9838-cc29a5a1d6d5.png)
