### ISSUE TITLE
Decom us-west Deis 1 cluster

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#804]

**Comment by jgmize** [comment]
- [X] delete NR synthetics alerts
- [X] verify NR server downtime alerts are off
- [X] delete route53 healthchecks
- [X] review & delete all deis apps 
- [ ] delete auto scaling group
- [ ] delete launch configuration
- [ ] review & delete ELBs

**Comment by jgmize** [comment]
Decom complete.
