### ISSUE TITLE
Netlify recommendation

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#807]

**Comment by pmac** [comment]
Current recommendation is to not use Netlify for production for now. The enterprise plans are too expensive and the normal plans would still require sec-review and the consensus is that it's not worth it for us at preset. This may change if our workload should shift to more small static one-off sites.

I will follow-up with Netlify with our decision and inquire if it's possible for us to keep a free minimal team account for our low-traffic non-production sites (e.g. perf-dashboard and dev version of protocol design system).
