### ISSUE TITLE
evaluate K8s hosted caching for SUMO

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#827]
- do we need persistent storage for work queues?

**Comment by jgmize** [comment]
- https://github.com/spotahome/redis-operator
- https://github.com/AmadeusITGroup/Redis-Operator
- https://github.com/jw-s/redis-operator

**Comment by glogiotatidis** [comment]
> do we need persistent storage for work queues?

Celery uses Redis so ideally yes. Most jobs (if not all) though are cron like and it should be OK if we skip a couple. But we'll have to verify this before making a call.

We also store session info in Redis, so having two separate Redis clusters would require to switch to database backed sessions which in turn would increase db load. Given that we've experienced db bottlenecks in the past, albeit with a smaller db size, maybe it's better to avoid the extra load.

My take is that the current AWS hosted Redis cluster is OK. I believe it's acceptable to experience a few minutes downtime -as happened on Sunday- while Redis auto-recovers and I'd prefer to spend engineering hours to
 1. Improve the CDN situation in Frankfurt and also put a CDN in front of SUMO.
 2. Decouple critical components of SUMO from Kitsune, like the In Product Redirects.

**Comment by metadave** [comment]
thank you @glogiotatidis!

**Comment by jgmize** [comment]
I think we should evaluate a hybrid approach:
- independent clusters hosted in each cluster which serve as cache and/or cluster-local celery queues
- shared elasticache cluster handles only sessions

**Comment by jgmize** [comment]
Context pasted from #meao-infra on irc.mozilla.org:

4:07 AM <meao-slack> BOT_ALERT: SUMO prod (SUMO Prod Oregon B violated SUMO Prod Oregon-B Synthetics) - <https://alerts.newrelic.com/accounts/1299394/incidents/27359581>
4:09 AM <meao-slack> BOT_ALERT: @slackbot uploaded a file: ALARM: "SUMO_Prod_Oregon-A-awsroute53-cbd6cd55-ab9d-4d90-80f8-7b6be2da7..." in US East (N. Virginia)
4:09 AM — •jgmize looking
4:09 AM <meao-slack> BOT_ALERT: @slackbot uploaded a file: ALARM: "SUMO_Prod_Oregon-awsroute53-792aea7a-0389-4e7f-ace7-ff241f08a3c..." in US East (N. Virginia)
4:09 AM <meao-slack> BOT_ALERT: @slackbot uploaded a file: ALARM: "SUMO_Prod_Oregon-B-awsroute53-9c72a915-d33e-41c8-971c-cd81f2db1..." in US East (N. Virginia)
4:10 AM <meao-slack> BOT_ALERT: SUMO prod (SUMO Prod Oregon A violated SUMO Prod Oregon-A Synthetics) - <https://alerts.newrelic.com/accounts/1299394/incidents/27359759>
4:11 AM <•jgmize> it appears to be an issue with redis
4:11 AM <•jgmize> https://rpm.newrelic.com/accounts/1299394/applications/45098028
4:12 AM <•jgmize> both clusters currently share the same elasticache redis cluster. 
4:12 AM <•jgmize> (unfortunately)
4:12 AM <•jgmize> we may want move the cache to independent redis clusters
4:13 AM <meao-slack> BOT_ALERT: SUMO prod (sumo-prod-oregon-a violated Error percentage (High)) - <https://alerts.newrelic.com/accounts/1299394/incidents/27359911>
4:13 AM <•jgmize> we could still have  a shared session store, but a session store downtime could gracefully degrade automatically to read-only mode
4:13 AM — •jgmize reading elasticache events
4:16 AM <meao-slack> BOT_ALERT: SUMO prod (SUMO Prod Oregon A violated SUMO Prod Oregon-A Synthetics) - <https://alerts.newrelic.com/accounts/1299394/incidents/27359759>
4:16 AM <meao-slack> BOT_ALERT: SUMO prod (SUMO Prod Oregon B violated SUMO Prod Oregon-B Synthetics) - <https://alerts.newrelic.com/accounts/1299394/incidents/27359581>
4:17 AM <•jgmize> shared-redis-002 cache-cluster Sat Jul 07 19:10:09 GMT-500 2018 Finished recovery for cache nodes 0001
4:17 AM <•jgmize> shared-redis-002 cache-cluster Sat Jul 07 19:07:17 GMT-500 2018 Recovering cache nodes 0001
4:17 AM <•jgmize> shared-redis-002 cache-cluster Sat Jul 07 19:00:53 GMT-500 2018 Recovering cache nodes 0001
4:18 AM <meao-slack> BOT_ALERT: SUMO prod (sumo-prod-oregon-a violated Error percentage (High)) - <https://alerts.newrelic.com/accounts/1299394/incidents/27359911>
4:18 AM <•jgmize> latency and apdex have recovered, throughput still recovering
4:19 AM <•jgmize> ^ for oregon-{a,b}
4:19 AM <•jgmize> https://rpm.newrelic.com/accounts/1299394/applications/45097089
4:19 AM <•jgmize> https://rpm.newrelic.com/accounts/1299394/applications/45098028
4:20 AM <•jgmize> https://screenshots.firefox.com/69WptbPuhjAt5lxf/rpm.newrelic.com
4:21 AM <•jgmize> https://screenshots.firefox.com/47An7VOYehZEW8pb/rpm.newrelic.com

**Comment by jgmize** [comment]
We had another redis node failure resulting in a few minutes downtime similar to the incident on Jul 8 above. The evaluation of the alternative architecture suggested above has not been a priority, as there are other issues with the site with higher risk & impact.

**Comment by jgmize** [comment]
Since we're considering splitting the cache away from the sessions & task queue, we may also want to consider switching to memcached instead of redis for that purpose.
