### ISSUE TITLE
Set up hosting for Protocol design system static site

### ISSUE THREAD

**Issue by craigcook** [mozmeao/infra#830]
Our design system uses a static site generator and is currently deploying to a personal account on Netlify (https://mozilla-protocol.netlify.com/) which has been great for the early phases of development. But now we're ready to give it a more permanent home for production. We'd like it to live at protocol.mozilla.org but if the subdomain proves impossible we can register a new domain.

The git repo is https://github.com/mozilla/protocol/

We'd like this soonish but it's certainly not urgent. I'm not sure what the first step is, or I guess second step if filing this issue is the first one. What's next? What info do you need to start the ball rolling?

**Comment by jgmize** [comment]
> I can submit a bug to point protocol.mozilla.org point at protocol.moz.works, which we can then point wherever we want.
>>    @jgmize do we need special permission to use a subdomain of mozilla.org, or should we use mozilla.net instead?

Mozilla.org subdomains do have additional security requirements, but I don't believe there should be any issues for a static site. I went ahead and filed https://bugzilla.mozilla.org/show_bug.cgi?id=1462101

**Comment by pmac** [comment]
> Did you want to stay with Netlify hosting, or a simple S3 bucket + Cloudfront?

My understanding (and what I told Craig on IRC) is that we can't get a "real" Netlify account (one that will give us team management of apps) and so we shouldn't use it for anything since we'd have to just use individual private accounts. Unless that changes, we'll need to go with S3 + Cloudfront or Github Pages for all hosting of static sites, both dev/demo and prod.

**Comment by metadave** [comment]
I forgot about the [recent changes](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) to Github pages. Would that be easier for folks?

**Comment by pmac** [comment]
> I forgot about the recent changes to Github pages. Would that be easier for folks?

We talked about that some too. I think more security review would be required to host a `*.mozilla.org` domain on GH Pages even though it does now support HTTPS. Other domains though I think it could be an option depending on other requirements (e.g. headers and/or redirects).

**Comment by jgmize** [comment]
https://protocol.mozilla.org is live, but https://github.com/mozilla/protocol/pull/114/ is still open. once that has been merged then future pushes to the prod branch will be automatically deployed to that url, and pushes to the master branch will be automatically deployed to https://protocol-stage.moz.works/

**Comment by craigcook** [comment]
https://github.com/mozilla/protocol/pull/114 merged!
