### ISSUE TITLE
Create RDS event subscriptions in frankfurt and tokyo to match oregon

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#838]
Oregon: https://us-west-2.console.aws.amazon.com/rds/home?region=us-west-2#event-subscriptions:

Frankfurt: https://eu-central-1.console.aws.amazon.com/rds/home?region=eu-central-1#event-subscriptions:

Tokyo: https://ap-northeast-1.console.aws.amazon.com/rds/home?region=ap-northeast-1#event-subscriptions:

**Comment by metadave** [comment]
Done. Note, only `availability` and `failover` RDS event subscriptions appear to have SNS subscriptions. I'm not sure if `availability-email` and `failover-email` do anything.
