### ISSUE TITLE
Create https://snippets-admin.mozilla.org

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#843]
We want `snippets-admin` deis app to listen to the new URL `https://snippets-admin.mozilla.org`.

This is a request for the appropriate DNS entries, SSL certs and ELBs.

The app now listens to both

 - snippets-admin.us-west.moz.works and
 - snippets-admin.moz.works

The later is not used so feel free to replace it with `snippets-admin.mozilla.org`

Related bugs:
 - [AS Router Remote Provider Message Previewing](https://bugzilla.mozilla.org/show_bug.cgi?id=1463836)
 - https://github.com/mozmeao/snippets-service/issues/532

**Comment by jgmize** [comment]
filed https://bugzilla.mozilla.org/show_bug.cgi?id=1465899

**Comment by jgmize** [comment]
filed https://bugzilla.mozilla.org/show_bug.cgi?id=1470931

**Comment by jgmize** [comment]
arn:aws:acm:us-west-2:236517346949:certificate/95897544-d03f-496c-9b60-9c20be4e0696 has now been issued and https://snippets-admin.mozilla.org now works
