### ISSUE TITLE
New Relic agent - Python upgrade from 2.6.x | 3.3.x

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#849]
You are receiving this notice because one or more of your Python applications being monitored by New Relic are using Python version 2.6.x or version 3.3.x. As of July 1, 2018, new releases of the New Relic Python Agent will no longer officially support Python 2.6.x and Python 3.3.x.

What does this mean for you?

Post July 1, 2018, all Python agent releases will ship without support for version 2.6.x and 3.3.x of the Python language. Historical versions of the New Relic Python Agent released prior to July 1, 2018, will continue to support Python 2.6.x and 3.3.x, but New Relic will not be releasing any patches or security fixes for those historical versions.

What action is required from you?

You should consider upgrading to the latest version of Python and re-install the agent to ensure you are optimally running and monitoring your applications with New Relic. Optionally, you may remain on a New Relic Python Agent version less than 4.0.

What is the minimum version of Python that will be officially supported?

Python version 2.7.

Why are we discontinuing the support for Python 2.6 and Python 3.3?

Python 2.6 was officially EOL’ed by Python software foundation in October 2013 and Python 3.3 was officially EOL’ed by the Python software foundation in September 2017. In addition, many major Python core tools have ceased to support Python 2.6.x and 3.3.x. This implies that there will be no additional bug fixes or security patches released for these versions.

If you have any issues or concerns relating to the deprecation of version 2.6.x or version 3.3.x of the Python language you are using, please contact support or check out the information posted on our community forum.

**Comment by metadave** [comment]
cfdd is Python 2.7.15

**Comment by jgmize** [comment]
I believe @metadave verified that all of our apps run newer versions of Python than those affected by this issue.
