### ISSUE TITLE
investigate using Kibana for SUMO queries

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#852]
https://github.com/mozmeao/infra/issues/770#issuecomment-394749549

**Comment by metadave** [comment]
Kibana is enabled for the sumo-failover DB, username/creds aren't available outside of sre/backend engineering yet. 

@glogiotatidis any thoughts on this?

**Comment by glogiotatidis** [comment]
hi @turtlelovesshoes!

does your `+1` mean that you folks are familiar with Kibana and are able to find the answers you're looking for there given that you have access and the data you're want to process is available? Would that work instead of direct DB access?

**Comment by glogiotatidis** [comment]
> Kibana is enabled for the sumo-failover DB, username/creds aren't available outside of sre/backend engineering yet.

thanks @metadave :metal:

**Comment by turtlelovesshoes** [comment]
@glogiotatidis 
> `does your +1 mean that you folks are familiar with Kibana and are able to find the answers you're looking for there given that you have access and the data you're want to process is available? 

I am becoming more familiar with Kibana. I stared looking here: [https://www.elastic.co/webinars/getting-started-kibana], but it looks pretty easy to learn. 

> 'Would that work instead of direct DB access?`

Yes, it would require a little syntax translation by creating filters. It would save a lot of time for the extra visualization step required as well. 

What is the price to add the team? When can we start? 💃

**Comment by rtanglao** [comment]
@metadave  @turtlelovesshoes i am in for kibana if and only if it allows me to access the same data and the same sorts of queries as SQL (which I think it does)

**Comment by rtanglao** [comment]
my use case: 
I as a SUMO  analyst want to be able to access  all the "ask a question"  and "contributor forum" meta data so i can do arbitrary ad-hoc and not predictable in advance  firefox desktop and fennec SUMO queries for reporting to product management and product marketing about Firefox support

**Comment by rtanglao** [comment]
and yes when can we start :-) !!!!

**Comment by metadave** [comment]
@turtlelovesshoes @rtanglao I believe the data in Elasticsearch is a small subset of the data that's in the database. I can create accounts for you if you want to poke around and see what's available. 

Please create accounts on https://keybase.io/ and let me know your Keybase username so I can securely send you an Elasticsearch username/password.

**Comment by turtlelovesshoes** [comment]
I have created an account, I can send you the account name via email. However, we are really looking for a tool that will provide read only access to the entirety for requests to show impact on the efforts of the community, the team and projects. Would you be open to a conversation on a tool that has has these core features for admin that currently are not accessible or the means by which to add more of the databases to the tool?
Thank you.

**Comment by metadave** [comment]
@turtlelovesshoes I'll bring this up with the team during the next standup. I'm pretty sure Kibana doesn't have all the data you want, and we don't have a simple way to give out external access to the DB.

**Comment by turtlelovesshoes** [comment]
Please take note of the impact that this is having on the team as well. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1262944
https://bugzilla.mozilla.org/show_bug.cgi?id=1474481

There is another tool in mozilla, bitergia, https://analytics.mozilla.community/ that seems to have kibana or similar functionality, is this tool limited access to kitsune as well because of outdated software libraries?

Having access to metrics is essential to the day to day jobs of community managers and support product analysts, you could say that the experience developed from not having proper dashboards or tool resources for so long and the engineering background of those on the SUMO team would qualify access and trust here.

**Comment by metadave** [comment]
@jgmize @pmac @glogiotatidis @bensternthal 
https://github.com/mozmeao/infra/issues/770

**Comment by glogiotatidis** [comment]
> There is another tool in mozilla, bitergia, https://analytics.mozilla.community/ that seems to have kibana or similar functionality, is this tool limited access to kitsune as well because of outdated software libraries?

The tool build by Bitergia is not collecting stats from Kitsune afaik. This has nothing to do with outdated libraries in Kitsune. In Austin I talked with members of Open Innovation Team (working with Bitergia) and members of SUMO and we all agreed that's a good idea to integrate so we can leverage this new platform and remove Kitsune dashboards. AFAIK no action has been taked on that yet.

**Comment by metadave** [comment]
While I created a read-only account in Kibana, I have not yet forwarded the creds to @turtlelovesshoes  as we were going to pursue https://github.com/mozmeao/infra/issues/770 instead. However, there may be some networking roadblocks so I'll continue to setup a Kibana account and permissions and forward them along.

**Comment by metadave** [comment]
Kibana creds sent to @turtlelovesshoes
