### ISSUE TITLE
Document manual recovery steps taken to recover from failed k8s master instance in tokyo

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#853]
-  updated api.internal.tokyo.moz.works and  tokyo.moz.works in route 53 via web console
  - related: https://github.com/kubernetes/kops/issues/2634
  - [ ] decide between PR to kops or migration to [EKS](https://github.com/mozmeao/infra/issues/854) &/or [GKE](https://github.com/mozmeao/infra/issues/778) as next action

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/pull/858
