### ISSUE TITLE
EKS eval

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#854]
See also #853

**Comment by metadave** [comment]
At the moment, EKS is only available in Oregon and Virginia.

**Comment by jgmize** [comment]
Thanks to the discussion after @danielhartnell's EKS presentation, we can rule this out in favor of continuing to use kops for AWS clusters.

**Comment by jgmize** [comment]
Now that EKS has had some time to mature, we should re-evaluate EKS vs continuing to use kops.

**Comment by metadave** [comment]
let's talk with @danielhartnell regarding his EKS experience

**Comment by jgmize** [comment]
Per discussion with @danielhartnell, @metadave, and @jpetto we didn't find any compelling reasons to switch from kops to EKS at this time.
