### ISSUE TITLE
transition all ACM certs from email to DNS validation

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#876]

**Comment by jgmize** [comment]
see https://docs.google.com/spreadsheets/d/1mTLW5dNPzsu6fAFFqws1cXJ8QpW3azIb-19D9MoVnog/edit?usp=sharing for several expiring in the next 2 weeks that cannot be renewed via email and will need to be replaced with new certs validated by DNS.

**Comment by metadave** [comment]
https://gist.github.com/metadave/602ce211ea9f847d58c8bb52333366c1

**Comment by metadave** [comment]
July certs have been processed in [the spreadsheet](https://docs.google.com/spreadsheets/d/1mTLW5dNPzsu6fAFFqws1cXJ8QpW3azIb-19D9MoVnog/edit?usp=sharing). 

- bedrock-stage frankfurt ELB will use *.frankfurt.moz.works cert
- bedrock-prod frankfurt ELB will use *.frankfurt.moz.works cert
- https://github.com/mozmeao/infra/pull/879


*.allizom cert request DNS validation: https://bugzilla.mozilla.org/show_bug.cgi?id=1473086

**Comment by jgmize** [comment]
MDN staging cert replaced

**Comment by escattone** [comment]
Thanks @metadave and @jgmize!

**Comment by metadave** [comment]
We'll be tracking the remaining certs in [this](https://github.com/mozmeao/infra/milestone/160 milestone
