### ISSUE TITLE
Pull subnets from external URL(s) for sumo-autoblock

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#882]
- https://s3.amazonaws.com/mozilla_infosec_blocklist/ipblocklist
- https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=61248764
- https://mana.mozilla.org/wiki/display/POLICIES/Standard%3A+MozDef+Blocklist+Usage

**Comment by metadave** [comment]
SUMO hosting has moved to another team.
