### ISSUE TITLE
Figure out deployment differences for geographically close clusters

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#885]
@jpetto saw an issue yesterday with bedrock that was causing static assets for a new page to 404. The newly built and deployed image had the new static assets and was serving them no problem, but the page was broken in the browser for him. What I believe happened is that he hit a pod in Oregon for the HTML and was hitting one in Iowa for the assets. Based on the IRC bot output from the deployment the production deployment in the Iowa cluster happened just over an hour after the one finished in Oregon. Since these clusters are geographically closer than the others I think we may see this issue more often than we did before. I think we can potentially take a few steps that will help:

1. Change deployment order for bedrock to deploy clusters in geographic order to minimize the time between the 2 North American cluster deployments
2. Look into potentially doing deployments by continent, and not just by cluster: i.e. deploy oregon-stage, then iowa-stage, then oregon-prod, then iowa-prod. 
3. Look into some technique for pinning a user session to a cluster once they've received the first response.

I'm sure there are other things we can try. This could easily happen for updated assets on a page as well as this case of a new page.

**Comment by pmac** [comment]
I'm putting this in infra because I believe this is an issue that could affect any site hosted in these clusters, and especially something like Kitsune when oregon-a is a different version than oregon-b.

**Comment by pmac** [comment]
Just talked to @alexgibson about this a bit on IRC and this deployment strategy should also work:

1. Deploy to all staging apps in all clusters simultaneously
2. Test all staging apps simultaneously (possibly only running the full suite in Oregon like we currently do)
3. If all stage tests passed deploy to all prod apps in all clusters simultaneously
4. Test all prod apps simultaneously

That would make the situation better and improve deployment times. It will take some deployment refactoring, but we're doing that now anyway with the move to native k8s.

Another thing to think about is that we could completely rethink our approach to hosting static assets. There are things we miss about having one place for these files as well as not getting rid of old hashed files as soon as the contents change. So it might be time to revisit syncing static files to s3 for hosting.

@metadave @jgmize I'm very much interested in your opinions on these points when you get a chance.

**Comment by metadave** [comment]
> Deploy to all staging apps in all clusters simultaneously

Doesn't this make the git-sync-operator easier to use, as we don't need region-specific commits for serial deployments @jgmize?

**Comment by jgmize** [comment]
> Another thing to think about is that we could completely rethink our approach to hosting static assets. There are things we miss about having one place for these files as well as not getting rid of old hashed files as soon as the contents change. So it might be time to revisit syncing static files to s3 for hosting.

Yes, this is an issue that will occur during rolling deployments within each cluster too. While it is slightly mitigated by CDN caching, I still think moving them to object storage is probably the best approach. 

>>    Deploy to all staging apps in all clusters simultaneously

>Doesn't this make the git-sync-operator easier to use, as we don't need region-specific commits for serial deployments @jgmize?

@metadave and I discussed the trade-offs of this approach, and we agreed that it's worth implementing sooner rather than later. We started working on this earlier today, and should hopefully have something worth testing tomorrow.

**Comment by jgmize** [comment]
> I still think moving static assets to object storage is probably the best approach.

Another approach I briefly considered would be to use EFS (or the GCP equivalent, https://cloud.google.com/filestore/) similar to MDN, but the operational advantages of object storage are pretty compelling to me.

**Comment by pmac** [comment]
Would we want to put said object storage behind CloudFront or is it possible via CloudFlare to add a separate origin for the `/media/*` URLs or just add another CloudFlare CDN endpoint?

**Comment by pmac** [comment]
This should also have the benefit of us handling thousands fewer requests and a thus a significant reduction in log volume and potentially server load. I'm looking into a few things now:

1. How we should do the upload?

    Currently the static assets are built during the docker build step. We could simply sync them to s3 with a script we run in Jenkins, or use something like `django-storages` to upload them as they're built in a step after the image is built. 
2. We need to be sure that we're setting proper `CacheControl` headers. We may need to do something custom with the upload to s3 to set very long expiry headers for the hashed file names.

**Comment by jgmize** [comment]
> Would we want to put said object storage behind CloudFront or is it possible via CloudFlare to add a separate origin for the /media/* URLs or just add another CloudFlare CDN endpoint?

Yes, I believe we can accomplish this with a [resolve override in a page rule](https://support.cloudflare.com/hc/en-us/articles/206190798-Using-Resolve-Override-in-Page-Rules).

**Comment by pmac** [comment]
Great! Sounds good. Let's do it :shipit:

**Comment by pmac** [comment]
This is in progress in #889

**Comment by jgmize** [comment]
www.mozilla.org/media/* is now backed by bedrock-prod-media.s3.amazonaws.com via a cloudflare page rule.
