### ISSUE TITLE
Enable s3-backed static media for bedrock prod

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#889]
This has been done for bedrock stage already and seems to be working well. I followed the steps in the [cloudflare blog post on "Resolve Override"](https://support.cloudflare.com/hc/en-us/articles/206190798-Using-Resolve-Override-in-Page-Rules) to enable a different origin for `/media/*` requests on stage. Steps were:

1. Add a `CNAME` to the `DNS` tab in CloudFlare settings using `www-media` as the name and `bedrock-stage-media.s3.amazonaws.com` as the domain.
2. Add a Page Rule for `www.allizom.org/media/*` adding the appropriate settings (see the stage settings in CloudFlare for final list). The primary setting is `Resolve Override = www-media.allizom.org` and `Host Header Override = bedrock-stage-media.s3.amazonaws.com`.
3. Test

Enabling on prod should be mostly the same substituting "mozilla" for "allizom". We need to decide what level of testing stage needs to pass before we're comfortable doing this in production. We also discussed some level of redundancy with a replica s3 bucket in another AWS region, but failover or load-balancing for that 2nd bucket is yet to be decided.

**Comment by pmac** [comment]
What say you @metadave @jgmize @jpetto ?

**Comment by metadave** [comment]
/me has typed several things but will have to think about it for a bit.

**Comment by pmac** [comment]
/me has similar feelings
/me will sleep on it and comment more tomorrow

**Comment by pmac** [comment]
Sounds like a fine idea to me. I'm guessing amazon won't do that for you with a single bucket name with replication turned on?

**Comment by metadave** [comment]
bucket replication would save us manually copying to the second bucket during a deploy, but I think we'd still need a DNS name in front to choose a bucket in a failover scenario.

**Comment by metadave** [comment]
We're going to create an additional bucket in eu-central-1 (Frankfurt) and replicate files to it. A new traffic policy will be put in front of both S3 buckets, which gives us the flexibility to do weighted/geo/failover routing. Cloudflare will hit this traffic policy and the [Kwisatz Haderach](http://dune.wikia.com/wiki/Kwisatz_Haderach) will be born.

So the idea would be:

Cloudflare -> bedrock-stage-media.moz.works (TP) -> [bedrock-stage-media.s3.amazonaws.com, bedrock-stage-media-failover.s3.amazonaws.com]

Cloudflare -> bedrock-prod-media.moz.works (TP) -> [bedrock-prod-media.s3.amazonaws.com, bedrock-prod-media-failover.s3.amazonaws.com]

**Comment by pmac** [comment]
I love it. I'm excited to be a part of it! Let's cross the streams!

**Comment by jgmize** [comment]
www.mozilla.org/media/* is now backed by bedrock-prod-media.s3.amazonaws.com via a cloudflare page rule.
