### ISSUE TITLE
Switch SUMO stage static media CDN to the new s3 bucket

### ISSUE THREAD

**Issue by pmac** [mozmeao/infra#898]
In #890 Dave created the s3 buckets and those are now being [filled by the SUMO deployments](https://github.com/mozilla/kitsune/pull/3272). Let's switch the SUMO staging CDN (static-media-stage-cdn.sumo.mozilla.net) over to the `sumo-stage-media` s3 bucket and do some testing.

**Comment by metadave** [comment]
@pmac Do we need a host header override here as well?

**Comment by pmac** [comment]
don't think any of that is required since cloudfront natively understands how to interface with s3.

**Comment by metadave** [comment]
CDN changes are in this WIP PR: https://github.com/mozmeao/infra/pull/899
