### ISSUE TITLE
ELB for snippets-dev.oregon-b.moz.works

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/infra#906]
I've setup `snippets-dev.oregon-b.moz.works` Deis app and the last step is an ELB with a proper cert and HTTP configuration for the `X-Forwarded-*`  headers.

A good domain sounds like `dev.snippets.moz.works`.

**Comment by glogiotatidis** [comment]
@jgmize could you please setup this up for me?

**Comment by jgmize** [comment]
https://dev.snippets.moz.works and https://snippets-dev.oregon-b.moz.works both point to the new ELB backed by the new nodeport service created in #907

**Comment by glogiotatidis** [comment]
Thanks @jgmize !
