### ISSUE TITLE
resize k8s node disk sizes down to 250GiB

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#91]
- [x] Virginia cluster
- [x] Tokyo cluster

Docs [here](https://github.com/mozmar/infra/blob/master/docs/resize_k8s_node.md)

**Comment by metadave** [comment]
@jgmize @glogiotatidis want to scale Virginia down while we're in Toronto?

**Comment by jgmize** [comment]
I think we'll have a lot going on in Toronto and that this can probably wait until after.

**Comment by metadave** [comment]
the Virginia cluster has been decommissioned.
