### ISSUE TITLE
Switch GCP logging from stackdriver to papertrail

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#914]

**Comment by metadave** [comment]
https://help.papertrailapp.com/kb/hosting-services/google-cloud-platform/#docker-containers-on-google-container-engine
https://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-kubernetes

**Comment by metadave** [comment]
Stackdriver logging has been disabled in our GKE cluster.

@jpetto @pmac @jgmize all Bedrock app logs from GCP + AWS flow into Papertrail:
[GCP us-central1](https://papertrailapp.com/groups/11347802/events)
