### ISSUE TITLE
Reserve Instance Research / Purchase

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/infra#915]
- [Budget](https://docs.google.com/spreadsheets/d/10f0u-AYJkQo0Ft2IctTgjdkXMvnd6-v0JoNk9Ei10BQ/edit#gid=780883974)
- [Casa ticket](https://biztera.com/projects/new/12280)

---

- [x] Buy EC2
- [x] Buy Elasticache
- [x] Buy RDS - Sep 27th

**Comment by metadave** [comment]
We've talked about getting rid of the `ap-northeast-1` instances (including the RDS reserved instance) hosting our Tokyo K8s cluster.

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/issues/923

**Comment by metadave** [comment]
I was able to start a new cluster w/ m5.xlarge instances in https://github.com/mozmeao/infra/issues/923.

**Comment by bensternthal** [comment]
RDS purchase complete and confirmed. I do not think anything is left on this one.
