### ISSUE TITLE
research AWS instance types: M4 vs M5

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#923]
https://aws.amazon.com/ec2/instance-types/

**Comment by metadave** [comment]
On demand pricing:

![amazon_web_services_simple_monthly_calculator](https://user-images.githubusercontent.com/58244/44928737-caf1b200-ad26-11e8-9dc7-466b2d782d29.png)

**Comment by metadave** [comment]
- `m4.xlarge` 1 year contract, all up-front us-west-2: 1014.30
- `m5.xlarge` 1 year contract, all up-front us-west-2:  1003.30

**Comment by metadave** [comment]
## m4.xlarge

```
 M4 instances provide a balance of compute, memory, and network resources, 
 and it is a good choice for many applications.
```

- 4 vcpu
- 16 GiB memory
- 750 Dedicated EBS Bandwidth (Mbps)

- 2.3 GHz Intel Xeon® E5-2686 v4 (Broadwell) processors or 2.4 GHz Intel Xeon® E5-2676 v3 (Haswell) processors
- EBS-optimized by default at no additional cost
- Support for Enhanced Networking
- Balance of compute, memory, and network resources

---

## m5.xlarge

```
M5 instances are the latest generation of General Purpose Instances. This family provides a
balance of compute, memory, and network resources, and it is a good choice for many 
applications. 2.5 GHz Intel Xeon® Platinum 8175 processors with new Intel Advanced 
Vector Extension (AXV-512) instruction set. New larger instance size, m5.24xlarge, offering 
96 vCPUs and 384 GiB of memory
```

- 4 vcpu
- 16 GiB memory
- Up to 3,500 Dedicated EBS Bandwidth (Mbps)

- Up to 25 Gbps network bandwidth using Enhanced Networking
- Requires HVM AMIs that include drivers for ENA and NVMe
- Powered by the new light-weight Nitro system, a combination of dedicated hardware and lightweight hypervisor
- Instance storage offered via EBS or NVMe SSDs that are physically attached to the host server
- With new M5d instances, local NVMe-based SSDs are physically connected to the host server and provide block-level storage that is coupled to the lifetime of the M5 instance

**Comment by metadave** [comment]
cc @jgmize @bensternthal

**Comment by bensternthal** [comment]
Price diff is negligible... so whichever way you want to go.. works for me.

**Comment by jgmize** [comment]
Let's spin up a test cluster using a command similar to the following, based on https://github.com/kubernetes/kops/issues/4690#issuecomment-398577079
```
AWS_AVAILABILITY_ZONES=eu-central-1b
kops create cluster \
	--zones ${AWS_AVAILABILITY_ZONES} \
	--master-size m5.xlarge \
	--master-zones ${AWS_AVAILABILITY_ZONES} \
	--node-count 2 \
	--node-size m5.xlarge \
	--image 379101102735/debian-stretch-hvm-x86_64-gp2-2018-06-13-59294 \
	--name frankfurt-b.moz.works\
	--yes
```

**Comment by metadave** [comment]
I was able to create a cluster w/ m5.xlarges with the following:

```
export KOPS_STATE_STORE=s3://frankfurt-kops-state
export AWS_AVAILABILITY_ZONES=eu-central-1b

./kops-1.9.2 create cluster \
	--zones ${AWS_AVAILABILITY_ZONES} \
	--master-size m5.xlarge \
	--master-zones ${AWS_AVAILABILITY_ZONES} \
	--node-count 2 \
	--node-size m5.xlarge \
	--image 379101102735/debian-stretch-hvm-x86_64-gp2-2018-06-13-59294 \
	--name frankfurt-b.moz.works\
	--yes

./kops-1.9.2 create secret --name frankfurt-b.moz.works sshpublickey admin -i ~/.ssh/frankfurt-b.pub

./kops-1.9.2 update cluster frankfurt-b.moz.works --yes
```

pub/private keys were not saved during this test.
