### ISSUE TITLE
cluster upgrade(s)

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#933]
<stretch for Sept>

**Comment by metadave** [comment]
Ark broke in Iowa (imagePullPolicy=Always) from the recent upgrade, these instructions need to be followed before upgrading clusters:https://github.com/heptio/ark/blob/master/docs/upgrading-to-v0.10.md

The alternative is to pin the image for each Ark deployment.

**Comment by jgmize** [comment]
Initiated upgrade of iowa-a to 1.10.12-gke.1

**Comment by metadave** [comment]
@jgmize any thoughts on when the oregon-b upgrade can occur?

**Comment by jgmize** [comment]
@metadave I created a calendar entry for an oregon-b upgrade on Monday, and invited you as optional.

**Comment by metadave** [comment]
@jgmize can you add Keegan + EricZ as optional?

**Comment by jgmize** [comment]
Done, thanks for the reminder.
