### ISSUE TITLE
acceptance testing (bedrock integration test suite)

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#934]

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/issues/895

**Comment by jgmize** [comment]
Currently researching test failures listed on https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/akamai-test/3/pipeline/32

**Comment by jgmize** [comment]
Test failures are due to "feature" implemented at platform level that is not configurable according to Akamai.
