### ISSUE TITLE
Elasticache maintenance in usw by Sept 30

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#938]
Per email from Amazon:

Your Amazon ElastiCache node(s) listed in “Schedule of Remaining ElastiCache Instances” section below are planned for replacement within your cluster’s current maintenance window. This replacement applies mandatory patches to improve the security, reliability, and operational performance of your ElastiCache instance. For more information about this security issue, see the following security bulletin: https://aws.amazon.com/security/security-bulletins/AWS-2018-016/.

Prefer Self-Service Maintenance? Follow the instructions here: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.NodeReplacement.html. Nodes patched from self-service maintenance will be automatically removed from the planned schedule below.

Please note that the schedule below contains planned maintenance, and nodes may still be replaced outside of these windows due to other underlying hardware issues.

Maintenance status summary for your ElastiCache fleet
-----------------------------------------------------
Total nodes applicable for maintenance: 13, Total nodes replaced so far: 11

Schedule of Remaining ElastiCache instances
-------------------------------------------
Region: us-west-2, Cluster Name: sumo-redis-shared, Node Name: sumo-redis-shared-002, Replacement Time: 09:00 UTC, Sep 30, 2018
Region: us-west-2, Cluster Name: ee-redis-rg-usw, Node Name: ee-redis-usw, Replacement Time: 13:00 UTC, Sep 30, 2018

The maintenance will begin during your cluster’s maintenance window (see the replacement time for each node above), but might finish outside the window depending on the amount of data and the load on the node(s). Replacements generally take a few minutes to complete. Syncing the data from the master node can take additional time. Depending on cluster configuration, you might see performance or availability impact during this period. For more details, please refer to ElastiCache Maintenance FAQs: https://aws.amazon.com/elasticache/elasticache-maintenance.

**Comment by metadave** [comment]
sumo-redis-shared and ee-redis-rg-usw has been manually updated.
