### ISSUE TITLE
up-to-date Windows XP can't access SUMO

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#942]
https://mozilla.slack.com/archives/C4DP9MR70/p1537780637000100

https://support.mozilla.org/en-US/kb/end-support-windows-xp-and-vista

**Comment by metadave** [comment]
@alexgibson do you have an XP VM that can be used to test sumo? I made a small change to the cipher suite that might resolve the issue.

**Comment by metadave** [comment]
I added `DES-CBC3-SHA ` to the ELB, which allows XP to connect and retrieve HTML. However, it looks like the media CDN (E32HYUOKY48QWE) doesn't work with clients that don't support `*-RSA-*` based ciphers:

```
If you're using an SSL/TLS certificate in AWS Certificate Manager, a viewer must support one of the *-RSA-* ciphers.
```

From:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html#secure-connections-supported-ciphers

**Comment by pmac** [comment]
well that's unfortunate. It's a bummer to have to switch CDNs for this, but I think we might. It's important for the support site to support these users.

**Comment by pmac** [comment]
or I guess we don't have to switch CDNs, but switch to manual cert management?

**Comment by jgmize** [comment]
Just to clarify the scope of this issue, I believe that even very old versions of Firefox should still be abpe to load assets from the sumo CDN on XP without any changes. @alexgibson would you be willing to confirm this with your XP VM?

**Comment by alexgibson** [comment]
> @alexgibson would you be willing to confirm this with your XP VM?

Using Firefox 52 ESR I can view SUMO fine yes.

It's worth noting that we're currently directing a lof of XP users to [this article in particular](https://support.mozilla.org/en-US/kb/end-support-windows-xp-and-vista), including non-FF users who are still trying to download.

According to GA, we still get a significant long-tail of legacy IE traffic:

![screenshot_2018-09-26-analytics-360](https://user-images.githubusercontent.com/400117/46073713-9afaca80-c17d-11e8-9abb-1c2c4d4c2cc6.png)

**Comment by metadave** [comment]
I'm going to try a LetsEncrypt cert on the stage CDN

**Comment by metadave** [comment]
@alexgibson can you let me know how stage looks in XP?

Here's a direct link to an image on the stage CDN w/ letsencrypt cert:
https://stage-cdn.sumo.mozilla.net/uploads/products/2018-09-24-09-19-19-d6a5c9.png

**Comment by alexgibson** [comment]
No joy sadly :(

<img width="1672" alt="screen shot 2018-09-26 at 16 14 16" src="https://user-images.githubusercontent.com/400117/46089849-4cfabc80-c1a7-11e8-9930-33a1d7428e5a.png">

**Comment by alexgibson** [comment]
By the way, if it makes debugging easier - I'm testing this using BrowserStack. You can sign up for a limited trial at no cost: https://www.browserstack.com/

**Comment by pmac** [comment]
Based on a slack conversation it seems like we've agreed to stop attempting to support XP at the CDN. I'll file an issue on kitsune to try to do something outside of the CDN for IE < 9 to clean up the content a bit if the CDN fails to load. Or perhaps for everyone if the CDN fails to load, since that is a thing that can happen to anyone really if DNS goes wonky.

**Comment by pmac** [comment]
For the curious I have filed https://github.com/mozilla/kitsune/issues/3336

**Comment by metadave** [comment]
> I'm going to try a LetsEncrypt cert on the stage CDN

Cert change has been reverted for the SUMO stage CDN.
