### ISSUE TITLE
[Cloudflare]: The SSL Certificate for www.mozilla.org will expire on Nov 14, 2018

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#955]
Same for www.allizom.org cert installed in cloudflare.

**Comment by metadave** [comment]
where do we go about requesting certs nowadays?

**Comment by jgmize** [comment]
The Cloudflare certs are not suitable for production because the Organization on the cert says "Cloudflare", and our legal team wants the organization on the cert to say "Mozilla Corporation". The simplest path forward is a renewal of our existing cert, and I've requested that in https://bugzilla.mozilla.org/show_bug.cgi?id=1503544#c2.

**Comment by jgmize** [comment]
We installed the cert from [bug 1503544] today. The new cert expires November 13, 2019.
