### ISSUE TITLE
Verify www.mozilla.org for yandex webmastertools

### ISSUE THREAD

**Issue by rraue** [mozmeao/infra#956]
I would like to get more insights into the Russian search market and how we can improve our rankings and as Yandex is the biggest search engine there, I need www.mozilla.org to be verified:
<img width="1728" alt="screen shot 2018-10-18 at 13 31 12" src="https://user-images.githubusercontent.com/36700618/47166875-71a50880-d2fd-11e8-8105-58f4061d708e.png">

**Comment by jgmize** [comment]
@rraue it looks like the HTML or meta tag options indicated in your screenshot might be simpler due to the infoblox error above. Can you paste the text of the meta tag and HTML file into comments in this issue?

**Comment by rraue** [comment]
I would not like to have another line of unnessesary code in the head, so I think its better with the file than the meta tag:
> In the site's root directory, create the file yandex_7bdb48599fe21f87.html with the following content:
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>Verification: 7bdb48599fe21f87</body>
</html>
```
> Make sure that the file at https://www.mozilla.org/yandex_7bdb48599fe21f87.html opens

**Comment by metadave** [comment]
cc @jpetto @pmac

**Comment by pmac** [comment]
@rraue cool. let's just go with the HTML file then. File an issue in the bedrock repo to have that file added with the content from your comment.
