### ISSUE TITLE
Eval revsys optimized python docker base images

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#960]
According to https://www.revsys.com/tidbits/optimized-python/ images built by https://github.com/revsys/optimized-python-docker are smaller and faster than the base images we switched to in #641.

**Comment by escattone** [comment]
Interested to see what you think here! I think my only worry is that they won't maintain it as well as the official Python images.

**Comment by pmac** [comment]
Exactly my thoughts @escattone, but interesting nonetheless. Good find Josh.

**Comment by jwhitlock** [comment]
Kuma's blocked by the [Python 3 update](https://bugzilla.mozilla.org/show_bug.cgi?id=1467518), since this requires 3.6.

**Comment by jgmize** [comment]
There are python 2.7 builds available, but they're older: https://hub.docker.com/r/revolutionsystems/python/tags/
