### ISSUE TITLE
cold backups for SUMO

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#977]

**Comment by jgmize** [comment]
https://aws.amazon.com/blogs/aws/aws-backup-automate-and-centrally-manage-your-backups/

**Comment by metadave** [comment]
AWS backup is limited to:
- US East (N. Virginia)
- US East (Ohio)
- EU (Ireland)
- US West (Oregon)

**Comment by metadave** [comment]
SUMO hosting has moved to another team.
