### ISSUE TITLE
New CI/CD pipeline for snippets

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#986]

**Comment by glogiotatidis** [comment]
Will this be something we do along with the GCP move? Asking b/c snippets is still on Deis and we probably need to do infra changes to do the CI/CD ones?

**Comment by jgmize** [comment]
The GCP migrations have been de-prioritized, and this issue will focus on replacing the existing Jenkins pipeline deployments to the existing clusters in AWS. The current plan is to follow the template established in https://github.com/mozmeao/infra/issues/1117 in frankfurt & oregon-b.

**Comment by jgmize** [comment]
When we did the initial deployments in nucleus, we used a [different selector type](https://github.com/mozmeao/nucleus-config/commit/62d25be7a22b9abe6efc37713d5419b415391341) than the existing deployments managed by Deis Workflow so that we could validate everything else was working before routing traffic to it. We plan on adopting a similar strategy for this rollout.

**Comment by jpetto** [comment]
Pipeline is running and we are in dev/stage/prod!

🕺 💃 🎉 🐤 😸 🥂 🍻 🏖
